window.traderCatalogue={traderName:'Rolf',currency:'ZOMBIE_NOTES',currencyLabel:'Zombie Notes',items:[
{name:'Camo Green Gas Mask Filter',className:'camogreen_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Christmas Gas Mask Filter',className:'christmas_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Cow Gas Mask Filter',className:'cow_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Green Pixel Gas Mask Filter',className:'greenpixel_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Halloween Gas Mask Filter',className:'halloween_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Red Scale Gas Mask Filter',className:'redscale_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Rick & Morty Gas Mask Filter',className:'rickandmorty_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'SpongeBob Gas Mask Filter',className:'spongebob_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Ammo Workbench',className:'ammo_workbench_box',category:'Workbenches',mode:'sell',price:5000},
{name:'Repair Workbench',className:'repair_workbench_box',category:'Workbenches',mode:'sell',price:5000},
{name:'Mag Loader Cleaning Kit',className:'magloadercleaningkit',category:'Mag Loaders',mode:'sell',price:100},
{name:'Magazine Loader',className:'km_magazineloader2',category:'Mag Loaders',mode:'sell',price:750},
{name:'Compass',className:'compass',category:'Navigation',mode:'sell',price:50},
{name:'GPS Receiver',className:'gpsreceiver',category:'Navigation',mode:'sell',price:100},
{name:'Orienteering Compass',className:'orienteeringcompass',category:'Navigation',mode:'sell',price:50},
{name:'Camo Sleeping Bag',className:'lbs_sleepingpacked_new_camo',category:'Sleeping Bags',mode:'sell',price:500},
{name:'Lbs Sleepingpacked Extended Cow',className:'lbs_sleepingpacked_extended_cow',category:'Sleeping Bags',mode:'sell',price:500},
{name:'Lbs Sleepingpacked Extended Palm',className:'lbs_sleepingpacked_extended_palm',category:'Sleeping Bags',mode:'sell',price:500},
{name:'Lbs Sleepingpacked Extended Red Scale',className:'lbs_sleepingpacked_extended_red_scale',category:'Sleeping Bags',mode:'sell',price:500},
{name:'Lbs Sleepingpacked Extended Rick And Morty',className:'lbs_sleepingpacked_extended_rick_and_morty',category:'Sleeping Bags',mode:'sell',price:500},
{name:'Lbs Sleepingpacked Extended Stranger Things',className:'lbs_sleepingpacked_extended_stranger_things',category:'Sleeping Bags',mode:'sell',price:500},
{name:'Lbs Sleepingpacked Extended Zedklr',className:'lbs_sleepingpacked_extended_zedklr',category:'Sleeping Bags',mode:'sell',price:500},
{name:'Lbs Sleepingpacked New Blue',className:'lbs_sleepingpacked_new_blue',category:'Sleeping Bags',mode:'sell',price:500},
{name:'Blue Fish Hat',className:'geb_bluefishhat',category:'Geb\'s Fishing Gear',mode:'buy',price:125},
{name:'Blue Fish Shirt',className:'geb_bluefishshirt',category:'Geb\'s Fishing Gear',mode:'buy',price:175},
{name:'Blue Fishing Gloves',className:'geb_bluefishgloves',category:'Geb\'s Fishing Gear',mode:'buy',price:75},
{name:'Geb Greenfishhat',className:'geb_greenfishhat',category:'Gebs Fishing Gear',mode:'buy',price:125},
{name:'Geb Greenfishshirt',className:'geb_greenfishshirt',category:'Gebs Fishing Gear',mode:'buy',price:175},
{name:'Geb Orangefishgloves',className:'geb_orangefishgloves',category:'Gebs Fishing Gear',mode:'buy',price:75},
{name:'Geb Purplefishhat',className:'geb_purplefishhat',category:'Gebs Fishing Gear',mode:'buy',price:125},
{name:'Geb Purplefishshirt',className:'geb_purplefishshirt',category:'Gebs Fishing Gear',mode:'buy',price:175},
{name:'Geb Redfishhat',className:'geb_redfishhat',category:'Gebs Fishing Gear',mode:'buy',price:125},
{name:'Geb Redfishshirt',className:'geb_redfishshirt',category:'Gebs Fishing Gear',mode:'buy',price:175}
]};
