window.traderCatalogue={traderName:'Rolf',currency:'ZOMBIE_NOTES',currencyLabel:'Zombie Notes',items:[
{name:'Camo Green Gas Mask Filter',className:'camogreen_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Christmas Gas Mask Filter',className:'christmas_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Cow Gas Mask Filter',className:'cow_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Green Pixel Gas Mask Filter',className:'greenpixel_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Halloween Gas Mask Filter',className:'halloween_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Red Scale Gas Mask Filter',className:'redscale_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Rick & Morty Gas Mask Filter',className:'rickandmorty_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'SpongeBob Gas Mask Filter',className:'spongebob_gasmask_filter',category:'NBC Gear',mode:'sell',price:550},
{name:'Ammo Workbench',className:'ammo_workbench_box',category:'Workbenches',mode:'sell',price:5000},
{name:'Repair Workbench',className:'repair_workbench_box',category:'Workbenches',mode:'sell',price:5000},
{name:'Mag Loader Cleaning Kit',className:'magloadercleaningkit',category:'Mag Loaders',mode:'sell',price:100},
{name:'Magazine Loader',className:'km_magazineloader2',category:'Mag Loaders',mode:'sell',price:750},
{name:'Compass',className:'compass',category:'Navigation',mode:'sell',price:50},
{name:'GPS Receiver',className:'gpsreceiver',category:'Navigation',mode:'sell',price:100},
{name:'Orienteering Compass',className:'orienteeringcompass',category:'Navigation',mode:'sell',price:50},
{name:'Camo Sleeping Bag',className:'lbs_sleepingpacked_new_camo',category:'Sleeping Bags',mode:'sell',price:500},
{name:'Blue Fish Hat',className:'geb_bluefishhat',category:'Geb\'s Fishing Gear',mode:'buy',price:125},
{name:'Blue Fish Shirt',className:'geb_bluefishshirt',category:'Geb\'s Fishing Gear',mode:'buy',price:175},
{name:'Blue Fishing Gloves',className:'geb_bluefishgloves',category:'Geb\'s Fishing Gear',mode:'buy',price:75}
]};
