window.traderCatalogue={traderName:'Indar',currency:'USD',items:[
{name:'Ak101',className:'ak101',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4225,sellPrice:2112},
{name:'Ak101 Black',className:'ak101_black',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4225,sellPrice:2112},
{name:'Ak101 Green',className:'ak101_green',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4225,sellPrice:2112},
{name:'Ak74',className:'ak74',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:9370,sellPrice:4685},
{name:'Ak74 Black',className:'ak74_black',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:9370,sellPrice:4685},
{name:'Ak74 Green',className:'ak74_green',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:9370,sellPrice:4685},
{name:'AKM',className:'akm',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:10935,sellPrice:5468},
{name:'AUG',className:'aug',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:2980,sellPrice:1490},
{name:'Augshort',className:'augshort',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4580,sellPrice:2290},
{name:'Fal',className:'fal',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:9980,sellPrice:4990},
{name:'Famas',className:'famas',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4465,sellPrice:2232},
{name:'Sawedofffamas',className:'sawedofffamas',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4465,sellPrice:2232},
{name:'Aysa Antiairmissile',className:'aysa_antiairmissile',category:'Launchers And Ammo',traderSells:true,traderBuys:true,buyPrice:8750,sellPrice:4375},
{name:'Aysa Antiairquadlauncher',className:'aysa_antiairquadlauncher',category:'Launchers And Ammo',traderSells:false,traderBuys:true,sellPrice:11250},
{name:'Aysa Blackbox',className:'aysa_blackbox',category:'Launchers And Ammo',traderSells:false,traderBuys:true,sellPrice:6250},
{name:'Aysa Missilemag',className:'aysa_missilemag',category:'Launchers And Ammo',traderSells:true,traderBuys:true,buyPrice:6250,sellPrice:3125},
{name:'Aysa Seekerscope',className:'aysa_seekerscope',category:'Launchers And Ammo',traderSells:true,traderBuys:true,buyPrice:4250,sellPrice:2125},
{name:'Melees Annihil',className:'my_df_weapons_melees_annihil',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1688},
{name:'Melees Annihil2',className:'my_df_weapons_melees_annihil2',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1800},
{name:'Melees Chainsaw',className:'my_df_weapons_melees_chainsaw',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:3375},
{name:'Melees Creed',className:'my_df_weapons_melees_creed',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1312},
{name:'Melees Datathrowingknife',className:'my_df_weapons_melees_datathrowingknife',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:562},
{name:'Melees Datathrowingknife 2',className:'my_df_weapons_melees_datathrowingknife_2',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:675},
{name:'Melees Executor',className:'my_df_weapons_melees_executor',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1688},
{name:'Melees Executor2',className:'my_df_weapons_melees_executor2',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1800},
{name:'Melees Fairbairnsykes',className:'my_df_weapons_melees_fairbairnsykes',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:900},
{name:'Melees Karambit Raidenshogun',className:'my_df_weapons_melees_karambit_raidenshogun',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:900},
{name:'Melees Mercyknife',className:'my_df_weapons_melees_mercyknife',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1312},
{name:'Melees Polaris',className:'my_df_weapons_melees_polaris',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1312},
{name:'Melees Quenching',className:'my_df_weapons_melees_quenching',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1688},
{name:'Melees Shadowkiller',className:'my_df_weapons_melees_shadowkiller',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1688},
{name:'Melees Sharpblade',className:'my_df_weapons_melees_sharpblade',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:900},
{name:'Melees Silencefd',className:'my_df_weapons_melees_silencefd',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:900},
{name:'Melees Thievesea',className:'my_df_weapons_melees_thievesea',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1312},
{name:'DMR M14',className:'my_df_weapons_dmr_m14',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4375},
{name:'DMR Marlin',className:'my_df_weapons_dmr_marlin',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4000},
{name:'DMR Mini14',className:'my_df_weapons_dmr_mini14',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4125},
{name:'DMR Psg',className:'my_df_weapons_dmr_psg',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4750},
{name:'DMR SKS',className:'my_df_weapons_dmr_sks',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4125},
{name:'DMR SKS Morden',className:'my_df_weapons_dmr_sks_morden',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4125},
{name:'DMR Sp9',className:'my_df_weapons_dmr_sp9',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4625},
{name:'DMR SR-25',className:'my_df_weapons_dmr_sr25',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4750},
{name:'DMR SVD',className:'my_df_weapons_dmr_svd',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4625},
{name:'DMR Vss',className:'my_df_weapons_dmr_vss',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4500},
{name:'Launcher Law',className:'my_df_weapons_launcher_law',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4250},
{name:'Launcher Rpg7',className:'my_df_weapons_launcher_rpg7',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:5000},
{name:'LMG M249',className:'my_df_weapons_lmg_m249',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4250},
{name:'LMG M250',className:'my_df_weapons_lmg_m250',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:5000},
{name:'LMG Pkm',className:'my_df_weapons_lmg_pkm',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4750},
{name:'LMG Qjb201',className:'my_df_weapons_lmg_qjb201',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4500},
{name:'Pistols 93r',className:'my_df_weapons_pistols_93r',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:1250},
{name:'Pistols Coltpython',className:'my_df_weapons_pistols_coltpython',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:1000},
{name:'Pistols Deagle',className:'my_df_weapons_pistols_deagle',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:1375},
{name:'Pistols Glock17c',className:'my_df_weapons_pistols_glock17c',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:875},
{name:'Pistols Glock18c',className:'my_df_weapons_pistols_glock18c',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:1250},
{name:'Pistols M1911',className:'my_df_weapons_pistols_m1911',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:750},
{name:'Pistols Qsz92g',className:'my_df_weapons_pistols_qsz92g',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:750},
{name:'Rifles AK-12',className:'my_df_weapons_rifles_ak12',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3500},
{name:'Rifles AKM',className:'my_df_weapons_rifles_akm',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3500},
{name:'Rifles AKS-74U',className:'my_df_weapons_rifles_aks74u',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3000},
{name:'Rifles Ash12',className:'my_df_weapons_rifles_ash12',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4250},
{name:'Rifles Asval',className:'my_df_weapons_rifles_asval',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3875},
{name:'Rifles AUG',className:'my_df_weapons_rifles_aug',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2750},
{name:'Rifles Car15',className:'my_df_weapons_rifles_car15',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3000},
{name:'Rifles G3',className:'my_df_weapons_rifles_g3',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3750},
{name:'Rifles K416',className:'my_df_weapons_rifles_k416',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3375},
{name:'Rifles K437',className:'my_df_weapons_rifles_k437',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3250},
{name:'Rifles Kc17',className:'my_df_weapons_rifles_kc17',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3250},
{name:'Rifles M16A4',className:'my_df_weapons_rifles_m16a4',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3000},
{name:'Rifles M4A1',className:'my_df_weapons_rifles_m4a1',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3250},
{name:'Rifles M7',className:'my_df_weapons_rifles_m7',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4000},
{name:'Rifles Mcxlt',className:'my_df_weapons_rifles_mcxlt',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3500},
{name:'Rifles Mk47',className:'my_df_weapons_rifles_mk47',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3500},
{name:'Rifles Ptr32',className:'my_df_weapons_rifles_ptr32',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3500},
{name:'Rifles QBZ-191',className:'my_df_weapons_rifles_qbz191',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3250},
{name:'Rifles QBZ-95',className:'my_df_weapons_rifles_qbz95',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3125},
{name:'Rifles SCAR-H',className:'my_df_weapons_rifles_scarh',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4000},
{name:'Rifles SG553',className:'my_df_weapons_rifles_sg553',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3250},
{name:'Shotguns Citori725',className:'my_df_weapons_shotguns_citori725',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:1750},
{name:'Shotguns Fpss',className:'my_df_weapons_shotguns_fpss',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2125},
{name:'Shotguns Fpss Withmag',className:'my_df_weapons_shotguns_fpss_withmag',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2250},
{name:'Shotguns M1014',className:'my_df_weapons_shotguns_m1014',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2750},
{name:'Shotguns M870',className:'my_df_weapons_shotguns_m870',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:1875},
{name:'Shotguns Saiga12k',className:'my_df_weapons_shotguns_saiga12k',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:3000},
{name:'SMG Bison',className:'my_df_weapons_smg_bison',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2250},
{name:'SMG Mk4',className:'my_df_weapons_smg_mk4',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:1875},
{name:'SMG Mp5',className:'my_df_weapons_smg_mp5',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2000},
{name:'SMG Mp7',className:'my_df_weapons_smg_mp7',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2625},
{name:'SMG P90',className:'my_df_weapons_smg_p90',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2750},
{name:'SMG PP-19',className:'my_df_weapons_smg_pp19',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2125},
{name:'SMG Qcq171',className:'my_df_weapons_smg_qcq171',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2375},
{name:'SMG Smg45',className:'my_df_weapons_smg_smg45',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2500},
{name:'SMG Sr3m',className:'my_df_weapons_smg_sr3m',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2750},
{name:'SMG Uzi',className:'my_df_weapons_smg_uzi',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:1750},
{name:'SMG Vector',className:'my_df_weapons_smg_vector',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2625},
{name:'Snipers Awm',className:'my_df_weapons_snipers_awm',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:5000},
{name:'Snipers M700',className:'my_df_weapons_snipers_m700',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4250},
{name:'Snipers R93',className:'my_df_weapons_snipers_r93',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4750},
{name:'Snipers SV-98',className:'my_df_weapons_snipers_sv98',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4500},
{name:'Colt1911',className:'colt1911',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:5305,sellPrice:2652},
{name:'Cz75',className:'cz75',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2920,sellPrice:1460},
{name:'Deagle',className:'deagle',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2880,sellPrice:1440},
{name:'Deagle Gold',className:'deagle_gold',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2880,sellPrice:1440},
{name:'Derringer Black',className:'derringer_black',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3110,sellPrice:1555},
{name:'Derringer Grey',className:'derringer_grey',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3110,sellPrice:1555},
{name:'Derringer Pink',className:'derringer_pink',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3110,sellPrice:1555},
{name:'Engraved1911',className:'engraved1911',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:4975,sellPrice:2488},
{name:'Fnx45',className:'fnx45',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:7390,sellPrice:3695},
{name:'Glock19',className:'glock19',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3090,sellPrice:1545},
{name:'Longhorn',className:'longhorn',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3095,sellPrice:1548},
{name:'Magnum',className:'magnum',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2895,sellPrice:1448},
{name:'Makarovij70',className:'makarovij70',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3020,sellPrice:1510},
{name:'Mkii',className:'mkii',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3085,sellPrice:1542},
{name:'P1',className:'p1',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2995,sellPrice:1498},
{name:'Sawedoffmagnum',className:'sawedoffmagnum',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2895,sellPrice:1448},
{name:'Cz527',className:'cz527',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2920,sellPrice:1460},
{name:'Cz527 Black',className:'cz527_black',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2920,sellPrice:1460},
{name:'Cz527 Camo',className:'cz527_camo',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2920,sellPrice:1460},
{name:'Cz527 Green',className:'cz527_green',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2920,sellPrice:1460},
{name:'Cz550',className:'cz550',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:5715,sellPrice:2858},
{name:'Izh18',className:'izh18',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3080,sellPrice:1540},
{name:'M14',className:'m14',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:10805,sellPrice:5402},
{name:'Mosin9130',className:'mosin9130',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Mosin9130 Black',className:'mosin9130_black',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Mosin9130 Camo',className:'mosin9130_camo',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Mosin9130 Green',className:'mosin9130_green',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Repeater',className:'repeater',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3095,sellPrice:1548},
{name:'Ruger1022',className:'ruger1022',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2945,sellPrice:1472},
{name:'Sawedoffizh18',className:'sawedoffizh18',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3080,sellPrice:1540},
{name:'Sawedoffmosin9130',className:'sawedoffmosin9130',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Sawedoffmosin9130 Black',className:'sawedoffmosin9130_black',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Sawedoffmosin9130 Camo',className:'sawedoffmosin9130_camo',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Sawedoffmosin9130 Green',className:'sawedoffmosin9130_green',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'SKS',className:'sks',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2995,sellPrice:1498},
{name:'SKS Black',className:'sks_black',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2995,sellPrice:1498},
{name:'SKS Green',className:'sks_green',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2995,sellPrice:1498},
{name:'Ssg82',className:'ssg82',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:6095,sellPrice:3048},
{name:'Winchester70',className:'winchester70',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:5900,sellPrice:2950},
{name:'Winchester70 Black',className:'winchester70_black',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:5900,sellPrice:2950},
{name:'Winchester70 Green',className:'winchester70_green',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:5900,sellPrice:2950},
{name:'Izh18shotgun',className:'izh18shotgun',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:1915,sellPrice:958},
{name:'Izh43shotgun',className:'izh43shotgun',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:1905,sellPrice:952},
{name:'Mp133shotgun',className:'mp133shotgun',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:5535,sellPrice:2768},
{name:'R12',className:'r12',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:5455,sellPrice:2728},
{name:'Saiga',className:'saiga',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:4220,sellPrice:2110},
{name:'Sawedoffizh18shotgun',className:'sawedoffizh18shotgun',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:1915,sellPrice:958},
{name:'Sawedoffizh43shotgun',className:'sawedoffizh43shotgun',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:1905,sellPrice:952},
{name:'Asval',className:'asval',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:7005,sellPrice:3502},
{name:'B95',className:'b95',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4380,sellPrice:2190},
{name:'Sawedoffb95',className:'sawedoffb95',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4380,sellPrice:2190},
{name:'Scout',className:'scout',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4040,sellPrice:2020},
{name:'Scout Chernarus',className:'scout_chernarus',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4040,sellPrice:2020},
{name:'Scout Livonia',className:'scout_livonia',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4040,sellPrice:2020},
{name:'SV-98',className:'sv98',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4845,sellPrice:2422},
{name:'SVD',className:'svd',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:5000,sellPrice:2500},
{name:'SVD Wooden',className:'svd_wooden',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:5000,sellPrice:2500},
{name:'Vikhr',className:'vikhr',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:6530,sellPrice:3265},
{name:'Vss',className:'vss',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:6400,sellPrice:3200},
{name:'AKS-74U',className:'aks74u',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:8745,sellPrice:4372},
{name:'Cz61',className:'cz61',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:4795,sellPrice:2398},
{name:'Mp5k',className:'mp5k',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:5395,sellPrice:2698},
{name:'Pm73rak',className:'pm73rak',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:6530,sellPrice:3265},
{name:'PP-19',className:'pp19',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:6910,sellPrice:3455},
{name:'Ump45',className:'ump45',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:6410,sellPrice:3205},
{name:'Cleaver',className:'cleaver',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:958,sellPrice:479},
{name:'Combatknife',className:'combatknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1058,sellPrice:529},
{name:'Crudemachete',className:'crudemachete',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1008,sellPrice:504},
{name:'Fangeknife',className:'fangeknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:974,sellPrice:487},
{name:'Huntingknife',className:'huntingknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:992,sellPrice:496},
{name:'Kitchenknife',className:'kitchenknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:922,sellPrice:461},
{name:'Kukriknife',className:'kukriknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1074,sellPrice:537},
{name:'Machete',className:'machete',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1024,sellPrice:512},
{name:'Orientalmachete',className:'orientalmachete',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1042,sellPrice:521},
{name:'Steakknife',className:'steakknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:936,sellPrice:468},
{name:'Sword',className:'sword',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1092,sellPrice:546},
{name:'Barbedbaseballbat',className:'barbedbaseballbat',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:488,sellPrice:244},
{name:'Baseballbat',className:'baseballbat',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:488,sellPrice:244},
{name:'Brassknuckles Dull',className:'brassknuckles_dull',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:428,sellPrice:214},
{name:'Brassknuckles Shiny',className:'brassknuckles_shiny',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:428,sellPrice:214},
{name:'Broom',className:'broom',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:293,sellPrice:146},
{name:'Broom Birch',className:'broom_birch',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:293,sellPrice:146},
{name:'Iceaxe',className:'iceaxe',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:1313,sellPrice:656},
{name:'Lugwrench',className:'lugwrench',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:728,sellPrice:364},
{name:'Mace',className:'mace',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:713,sellPrice:356},
{name:'Meattenderizer',className:'meattenderizer',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:514,sellPrice:257},
{name:'Nailedbaseballbat',className:'nailedbaseballbat',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:488,sellPrice:244},
{name:'Pipe',className:'pipe',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:473,sellPrice:236},
{name:'Pipewrench',className:'pipewrench',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:784,sellPrice:392},
{name:'Spearbone',className:'spearbone',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:619,sellPrice:310},
{name:'Spearstone',className:'spearstone',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:581,sellPrice:290},
{name:'Stunbaton',className:'stunbaton',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:353,sellPrice:176}
]};
