window.traderCatalogue={traderName:'Indar',currency:'USD',items:[
{name:'Ak101',className:'ak101',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4225,sellPrice:2112},
{name:'Ak101 Black',className:'ak101_black',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4225,sellPrice:2112},
{name:'Ak101 Green',className:'ak101_green',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4225,sellPrice:2112},
{name:'Ak74',className:'ak74',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:9370,sellPrice:4685},
{name:'Ak74 Black',className:'ak74_black',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:9370,sellPrice:4685},
{name:'Ak74 Green',className:'ak74_green',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:9370,sellPrice:4685},
{name:'AKM',className:'akm',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:10935,sellPrice:5468},
{name:'AUG',className:'aug',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:2980,sellPrice:1490},
{name:'Augshort',className:'augshort',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4580,sellPrice:2290},
{name:'Fal',className:'fal',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:9980,sellPrice:4990},
{name:'Famas',className:'famas',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4465,sellPrice:2232},
{name:'M16 A2',className:'M16A2',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:3500,sellPrice:1750},
{name:'M4 A1',className:'M4A1',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:7000,sellPrice:3500},
{name:'M4 A1 Black',className:'M4A1_Black',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:7000,sellPrice:3500},
{name:'M4 A1 Green',className:'M4A1_Green',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:7000,sellPrice:3500},
{name:'Sawedofffamas',className:'sawedofffamas',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:4465,sellPrice:2232},
{name:'SCAR-H',className:'SCARH',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:8000,sellPrice:4000},
{name:'SCAR-H Black',className:'SCARH_Black',category:'Assault Rifles',traderSells:true,traderBuys:true,buyPrice:8000,sellPrice:4000},
{name:'AK Folding Bttstck Black',className:'AK_FoldingBttstck_Black',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'AK Folding Bttstck Green',className:'AK_FoldingBttstck_Green',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'AK Foldingbttstck',className:'ak_foldingbttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'AK Plastic Bttstck Black',className:'AK_PlasticBttstck_Black',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'AK Plastic Bttstck Green',className:'AK_PlasticBttstck_Green',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'AK Plasticbttstck',className:'ak_plasticbttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'AK Wood Bttstck Black',className:'AK_WoodBttstck_Black',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'AK Wood Bttstck Camo',className:'AK_WoodBttstck_Camo',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'AK Woodbttstck',className:'ak_woodbttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Ak74 Wood Bttstck Black',className:'AK74_WoodBttstck_Black',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Ak74 Woodbttstck',className:'ak74_woodbttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'AKS-74U Bttstck',className:'aks74u_bttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'AKS-74U Bttstck Black',className:'aks74u_bttstck_black',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Fal Foldingbttstck',className:'fal_foldingbttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Fal Oebttstck',className:'fal_oebttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Ghillieatt Mossy',className:'ghillieatt_mossy',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Ghillieatt Tan',className:'ghillieatt_tan',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Ghillieatt Winter',className:'ghillieatt_winter',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Ghillieatt Woodland',className:'ghillieatt_woodland',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'M4 Cqbbttstck',className:'m4_cqbbttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'M4 Mpbttstck',className:'m4_mpbttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'M4 Oebttstck',className:'m4_oebttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Mp5k Stockbttstck',className:'mp5k_stockbttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'PP-19 Bttstck',className:'pp19_bttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Saiga Bttstck',className:'saiga_bttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Scar Precision Bttstck',className:'SCAR_PrecisionBttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Scar Precision Bttstck Black',className:'SCAR_PrecisionBttstck_Black',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Scar Stock Bttstck',className:'SCAR_StockBttstck',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'Scar Stock Bttstck Black',className:'SCAR_StockBttstck_Black',category:'Buttstocks',traderSells:false,traderBuys:false},
{name:'DMR M14',className:'My_DF_Weapons_DMR_M14',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4375},
{name:'DMR Marlin',className:'My_DF_Weapons_DMR_Marlin',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4000},
{name:'DMR Mini14',className:'My_DF_Weapons_DMR_Mini14',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4125},
{name:'DMR Psg',className:'My_DF_Weapons_DMR_PSG',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4750},
{name:'DMR SKS',className:'My_DF_Weapons_DMR_SKS',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4125},
{name:'DMR SKS Morden',className:'my_df_weapons_dmr_sks_morden',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4125},
{name:'DMR Sp9',className:'My_DF_Weapons_DMR_SP9',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4625},
{name:'DMR SR-25',className:'My_DF_Weapons_DMR_SR25',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4750},
{name:'DMR Svch',className:'My_DF_Weapons_DMR_SVCH',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4250},
{name:'DMR SVD',className:'My_DF_Weapons_DMR_SVD',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4625},
{name:'DMR Vss',className:'My_DF_Weapons_DMR_VSS',category:'DF Weapons DMR',traderSells:false,traderBuys:true,sellPrice:4500},
{name:'Pistols 93 R',className:'My_DF_Weapons_Pistols_93R',category:'DF Weapons Pistol',traderSells:false,traderBuys:true,sellPrice:1250},
{name:'Pistols Colt Python',className:'My_DF_Weapons_Pistols_ColtPython',category:'DF Weapons Pistol',traderSells:false,traderBuys:true,sellPrice:1000},
{name:'Pistols Deagle',className:'My_DF_Weapons_Pistols_Deagle',category:'DF Weapons Pistol',traderSells:false,traderBuys:true,sellPrice:1375},
{name:'Pistols Glock17 C',className:'My_DF_Weapons_Pistols_Glock17C',category:'DF Weapons Pistol',traderSells:false,traderBuys:true,sellPrice:875},
{name:'Pistols Glock18 C',className:'My_DF_Weapons_Pistols_Glock18C',category:'DF Weapons Pistol',traderSells:false,traderBuys:true,sellPrice:1250},
{name:'Pistols M1911',className:'My_DF_Weapons_Pistols_M1911',category:'DF Weapons Pistol',traderSells:false,traderBuys:true,sellPrice:750},
{name:'Pistols Qsz92 G',className:'My_DF_Weapons_Pistols_QSZ92G',category:'DF Weapons Pistol',traderSells:false,traderBuys:true,sellPrice:750},
{name:'Rifles AK-12',className:'My_DF_Weapons_Rifles_AK12',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3500},
{name:'Rifles AKM',className:'My_DF_Weapons_Rifles_AKM',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3500},
{name:'Rifles Aks74 U',className:'My_DF_Weapons_Rifles_AKS74U',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3000},
{name:'Rifles Ar57',className:'My_DF_Weapons_Rifles_AR57',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:2125},
{name:'Rifles Ash12',className:'My_DF_Weapons_Rifles_Ash12',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:4250},
{name:'Rifles Asval',className:'My_DF_Weapons_Rifles_ASVAL',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3875},
{name:'Rifles AUG',className:'My_DF_Weapons_Rifles_AUG',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:2750},
{name:'Rifles Car15',className:'My_DF_Weapons_Rifles_CAR15',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3000},
{name:'Rifles G3',className:'My_DF_Weapons_Rifles_G3',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3750},
{name:'Rifles K416',className:'My_DF_Weapons_Rifles_K416',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3375},
{name:'Rifles K437',className:'My_DF_Weapons_Rifles_K437',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3250},
{name:'Rifles Kc17',className:'My_DF_Weapons_Rifles_KC17',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3250},
{name:'Rifles M16 A4',className:'My_DF_Weapons_Rifles_M16A4',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3000},
{name:'Rifles M4 A1',className:'My_DF_Weapons_Rifles_M4A1',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3250},
{name:'Rifles M7',className:'My_DF_Weapons_Rifles_M7',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3500},
{name:'Rifles Mcxlt',className:'My_DF_Weapons_Rifles_MCXLT',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:1750},
{name:'Rifles Mk47',className:'My_DF_Weapons_Rifles_MK47',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3500},
{name:'Rifles Ptr32',className:'My_DF_Weapons_Rifles_PTR32',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3500},
{name:'Rifles QBZ-191',className:'My_DF_Weapons_Rifles_QBZ191',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3250},
{name:'Rifles QBZ-95',className:'My_DF_Weapons_Rifles_QBZ95',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3125},
{name:'Rifles Rm277',className:'My_DF_Weapons_Rifles_RM277',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:2250},
{name:'Rifles SCAR-H',className:'My_DF_Weapons_Rifles_SCARH',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:4000},
{name:'Rifles SG553',className:'My_DF_Weapons_Rifles_SG553',category:'DF Weapons Rifle',traderSells:false,traderBuys:true,sellPrice:3250},
{name:'Shotguns Citori725',className:'My_DF_Weapons_Shotguns_Citori725',category:'DF Weapons Shotgun',traderSells:false,traderBuys:true,sellPrice:1750},
{name:'Shotguns Fpss',className:'My_DF_Weapons_Shotguns_FPSS',category:'DF Weapons Shotgun',traderSells:false,traderBuys:true,sellPrice:2250},
{name:'Shotguns M1014',className:'My_DF_Weapons_Shotguns_M1014',category:'DF Weapons Shotgun',traderSells:false,traderBuys:true,sellPrice:2750},
{name:'Shotguns M870',className:'My_DF_Weapons_Shotguns_M870',category:'DF Weapons Shotgun',traderSells:false,traderBuys:true,sellPrice:1875},
{name:'Shotguns Saiga12 K',className:'My_DF_Weapons_Shotguns_Saiga12K',category:'DF Weapons Shotgun',traderSells:false,traderBuys:true,sellPrice:3000},
{name:'SMG Bison',className:'My_DF_Weapons_SMG_Bison',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:2250},
{name:'SMG Mk4',className:'My_DF_Weapons_SMG_MK4',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:1875},
{name:'SMG Mp5',className:'My_DF_Weapons_SMG_MP5',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:2000},
{name:'SMG Mp7',className:'My_DF_Weapons_SMG_MP7',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:2625},
{name:'SMG P90',className:'My_DF_Weapons_SMG_P90',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:2750},
{name:'SMG PP-19',className:'My_DF_Weapons_SMG_PP19',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:2125},
{name:'SMG Qcq171',className:'My_DF_Weapons_SMG_QCQ171',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:2375},
{name:'SMG Smg45',className:'My_DF_Weapons_SMG_SMG45',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:2500},
{name:'SMG Sr3 M',className:'My_DF_Weapons_SMG_SR3M',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:2750},
{name:'SMG Uzi',className:'My_DF_Weapons_SMG_Uzi',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:1750},
{name:'SMG Vector',className:'My_DF_Weapons_SMG_Vector',category:'DF Weapons SMG',traderSells:false,traderBuys:true,sellPrice:2625},
{name:'Snipers Awm',className:'My_DF_Weapons_Snipers_AWM',category:'DF Weapons Sniper',traderSells:false,traderBuys:true,sellPrice:5000},
{name:'Snipers M700',className:'My_DF_Weapons_Snipers_M700',category:'DF Weapons Sniper',traderSells:false,traderBuys:true,sellPrice:4250},
{name:'Snipers M82',className:'My_DF_Weapons_Snipers_M82',category:'DF Weapons Sniper',traderSells:false,traderBuys:true,sellPrice:5000},
{name:'Snipers R93',className:'My_DF_Weapons_Snipers_R93',category:'DF Weapons Sniper',traderSells:false,traderBuys:true,sellPrice:4750},
{name:'Snipers SV-98',className:'My_DF_Weapons_Snipers_SV98',category:'DF Weapons Sniper',traderSells:false,traderBuys:true,sellPrice:4500},
{name:'AK Plastichndgrd',className:'ak_plastichndgrd',category:'Handguards',traderSells:false,traderBuys:false},
{name:'AK Rail Hndgrd Black',className:'AK_RailHndgrd_Black',category:'Handguards',traderSells:false,traderBuys:false},
{name:'AK Rail Hndgrd Green',className:'AK_RailHndgrd_Green',category:'Handguards',traderSells:false,traderBuys:false},
{name:'AK Railhndgrd',className:'ak_railhndgrd',category:'Handguards',traderSells:false,traderBuys:false},
{name:'AK Wood Hndgrd Black',className:'AK_WoodHndgrd_Black',category:'Handguards',traderSells:false,traderBuys:false},
{name:'AK Wood Hndgrd Camo',className:'AK_WoodHndgrd_Camo',category:'Handguards',traderSells:false,traderBuys:false},
{name:'AK Woodhndgrd',className:'ak_woodhndgrd',category:'Handguards',traderSells:false,traderBuys:false},
{name:'Ak74 Hndgrd',className:'ak74_hndgrd',category:'Handguards',traderSells:false,traderBuys:false},
{name:'Ak74 Hndgrd Camo',className:'AK74_Hndgrd_Camo',category:'Handguards',traderSells:false,traderBuys:false},
{name:'M4 Mphndgrd',className:'m4_mphndgrd',category:'Handguards',traderSells:false,traderBuys:false},
{name:'M4 Plastic Hndgrd Green',className:'M4_PlasticHndgrd_Green',category:'Handguards',traderSells:false,traderBuys:false},
{name:'M4 Plastichndgrd',className:'m4_plastichndgrd',category:'Handguards',traderSells:false,traderBuys:false},
{name:'M4 Rishndgrd',className:'m4_rishndgrd',category:'Handguards',traderSells:false,traderBuys:false},
{name:'M4 Rishndgrd Black',className:'M4_RISHndgrd_Black',category:'Handguards',traderSells:false,traderBuys:false},
{name:'M4 Rishndgrd Green',className:'M4_RISHndgrd_Green',category:'Handguards',traderSells:false,traderBuys:false},
{name:'Mp5 Plastichndgrd',className:'mp5_plastichndgrd',category:'Handguards',traderSells:false,traderBuys:false},
{name:'Mp5 Railhndgrd',className:'mp5_railhndgrd',category:'Handguards',traderSells:false,traderBuys:false},
{name:'Aysa Antiairmissile',className:'aysa_antiairmissile',category:'Launchers And Ammo',traderSells:true,traderBuys:true,buyPrice:8750,sellPrice:4375},
{name:'Aysa Antiairquadlauncher',className:'aysa_antiairquadlauncher',category:'Launchers And Ammo',traderSells:false,traderBuys:true,sellPrice:11250},
{name:'Aysa Blackbox',className:'aysa_blackbox',category:'Launchers And Ammo',traderSells:false,traderBuys:true,sellPrice:6250},
{name:'Aysa Missilemag',className:'aysa_missilemag',category:'Launchers And Ammo',traderSells:true,traderBuys:true,buyPrice:6250,sellPrice:3125},
{name:'Aysa Seekerscope',className:'aysa_seekerscope',category:'Launchers And Ammo',traderSells:true,traderBuys:true,buyPrice:4250,sellPrice:2125},
{name:'Mag 1911 7rnd',className:'mag_1911_7rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Ak101 30rnd',className:'mag_ak101_30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Ak74 30rnd',className:'mag_ak74_30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Ak74 45rnd',className:'mag_ak74_45rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag AKM 30rnd',className:'mag_akm_30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag AKM Drum75rnd',className:'mag_akm_drum75rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag AKM Palm30 Rnd Black',className:'Mag_AKM_Palm30Rnd_Black',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag AKM Palm30 Rnd Green',className:'Mag_AKM_Palm30Rnd_Green',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag AKM Palm30rnd',className:'mag_akm_palm30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag AUG 30rnd',className:'mag_aug_30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Cmag 10 Rnd Black',className:'Mag_CMAG_10Rnd_Black',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Cmag 10rnd',className:'mag_cmag_10rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Cmag 20rnd',className:'mag_cmag_20rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Cmag 30rnd',className:'mag_cmag_30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Cmag 40rnd',className:'mag_cmag_40rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Cz527 5rnd',className:'mag_cz527_5rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Cz550 10rnd',className:'mag_cz550_10rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Cz61 20rnd',className:'mag_cz61_20rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Cz75 15rnd',className:'mag_cz75_15rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Deagle 9rnd',className:'mag_deagle_9rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Fal 20rnd',className:'mag_fal_20rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Famas 25rnd',className:'mag_famas_25rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Fnx45 15rnd',className:'mag_fnx45_15rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Glock 15rnd',className:'mag_glock_15rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Ij70 8rnd',className:'mag_ij70_8rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag M14 10rnd',className:'mag_m14_10rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag M14 20rnd',className:'mag_m14_20rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Mkii 10rnd',className:'mag_mkii_10rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Mp5 15rnd',className:'mag_mp5_15rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Mp5 30rnd',className:'mag_mp5_30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag P1 8rnd',className:'mag_p1_8rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Pm73 15rnd',className:'mag_pm73_15rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Pm73 25rnd',className:'mag_pm73_25rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag PP-19 64rnd',className:'mag_pp19_64rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Ruger1022 15rnd',className:'mag_ruger1022_15rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Ruger1022 30rnd',className:'mag_ruger1022_30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Saiga 5rnd',className:'mag_saiga_5rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Saiga 8rnd',className:'mag_saiga_8rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Saiga Drum20rnd',className:'mag_saiga_drum20rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag SCAR-H 20 Rnd',className:'Mag_SCARH_20Rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag SCAR-H 20 Rnd Black',className:'Mag_SCARH_20Rnd_Black',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Scout 5rnd',className:'mag_scout_5rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Ssg82 5rnd',className:'mag_ssg82_5rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Stanag 30rnd',className:'mag_stanag_30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Stanag 60rnd',className:'mag_stanag_60rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Stanagcoupled 30rnd',className:'mag_stanagcoupled_30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag SV-98 10rnd',className:'mag_sv98_10rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag SVD 10rnd',className:'mag_svd_10rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Ump 25rnd',className:'mag_ump_25rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Val 20rnd',className:'mag_val_20rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Vikhr 30rnd',className:'mag_vikhr_30rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Mag Vss 10rnd',className:'mag_vss_10rnd',category:'Magazines',traderSells:false,traderBuys:false},
{name:'Melees Annihil',className:'my_df_weapons_melees_annihil',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1688},
{name:'Melees Annihil2',className:'my_df_weapons_melees_annihil2',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1800},
{name:'Melees Chainsaw',className:'my_df_weapons_melees_chainsaw',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:3375},
{name:'Melees Creed',className:'my_df_weapons_melees_creed',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1312},
{name:'Melees Datathrowingknife',className:'my_df_weapons_melees_datathrowingknife',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:562},
{name:'Melees Datathrowingknife 2',className:'my_df_weapons_melees_datathrowingknife_2',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:675},
{name:'Melees Executor',className:'my_df_weapons_melees_executor',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1688},
{name:'Melees Executor2',className:'my_df_weapons_melees_executor2',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1800},
{name:'Melees Fairbairnsykes',className:'my_df_weapons_melees_fairbairnsykes',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:900},
{name:'Melees Karambit Raidenshogun',className:'my_df_weapons_melees_karambit_raidenshogun',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:900},
{name:'Melees Mercyknife',className:'my_df_weapons_melees_mercyknife',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1312},
{name:'Melees Polaris',className:'my_df_weapons_melees_polaris',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1312},
{name:'Melees Quenching',className:'my_df_weapons_melees_quenching',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1688},
{name:'Melees Shadowkiller',className:'my_df_weapons_melees_shadowkiller',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1688},
{name:'Melees Sharpblade',className:'my_df_weapons_melees_sharpblade',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:900},
{name:'Melees Silencefd',className:'my_df_weapons_melees_silencefd',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:900},
{name:'Melees Thievesea',className:'my_df_weapons_melees_thievesea',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1312},
{name:'Colt1911',className:'colt1911',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:5305,sellPrice:2652},
{name:'Cz75',className:'cz75',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2920,sellPrice:1460},
{name:'Deagle',className:'deagle',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2880,sellPrice:1440},
{name:'Deagle Gold',className:'deagle_gold',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2880,sellPrice:1440},
{name:'Derringer Black',className:'derringer_black',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3110,sellPrice:1555},
{name:'Derringer Grey',className:'derringer_grey',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3110,sellPrice:1555},
{name:'Derringer Pink',className:'derringer_pink',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3110,sellPrice:1555},
{name:'Engraved1911',className:'engraved1911',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:4975,sellPrice:2488},
{name:'Flaregun',className:'Flaregun',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2500,sellPrice:1250},
{name:'Fnx45',className:'fnx45',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:7390,sellPrice:3695},
{name:'Glock19',className:'glock19',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3090,sellPrice:1545},
{name:'Longhorn',className:'longhorn',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3095,sellPrice:1548},
{name:'Magnum',className:'magnum',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2895,sellPrice:1448},
{name:'Makarovij70',className:'makarovij70',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3020,sellPrice:1510},
{name:'Mkii',className:'mkii',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:3085,sellPrice:1542},
{name:'P1',className:'p1',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2995,sellPrice:1498},
{name:'Sawedoffmagnum',className:'sawedoffmagnum',category:'Pistols',traderSells:true,traderBuys:true,buyPrice:2895,sellPrice:1448},
{name:'Cz527',className:'cz527',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2920,sellPrice:1460},
{name:'Cz527 Black',className:'cz527_black',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2920,sellPrice:1460},
{name:'Cz527 Camo',className:'cz527_camo',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2920,sellPrice:1460},
{name:'Cz527 Green',className:'cz527_green',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2920,sellPrice:1460},
{name:'Cz550',className:'cz550',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:5715,sellPrice:2858},
{name:'Izh18',className:'izh18',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3080,sellPrice:1540},
{name:'M14',className:'m14',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:10805,sellPrice:5402},
{name:'Mosin9130',className:'mosin9130',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Mosin9130 Black',className:'mosin9130_black',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Mosin9130 Camo',className:'mosin9130_camo',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Mosin9130 Green',className:'mosin9130_green',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Repeater',className:'repeater',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3095,sellPrice:1548},
{name:'Ruger1022',className:'ruger1022',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2945,sellPrice:1472},
{name:'Sawedoffizh18',className:'sawedoffizh18',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3080,sellPrice:1540},
{name:'Sawedoffmosin9130',className:'sawedoffmosin9130',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Sawedoffmosin9130 Black',className:'sawedoffmosin9130_black',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Sawedoffmosin9130 Camo',className:'sawedoffmosin9130_camo',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'Sawedoffmosin9130 Green',className:'sawedoffmosin9130_green',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:3075,sellPrice:1538},
{name:'SKS',className:'sks',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2995,sellPrice:1498},
{name:'SKS Black',className:'sks_black',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2995,sellPrice:1498},
{name:'SKS Green',className:'sks_green',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:2995,sellPrice:1498},
{name:'Ssg82',className:'ssg82',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:6095,sellPrice:3048},
{name:'Winchester70',className:'winchester70',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:5900,sellPrice:2950},
{name:'Winchester70 Black',className:'winchester70_black',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:5900,sellPrice:2950},
{name:'Winchester70 Green',className:'winchester70_green',category:'Rifles',traderSells:true,traderBuys:true,buyPrice:5900,sellPrice:2950},
{name:'Izh18shotgun',className:'izh18shotgun',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:1915,sellPrice:958},
{name:'Izh43shotgun',className:'izh43shotgun',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:1905,sellPrice:952},
{name:'Mp133shotgun',className:'mp133shotgun',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:5535,sellPrice:2768},
{name:'R12',className:'r12',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:5455,sellPrice:2728},
{name:'Saiga',className:'saiga',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:4220,sellPrice:2110},
{name:'Sawedoffizh18shotgun',className:'sawedoffizh18shotgun',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:1915,sellPrice:958},
{name:'Sawedoffizh43shotgun',className:'sawedoffizh43shotgun',category:'Shotguns',traderSells:true,traderBuys:true,buyPrice:1905,sellPrice:952},
{name:'Asval',className:'asval',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:7005,sellPrice:3502},
{name:'B95',className:'b95',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4380,sellPrice:2190},
{name:'Sawedoffb95',className:'sawedoffb95',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4380,sellPrice:2190},
{name:'Scout',className:'scout',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4040,sellPrice:2020},
{name:'Scout Chernarus',className:'scout_chernarus',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4040,sellPrice:2020},
{name:'Scout Livonia',className:'scout_livonia',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4040,sellPrice:2020},
{name:'SV-98',className:'sv98',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:4845,sellPrice:2422},
{name:'SVD',className:'svd',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:5000,sellPrice:2500},
{name:'SVD Wooden',className:'svd_wooden',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:5000,sellPrice:2500},
{name:'Vikhr',className:'vikhr',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:6530,sellPrice:3265},
{name:'Vss',className:'vss',category:'Sniper Rifles',traderSells:true,traderBuys:true,buyPrice:6400,sellPrice:3200},
{name:'AKS-74U',className:'aks74u',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:8745,sellPrice:4372},
{name:'Aks74 U Black',className:'AKS74U_Black',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:8745,sellPrice:4372},
{name:'Aks74 U Green',className:'AKS74U_Green',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:8745,sellPrice:4372},
{name:'Cz61',className:'cz61',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:4795,sellPrice:2398},
{name:'Mp5k',className:'mp5k',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:5395,sellPrice:2698},
{name:'Pm73rak',className:'pm73rak',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:6530,sellPrice:3265},
{name:'PP-19',className:'pp19',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:6910,sellPrice:3455},
{name:'Ump45',className:'ump45',category:'Submachine Guns',traderSells:true,traderBuys:true,buyPrice:6410,sellPrice:3205},
{name:'Cleaver',className:'cleaver',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:958,sellPrice:479},
{name:'Combatknife',className:'combatknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1058,sellPrice:529},
{name:'Crudemachete',className:'crudemachete',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1008,sellPrice:504},
{name:'Fangeknife',className:'fangeknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:974,sellPrice:487},
{name:'Huntingknife',className:'huntingknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:992,sellPrice:496},
{name:'Kitchenknife',className:'kitchenknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:922,sellPrice:461},
{name:'Kukriknife',className:'kukriknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1074,sellPrice:537},
{name:'Machete',className:'machete',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1024,sellPrice:512},
{name:'Orientalmachete',className:'orientalmachete',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1042,sellPrice:521},
{name:'Steakknife',className:'steakknife',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:936,sellPrice:468},
{name:'Sword',className:'sword',category:'Vanilla Knives',traderSells:true,traderBuys:true,buyPrice:1092,sellPrice:546},
{name:'Barbedbaseballbat',className:'barbedbaseballbat',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:488,sellPrice:244},
{name:'Baseballbat',className:'baseballbat',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:488,sellPrice:244},
{name:'Brass Knuckles Men At Arms',className:'BrassKnuckles_MenAtArms',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:428,sellPrice:214},
{name:'Brassknuckles Dull',className:'brassknuckles_dull',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:428,sellPrice:214},
{name:'Brassknuckles Shiny',className:'brassknuckles_shiny',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:428,sellPrice:214},
{name:'Broom',className:'broom',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:293,sellPrice:146},
{name:'Broom Birch',className:'broom_birch',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:293,sellPrice:146},
{name:'Iceaxe',className:'iceaxe',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:1313,sellPrice:656},
{name:'Lugwrench',className:'lugwrench',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:728,sellPrice:364},
{name:'Mace',className:'mace',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:713,sellPrice:356},
{name:'Meattenderizer',className:'meattenderizer',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:514,sellPrice:257},
{name:'Nailedbaseballbat',className:'nailedbaseballbat',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:488,sellPrice:244},
{name:'Pipe',className:'pipe',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:473,sellPrice:236},
{name:'Pipewrench',className:'pipewrench',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:784,sellPrice:392},
{name:'Spearbone',className:'spearbone',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:619,sellPrice:310},
{name:'Spearstone',className:'spearstone',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:581,sellPrice:290},
{name:'Stunbaton',className:'stunbaton',category:'Vanilla Melee Weapons',traderSells:true,traderBuys:true,buyPrice:353,sellPrice:176}
]};
