window.traderCatalogue={traderName:'Indar',currency:'USD',items:[
{name:'Melees Annihil',className:'my_df_weapons_melees_annihil',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:2531},
{name:'Melees Annihil2',className:'my_df_weapons_melees_annihil2',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:2700},
{name:'Melees Chainsaw',className:'my_df_weapons_melees_chainsaw',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:5062},
{name:'Melees Creed',className:'my_df_weapons_melees_creed',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1969},
{name:'Melees Datathrowingknife',className:'my_df_weapons_melees_datathrowingknife',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:844},
{name:'Melees Datathrowingknife 2',className:'my_df_weapons_melees_datathrowingknife_2',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1012},
{name:'Melees Executor',className:'my_df_weapons_melees_executor',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:2531},
{name:'Melees Executor2',className:'my_df_weapons_melees_executor2',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:2700},
{name:'Melees Fairbairnsykes',className:'my_df_weapons_melees_fairbairnsykes',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1350},
{name:'Melees Karambit Raidenshogun',className:'my_df_weapons_melees_karambit_raidenshogun',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1350},
{name:'Melees Mercyknife',className:'my_df_weapons_melees_mercyknife',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1969},
{name:'Melees Polaris',className:'my_df_weapons_melees_polaris',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1969},
{name:'Melees Quenching',className:'my_df_weapons_melees_quenching',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:2531},
{name:'Melees Shadowkiller',className:'my_df_weapons_melees_shadowkiller',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:2531},
{name:'Melees Sharpblade',className:'my_df_weapons_melees_sharpblade',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1350},
{name:'Melees Silencefd',className:'my_df_weapons_melees_silencefd',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1350},
{name:'Melees Thievesea',className:'my_df_weapons_melees_thievesea',category:'My DF Melee Weapons',traderSells:false,traderBuys:true,sellPrice:1969},
{name:'DMR M14',className:'My_DF_Weapons_DMR_M14',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:8750,sellPrice:6562},
{name:'DMR Marlin',className:'My_DF_Weapons_DMR_Marlin',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:8000,sellPrice:6000},
{name:'DMR Mini14',className:'My_DF_Weapons_DMR_Mini14',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:8250,sellPrice:6188},
{name:'DMR Psg',className:'My_DF_Weapons_DMR_PSG',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:9500,sellPrice:7125},
{name:'DMR SKS',className:'My_DF_Weapons_DMR_SKS',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:8250,sellPrice:6188},
{name:'DMR SKS Morden',className:'My_DF_Weapons_DMR_SKS_Morden',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:8250,sellPrice:6188},
{name:'DMR Sp9',className:'My_DF_Weapons_DMR_SP9',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:9250,sellPrice:6938},
{name:'DMR SR-25',className:'My_DF_Weapons_DMR_SR25',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:9500,sellPrice:7125},
{name:'DMR SVD',className:'My_DF_Weapons_DMR_SVD',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:9250,sellPrice:6938},
{name:'DMR Vss',className:'my_df_weapons_dmr_vss',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:6750},
{name:'Launcher Law',className:'my_df_weapons_launcher_law',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:6375},
{name:'Launcher Rpg7',className:'my_df_weapons_launcher_rpg7',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:7500},
{name:'LMG M249',className:'my_df_weapons_lmg_m249',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:6375},
{name:'LMG M250',className:'my_df_weapons_lmg_m250',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:7500},
{name:'LMG Pkm',className:'my_df_weapons_lmg_pkm',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:7125},
{name:'LMG Qjb201',className:'my_df_weapons_lmg_qjb201',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:6750},
{name:'Pistols 93 R',className:'My_DF_Weapons_Pistols_93R',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:2500,sellPrice:1875},
{name:'Pistols Colt Python',className:'My_DF_Weapons_Pistols_ColtPython',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:2000,sellPrice:1500},
{name:'Pistols Deagle',className:'my_df_weapons_pistols_deagle',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:2062},
{name:'Pistols Glock17 C',className:'My_DF_Weapons_Pistols_Glock17C',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:1750,sellPrice:1312},
{name:'Pistols Glock18 C',className:'My_DF_Weapons_Pistols_Glock18C',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:2500,sellPrice:1875},
{name:'Pistols M1911',className:'My_DF_Weapons_Pistols_M1911',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:1500,sellPrice:1125},
{name:'Pistols Qsz92 G',className:'My_DF_Weapons_Pistols_QSZ92G',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:1500,sellPrice:1125},
{name:'Rifles AK-12',className:'My_DF_Weapons_Rifles_AK12',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:7000,sellPrice:5250},
{name:'Rifles AKM',className:'My_DF_Weapons_Rifles_AKM',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:7000,sellPrice:5250},
{name:'Rifles Aks74 U',className:'My_DF_Weapons_Rifles_AKS74U',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6000,sellPrice:4500},
{name:'Rifles Ash12',className:'my_df_weapons_rifles_ash12',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:6375},
{name:'Rifles Asval',className:'my_df_weapons_rifles_asval',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:5812},
{name:'Rifles AUG',className:'My_DF_Weapons_Rifles_AUG',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:5500,sellPrice:4125},
{name:'Rifles Car15',className:'My_DF_Weapons_Rifles_CAR15',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6000,sellPrice:4500},
{name:'Rifles G3',className:'My_DF_Weapons_Rifles_G3',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:7500,sellPrice:5625},
{name:'Rifles K416',className:'My_DF_Weapons_Rifles_K416',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6750,sellPrice:5062},
{name:'Rifles K437',className:'My_DF_Weapons_Rifles_K437',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6500,sellPrice:4875},
{name:'Rifles Kc17',className:'My_DF_Weapons_Rifles_KC17',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6500,sellPrice:4875},
{name:'Rifles M16 A4',className:'My_DF_Weapons_Rifles_M16A4',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6000,sellPrice:4500},
{name:'Rifles M4 A1',className:'My_DF_Weapons_Rifles_M4A1',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6500,sellPrice:4875},
{name:'Rifles M7',className:'My_DF_Weapons_Rifles_M7',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:8000,sellPrice:6000},
{name:'Rifles Mcxlt',className:'My_DF_Weapons_Rifles_MCXLT',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:7000,sellPrice:5250},
{name:'Rifles Mk47',className:'My_DF_Weapons_Rifles_MK47',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:7000,sellPrice:5250},
{name:'Rifles Ptr32',className:'My_DF_Weapons_Rifles_PTR32',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:7000,sellPrice:5250},
{name:'Rifles QBZ-191',className:'My_DF_Weapons_Rifles_QBZ191',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6500,sellPrice:4875},
{name:'Rifles QBZ-95',className:'My_DF_Weapons_Rifles_QBZ95',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6250,sellPrice:4688},
{name:'Rifles SCAR-H',className:'My_DF_Weapons_Rifles_SCARH',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:8000,sellPrice:6000},
{name:'Rifles SG553',className:'My_DF_Weapons_Rifles_SG553',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6500,sellPrice:4875},
{name:'Shotguns Citori725',className:'My_DF_Weapons_Shotguns_Citori725',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:3500,sellPrice:2625},
{name:'Shotguns Fpss',className:'My_DF_Weapons_Shotguns_FPSS',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:4250,sellPrice:3188},
{name:'Shotguns Fpss With Mag',className:'My_DF_Weapons_Shotguns_FPSS_WithMag',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:4500,sellPrice:3375},
{name:'Shotguns M1014',className:'My_DF_Weapons_Shotguns_M1014',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:5500,sellPrice:4125},
{name:'Shotguns M870',className:'My_DF_Weapons_Shotguns_M870',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:3750,sellPrice:2812},
{name:'Shotguns Saiga12 K',className:'My_DF_Weapons_Shotguns_Saiga12K',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:6000,sellPrice:4500},
{name:'SMG Bison',className:'My_DF_Weapons_SMG_Bison',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:4500,sellPrice:3375},
{name:'SMG Mk4',className:'My_DF_Weapons_SMG_MK4',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:3750,sellPrice:2812},
{name:'SMG Mp5',className:'My_DF_Weapons_SMG_MP5',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:4000,sellPrice:3000},
{name:'SMG Mp7',className:'My_DF_Weapons_SMG_MP7',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:5250,sellPrice:3938},
{name:'SMG P90',className:'My_DF_Weapons_SMG_P90',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:5500,sellPrice:4125},
{name:'SMG PP-19',className:'My_DF_Weapons_SMG_PP19',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:4250,sellPrice:3188},
{name:'SMG Qcq171',className:'My_DF_Weapons_SMG_QCQ171',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:4750,sellPrice:3562},
{name:'SMG Smg45',className:'My_DF_Weapons_SMG_SMG45',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:5000,sellPrice:3750},
{name:'SMG Sr3m',className:'my_df_weapons_smg_sr3m',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:4125},
{name:'SMG Uzi',className:'My_DF_Weapons_SMG_Uzi',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:3500,sellPrice:2625},
{name:'SMG Vector',className:'My_DF_Weapons_SMG_Vector',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:5250,sellPrice:3938},
{name:'Snipers Awm',className:'my_df_weapons_snipers_awm',category:'My DF Weapons',traderSells:false,traderBuys:true,sellPrice:7500},
{name:'Snipers M700',className:'My_DF_Weapons_Snipers_M700',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:8500,sellPrice:6375},
{name:'Snipers R93',className:'My_DF_Weapons_Snipers_R93',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:9500,sellPrice:7125},
{name:'Snipers SV-98',className:'My_DF_Weapons_Snipers_SV98',category:'My DF Weapons',traderSells:true,traderBuys:true,buyPrice:9000,sellPrice:6750},
{name:'Cleaver',className:'cleaver',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:718},
{name:'Combatknife',className:'combatknife',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:794},
{name:'Crudemachete',className:'crudemachete',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:756},
{name:'Fangeknife',className:'fangeknife',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:292},
{name:'Huntingknife',className:'huntingknife',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:298},
{name:'Kitchenknife',className:'kitchenknife',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:692},
{name:'Kukriknife',className:'kukriknife',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:806},
{name:'Machete',className:'machete',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:768},
{name:'Orientalmachete',className:'orientalmachete',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:782},
{name:'Steakknife',className:'steakknife',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:702},
{name:'Sword',className:'sword',category:'Vanilla Knives',traderSells:false,traderBuys:true,sellPrice:819},
{name:'Barbedbaseballbat',className:'barbedbaseballbat',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:366},
{name:'Baseballbat',className:'baseballbat',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:366},
{name:'Brassknuckles Dull',className:'brassknuckles_dull',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:321},
{name:'Brassknuckles Shiny',className:'brassknuckles_shiny',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:321},
{name:'Broom',className:'broom',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:220},
{name:'Broom Birch',className:'broom_birch',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:220},
{name:'Iceaxe',className:'iceaxe',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:985},
{name:'Lugwrench',className:'lugwrench',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:546},
{name:'Mace',className:'mace',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:535},
{name:'Meattenderizer',className:'meattenderizer',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:386},
{name:'Nailedbaseballbat',className:'nailedbaseballbat',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:366},
{name:'Pipe',className:'pipe',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:355},
{name:'Pipewrench',className:'pipewrench',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:588},
{name:'Spearbone',className:'spearbone',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:464},
{name:'Spearstone',className:'spearstone',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:436},
{name:'Stunbaton',className:'stunbaton',category:'Vanilla Melee Weapons',traderSells:false,traderBuys:true,sellPrice:265}
]};
