window.traderCatalogue={traderName:'Manua',currency:'USD',items:[
{name:'Battery9v',className:'battery9v',category:'Batteries',buyPrice:0,sellPrice:0,traderSells:true,traderBuys:true},
{name:'Lfpg And Gate Kit',className:'LFPG_AND_Gate_Kit',category:'Bbp Addons',buyPrice:18750,sellPrice:9375,traderSells:true,traderBuys:true},
{name:'Lfpg Battery Large Kit',className:'LFPG_BatteryLarge_Kit',category:'Bbp Addons',buyPrice:131250,sellPrice:65625,traderSells:true,traderBuys:true},
{name:'Lfpg Battery Medium Kit',className:'LFPG_BatteryMedium_Kit',category:'Bbp Addons',buyPrice:75000,sellPrice:37500,traderSells:true,traderBuys:true},
{name:'Lfpg Cable Reel',className:'LFPG_CableReel',category:'Bbp Addons',buyPrice:50000,sellPrice:25000,traderSells:true,traderBuys:true},
{name:'Lfpg Camera Kit',className:'LFPG_Camera_Kit',category:'Bbp Addons',buyPrice:75000,sellPrice:37500,traderSells:true,traderBuys:true},
{name:'Lfpg Ceiling Light Kit',className:'LFPG_CeilingLight_Kit',category:'Bbp Addons',buyPrice:22500,sellPrice:11250,traderSells:true,traderBuys:true},
{name:'Lfpg Combiner Kit',className:'LFPG_Combiner_Kit',category:'Bbp Addons',buyPrice:30000,sellPrice:15000,traderSells:true,traderBuys:true},
{name:'Lfpg Door Controller Kit',className:'LFPG_DoorController_Kit',category:'Bbp Addons',buyPrice:187500,sellPrice:93750,traderSells:true,traderBuys:true},
{name:'Lfpg Electric Stove Kit',className:'LFPG_ElectricStove_Kit',category:'Bbp Addons',buyPrice:75000,sellPrice:37500,traderSells:true,traderBuys:true},
{name:'Lfpg Electronic Counter Kit',className:'LFPG_ElectronicCounter_Kit',category:'Bbp Addons',buyPrice:56250,sellPrice:28125,traderSells:true,traderBuys:true},
{name:'Lfpg Fridge Kit',className:'LFPG_Fridge_Kit',category:'Bbp Addons',buyPrice:93750,sellPrice:46875,traderSells:true,traderBuys:true},
{name:'Lfpg Furnace Kit',className:'LFPG_Furnace_Kit',category:'Bbp Addons',buyPrice:131250,sellPrice:65625,traderSells:true,traderBuys:true},
{name:'Lfpg Generator',className:'LFPG_Generator',category:'Bbp Addons',buyPrice:300000,sellPrice:150000,traderSells:true,traderBuys:true},
{name:'Lfpg Intercom Kit',className:'LFPG_Intercom_Kit',category:'Bbp Addons',buyPrice:37500,sellPrice:18750,traderSells:true,traderBuys:true},
{name:'Lfpg Laser Detector Kit',className:'LFPG_LaserDetector_Kit',category:'Bbp Addons',buyPrice:93750,sellPrice:46875,traderSells:true,traderBuys:true},
{name:'Lfpg Memory Cell Kit',className:'LFPG_MemoryCell_Kit',category:'Bbp Addons',buyPrice:56250,sellPrice:28125,traderSells:true,traderBuys:true},
{name:'Lfpg Monitor Kit',className:'LFPG_Monitor_Kit',category:'Bbp Addons',buyPrice:45000,sellPrice:22500,traderSells:true,traderBuys:true},
{name:'Lfpg Motion Sensor Kit',className:'LFPG_MotionSensor_Kit',category:'Bbp Addons',buyPrice:75000,sellPrice:37500,traderSells:true,traderBuys:true},
{name:'Lfpg Or Gate Kit',className:'LFPG_OR_Gate_Kit',category:'Bbp Addons',buyPrice:18750,sellPrice:9375,traderSells:true,traderBuys:true},
{name:'Lfpg Pressure Pad Kit',className:'LFPG_PressurePad_Kit',category:'Bbp Addons',buyPrice:56250,sellPrice:28125,traderSells:true,traderBuys:true},
{name:'Lfpg Push Button Kit',className:'LFPG_PushButton_Kit',category:'Bbp Addons',buyPrice:18750,sellPrice:9375,traderSells:true,traderBuys:true},
{name:'Lfpg Remote Controller',className:'LFPG_RemoteController',category:'Bbp Addons',buyPrice:75000,sellPrice:37500,traderSells:true,traderBuys:true},
{name:'Lfpg Searchlight Kit',className:'LFPG_Searchlight_Kit',category:'Bbp Addons',buyPrice:56250,sellPrice:28125,traderSells:true,traderBuys:true},
{name:'Lfpg Solar Panel Kit',className:'LFPG_SolarPanel_Kit',category:'Bbp Addons',buyPrice:225000,sellPrice:112500,traderSells:true,traderBuys:true},
{name:'Lfpg Sorter Kit',className:'LFPG_Sorter_Kit',category:'Bbp Addons',buyPrice:131250,sellPrice:65625,traderSells:true,traderBuys:true},
{name:'Lfpg Speaker Kit',className:'LFPG_Speaker_Kit',category:'Bbp Addons',buyPrice:30000,sellPrice:15000,traderSells:true,traderBuys:true},
{name:'Lfpg Splitter Kit',className:'LFPG_Splitter_Kit',category:'Bbp Addons',buyPrice:30000,sellPrice:15000,traderSells:true,traderBuys:true},
{name:'Lfpg Sprinkler Kit',className:'LFPG_Sprinkler_Kit',category:'Bbp Addons',buyPrice:37500,sellPrice:18750,traderSells:true,traderBuys:true},
{name:'Lfpg Switch V2 Kit',className:'LFPG_SwitchV2_Kit',category:'Bbp Addons',buyPrice:26250,sellPrice:13125,traderSells:true,traderBuys:true},
{name:'Lfpg Switch V2 Remote Kit',className:'LFPG_SwitchV2Remote_Kit',category:'Bbp Addons',buyPrice:45000,sellPrice:22500,traderSells:true,traderBuys:true},
{name:'Lfpg Wall Lamp Kit',className:'LFPG_WallLamp_Kit',category:'Bbp Addons',buyPrice:22500,sellPrice:11250,traderSells:true,traderBuys:true},
{name:'Lfpg Water Pump Kit',className:'LFPG_WaterPump_Kit',category:'Bbp Addons',buyPrice:150000,sellPrice:75000,traderSells:true,traderBuys:true},
{name:'Lfpg Xor Gate Kit',className:'LFPG_XOR_Gate_Kit',category:'Bbp Addons',buyPrice:22500,sellPrice:11250,traderSells:true,traderBuys:true},
{name:'Bbp Bedding',className:'bbp_bedding',category:'Bbp Items',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Bbp Bedkit',className:'bbp_bedkit',category:'Bbp Items',buyPrice:3500,sellPrice:1750,traderSells:true,traderBuys:true},
{name:'Bbp Bucket',className:'bbp_bucket',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Gang Plug',className:'bbp_gang_plug',category:'Bbp Items',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large A',className:'bbp_letter_large_a',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large B',className:'bbp_letter_large_b',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large C',className:'bbp_letter_large_c',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large D',className:'bbp_letter_large_d',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large E',className:'bbp_letter_large_e',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large F',className:'bbp_letter_large_f',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large G',className:'bbp_letter_large_g',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large H',className:'bbp_letter_large_h',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large I',className:'bbp_letter_large_i',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large J',className:'bbp_letter_large_j',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large K',className:'bbp_letter_large_k',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large L',className:'bbp_letter_large_l',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large M',className:'bbp_letter_large_m',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large N',className:'bbp_letter_large_n',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large O',className:'bbp_letter_large_o',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large P',className:'bbp_letter_large_p',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large Q',className:'bbp_letter_large_q',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large R',className:'bbp_letter_large_r',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large S',className:'bbp_letter_large_s',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large T',className:'bbp_letter_large_t',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large U',className:'bbp_letter_large_u',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large V',className:'bbp_letter_large_v',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large W',className:'bbp_letter_large_w',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large X',className:'bbp_letter_large_x',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large Y',className:'bbp_letter_large_y',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Letter Large Z',className:'bbp_letter_large_z',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet A',className:'bbp_magnet_a',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet B',className:'bbp_magnet_b',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet C',className:'bbp_magnet_c',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet D',className:'bbp_magnet_d',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet E',className:'bbp_magnet_e',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet F',className:'bbp_magnet_f',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet G',className:'bbp_magnet_g',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet H',className:'bbp_magnet_h',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet I',className:'bbp_magnet_i',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet J',className:'bbp_magnet_j',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet K',className:'bbp_magnet_k',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet L',className:'bbp_magnet_l',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet M',className:'bbp_magnet_m',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet N',className:'bbp_magnet_n',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet O',className:'bbp_magnet_o',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet P',className:'bbp_magnet_p',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet Q',className:'bbp_magnet_q',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet R',className:'bbp_magnet_r',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet S',className:'bbp_magnet_s',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet T',className:'bbp_magnet_t',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet U',className:'bbp_magnet_u',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet V',className:'bbp_magnet_v',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet W',className:'bbp_magnet_w',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet X',className:'bbp_magnet_x',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet Y',className:'bbp_magnet_y',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnet Z',className:'bbp_magnet_z',category:'Bbp Items',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Bbp Magnetbox',className:'bbp_magnetbox',category:'Bbp Items',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Bbp Old Lamp',className:'bbp_old_lamp',category:'Bbp Items',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Bbp Painting',className:'bbp_painting',category:'Bbp Items',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Bbp Painting 1',className:'bbp_painting_1',category:'Bbp Items',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Bbp Painting 2',className:'bbp_painting_2',category:'Bbp Items',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Bbp Painting Landscape',className:'bbp_painting_landscape',category:'Bbp Items',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Bbp Photoframe Landscape',className:'bbp_photoframe_landscape',category:'Bbp Items',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Bbp Photoframe Portrait',className:'bbp_photoframe_portrait',category:'Bbp Items',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Bbp Sofakit',className:'bbp_sofakit',category:'Bbp Items',buyPrice:5000,sellPrice:2500,traderSells:true,traderBuys:true},
{name:'Bbp Solarplus Panelkit',className:'bbp_solarplus_panelkit',category:'Bbp Items',buyPrice:7500,sellPrice:3750,traderSells:true,traderBuys:true},
{name:'Bbp Toilet',className:'bbp_toilet',category:'Bbp Items',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Bbp Xmaslights 9v',className:'bbp_xmaslights_9v',category:'Bbp Items',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Bbp Xmaslights Solar',className:'bbp_xmaslights_solar',category:'Bbp Items',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Ammobox',className:'ammobox',category:'Containers',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Barrel Blue',className:'barrel_blue',category:'Containers',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Barrel Green',className:'barrel_green',category:'Containers',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Barrel Red',className:'barrel_red',category:'Containers',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Barrel Yellow',className:'barrel_yellow',category:'Containers',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Seachest',className:'seachest',category:'Containers',buyPrice:3500,sellPrice:1750,traderSells:true,traderBuys:true},
{name:'Smallprotectorcase',className:'smallprotectorcase',category:'Containers',buyPrice:2500,sellPrice:1250,traderSells:true,traderBuys:true},
{name:'Alarmclock Blue',className:'alarmclock_blue',category:'Electronics',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Alarmclock Green',className:'alarmclock_green',category:'Electronics',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Alarmclock Red',className:'alarmclock_red',category:'Electronics',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Cablereel',className:'cablereel',category:'Electronics',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Electronicrepairkit',className:'electronicrepairkit',category:'Electronics',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Kitchentimer',className:'kitchentimer',category:'Electronics',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Megaphone',className:'megaphone',category:'Electronics',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Rangefinder',className:'rangefinder',category:'Electronics',buyPrice:5000,sellPrice:2500,traderSells:true,traderBuys:true},
{name:'Flag Altis',className:'flag_altis',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Apa',className:'flag_apa',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Babydeer',className:'flag_babydeer',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Bear',className:'flag_bear',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Bohemia',className:'flag_bohemia',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Brainz',className:'flag_brainz',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Cannibals',className:'flag_cannibals',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Cdf',className:'flag_cdf',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Chedaki',className:'flag_chedaki',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Chel',className:'flag_chel',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Chernarus',className:'flag_chernarus',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Cmc',className:'flag_cmc',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Crook',className:'flag_crook',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Dayz',className:'flag_dayz',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Hunterz',className:'flag_hunterz',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Livonia',className:'flag_livonia',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Livoniaarmy',className:'flag_livoniaarmy',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Livoniapolice',className:'flag_livoniapolice',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Napa',className:'flag_napa',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Nsahrani',className:'flag_nsahrani',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Pirates',className:'flag_pirates',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Refuge',className:'flag_refuge',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Rex',className:'flag_rex',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Rooster',className:'flag_rooster',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Rsta',className:'flag_rsta',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Snake',className:'flag_snake',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Ssahrani',className:'flag_ssahrani',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Tec',className:'flag_tec',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Uec',className:'flag_uec',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag White',className:'flag_white',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Wolf',className:'flag_wolf',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Zagorky',className:'flag_zagorky',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Flag Zenit',className:'flag_zenit',category:'Flags',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Chemlight Blue',className:'chemlight_blue',category:'Lights',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Chemlight Green',className:'chemlight_green',category:'Lights',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Chemlight Red',className:'chemlight_red',category:'Lights',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Chemlight White',className:'chemlight_white',category:'Lights',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Chemlight Yellow',className:'chemlight_yellow',category:'Lights',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Fireworkslauncher',className:'fireworkslauncher',category:'Lights',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Flashlight',className:'flashlight',category:'Lights',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Headtorch Black',className:'headtorch_black',category:'Lights',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Headtorch Grey',className:'headtorch_grey',category:'Lights',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Matchbox',className:'matchbox',category:'Lights',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Petrollighter',className:'petrollighter',category:'Lights',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Portablegaslamp',className:'portablegaslamp',category:'Lights',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Roadflare',className:'roadflare',category:'Lights',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Spotlight',className:'spotlight',category:'Lights',buyPrice:2000,sellPrice:1000,traderSells:true,traderBuys:true},
{name:'Tlrlight',className:'tlrlight',category:'Lights',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Universallight',className:'universallight',category:'Lights',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Xmaslights',className:'xmaslights',category:'Lights',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Bbp Blueprint',className:'bbp_blueprint',category:'Supplies',buyPrice:5000,sellPrice:2500,traderSells:true,traderBuys:true},
{name:'Bbp Carpet 1',className:'bbp_carpet_1',category:'Supplies',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Bbp Carpet 2',className:'bbp_carpet_2',category:'Supplies',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Bbp Cement',className:'bbp_cement',category:'Supplies',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Bbp Mortar Mix',className:'bbp_mortar_mix',category:'Supplies',buyPrice:1800,sellPrice:900,traderSells:true,traderBuys:true},
{name:'Bbp Plaster 1',className:'bbp_plaster_1',category:'Supplies',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Bbp Plaster 2',className:'bbp_plaster_2',category:'Supplies',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Bbp Tapemeasure',className:'bbp_tapemeasure',category:'Supplies',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Bbp Wallpaper 1',className:'bbp_wallpaper_1',category:'Supplies',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Bbp Wallpaper 2',className:'bbp_wallpaper_2',category:'Supplies',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Bbp Wallpaper Mural 1',className:'bbp_wallpaper_mural_1',category:'Supplies',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Bbp Wallpaper Mural 2',className:'bbp_wallpaper_mural_2',category:'Supplies',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Bear Beige',className:'bear_beige',category:'Supplies',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Bear Dark',className:'bear_dark',category:'Supplies',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Bear Pink',className:'bear_pink',category:'Supplies',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Bear White',className:'bear_white',category:'Supplies',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Camonet',className:'camonet',category:'Supplies',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Epoxyputty',className:'epoxyputty',category:'Supplies',buyPrice:1200,sellPrice:600,traderSells:true,traderBuys:true},
{name:'Largegascanister',className:'largegascanister',category:'Supplies',buyPrice:2500,sellPrice:1250,traderSells:true,traderBuys:true},
{name:'Nailbox',className:'nailbox',category:'Supplies',buyPrice:3500,sellPrice:1750,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Cleaning Patches',className:'rag_baseitems_cleaning_patches',category:'Supplies',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Jar',className:'rag_baseitems_coffee_jar',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Blue Bar',className:'rag_baseitems_coffee_mug_blue_bar',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Blue Break',className:'rag_baseitems_coffee_mug_blue_break',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Green Bar',className:'rag_baseitems_coffee_mug_green_bar',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Green Break',className:'rag_baseitems_coffee_mug_green_break',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Green Fresh',className:'rag_baseitems_coffee_mug_green_fresh',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Purple Bar',className:'rag_baseitems_coffee_mug_purple_bar',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Purple Break',className:'rag_baseitems_coffee_mug_purple_break',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Rag',className:'rag_baseitems_coffee_mug_rag',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Red Bar',className:'rag_baseitems_coffee_mug_red_bar',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Red Break',className:'rag_baseitems_coffee_mug_red_break',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Yellow Break',className:'rag_baseitems_coffee_mug_yellow_break',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Yellow Fresh',className:'rag_baseitems_coffee_mug_yellow_fresh',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Mug Yellow Shop',className:'rag_baseitems_coffee_mug_yellow_shop',category:'Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Pack',className:'rag_baseitems_coffee_pack',category:'Supplies',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Thermos',className:'rag_baseitems_coffee_thermos',category:'Supplies',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Grammophone 2 Disk',className:'rag_baseitems_grammophone_2_disk',category:'Supplies',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Grammophone 3 Disk',className:'rag_baseitems_grammophone_3_disk',category:'Supplies',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Grammophone 4 Disk',className:'rag_baseitems_grammophone_4_disk',category:'Supplies',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Grammophone 5 Disk',className:'rag_baseitems_grammophone_5_disk',category:'Supplies',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Grammophone Disk',className:'rag_baseitems_grammophone_disk',category:'Supplies',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Portafilter',className:'rag_baseitems_portafilter',category:'Supplies',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Sawblade',className:'rag_baseitems_sawblade',category:'Supplies',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Spraycan Paint',className:'rag_baseitems_spraycan_paint',category:'Supplies',buyPrice:600,sellPrice:300,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Spraycan White',className:'rag_baseitems_spraycan_white',category:'Supplies',buyPrice:600,sellPrice:300,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Weapon Solvent',className:'rag_baseitems_weapon_solvent',category:'Supplies',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Workbench Blueprint',className:'rag_baseitems_workbench_blueprint',category:'Supplies',buyPrice:5000,sellPrice:2500,traderSells:true,traderBuys:true},
{name:'Tripod',className:'tripod',category:'Supplies',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Cartent',className:'cartent',category:'Tents',buyPrice:15000,sellPrice:7500,traderSells:true,traderBuys:true},
{name:'Largetent',className:'largetent',category:'Tents',buyPrice:10000,sellPrice:5000,traderSells:true,traderBuys:true},
{name:'Mediumtent',className:'mediumtent',category:'Tents',buyPrice:5000,sellPrice:2500,traderSells:true,traderBuys:true},
{name:'Mediumtent Green',className:'mediumtent_green',category:'Tents',buyPrice:5000,sellPrice:2500,traderSells:true,traderBuys:true},
{name:'Mediumtent Orange',className:'mediumtent_orange',category:'Tents',buyPrice:5000,sellPrice:2500,traderSells:true,traderBuys:true},
{name:'Partytent',className:'partytent',category:'Tents',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Partytent Blue',className:'partytent_blue',category:'Tents',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Partytent Brown',className:'partytent_brown',category:'Tents',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Partytent Lunapark',className:'partytent_lunapark',category:'Tents',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Bbp Cement Mixer Kit',className:'bbp_cement_mixer_kit',category:'Tools',buyPrice:5000,sellPrice:2500,traderSells:true,traderBuys:true},
{name:'Canopener',className:'canopener',category:'Tools',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Farminghoe',className:'farminghoe',category:'Tools',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Fieldshovel',className:'fieldshovel',category:'Tools',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Firefighteraxe',className:'firefighteraxe',category:'Tools',buyPrice:2000,sellPrice:1000,traderSells:true,traderBuys:true},
{name:'Fryingpan',className:'fryingpan',category:'Tools',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Hacksaw',className:'hacksaw',category:'Tools',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Hammer',className:'hammer',category:'Tools',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Handsaw',className:'handsaw',category:'Tools',buyPrice:1200,sellPrice:600,traderSells:true,traderBuys:true},
{name:'Hatchet',className:'hatchet',category:'Tools',buyPrice:2000,sellPrice:1000,traderSells:true,traderBuys:true},
{name:'Pickaxe',className:'pickaxe',category:'Tools',buyPrice:2500,sellPrice:1250,traderSells:true,traderBuys:true},
{name:'Pitchfork',className:'pitchfork',category:'Tools',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Pliers',className:'pliers',category:'Tools',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Portablegasstove',className:'portablegasstove',category:'Tools',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Screwdriver',className:'screwdriver',category:'Tools',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Shovel',className:'shovel',category:'Tools',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Sickle',className:'sickle',category:'Tools',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Sledgehammer',className:'sledgehammer',category:'Tools',buyPrice:2500,sellPrice:1250,traderSells:true,traderBuys:true},
{name:'Woodaxe',className:'woodaxe',category:'Tools',buyPrice:2000,sellPrice:1000,traderSells:true,traderBuys:true},
{name:'Wrench',className:'wrench',category:'Tools',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true}
]};
