window.traderCatalogue={traderName:'Manua',currency:'USD',items:[
{name:'Battery9v',className:'battery9v',category:'Batteries',buyPrice:0,traderSells:true,traderBuys:false},
{name:'Lfpg And Gate Kit',className:'LFPG_AND_Gate_Kit',category:'Bbp Addons',buyPrice:18750,traderSells:true,traderBuys:false},
{name:'Lfpg Battery Large Kit',className:'LFPG_BatteryLarge_Kit',category:'Bbp Addons',buyPrice:131250,traderSells:true,traderBuys:false},
{name:'Lfpg Battery Medium Kit',className:'LFPG_BatteryMedium_Kit',category:'Bbp Addons',buyPrice:75000,traderSells:true,traderBuys:false},
{name:'Lfpg Cable Reel',className:'LFPG_CableReel',category:'Bbp Addons',buyPrice:50000,traderSells:true,traderBuys:false},
{name:'Lfpg Camera Kit',className:'LFPG_Camera_Kit',category:'Bbp Addons',buyPrice:75000,traderSells:true,traderBuys:false},
{name:'Lfpg Ceiling Light Kit',className:'LFPG_CeilingLight_Kit',category:'Bbp Addons',buyPrice:22500,traderSells:true,traderBuys:false},
{name:'Lfpg Combiner Kit',className:'LFPG_Combiner_Kit',category:'Bbp Addons',buyPrice:30000,traderSells:true,traderBuys:false},
{name:'Lfpg Door Controller Kit',className:'LFPG_DoorController_Kit',category:'Bbp Addons',buyPrice:187500,traderSells:true,traderBuys:false},
{name:'Lfpg Electric Stove Kit',className:'LFPG_ElectricStove_Kit',category:'Bbp Addons',buyPrice:75000,traderSells:true,traderBuys:false},
{name:'Lfpg Electronic Counter Kit',className:'LFPG_ElectronicCounter_Kit',category:'Bbp Addons',buyPrice:56250,traderSells:true,traderBuys:false},
{name:'Lfpg Fridge Kit',className:'LFPG_Fridge_Kit',category:'Bbp Addons',buyPrice:93750,traderSells:true,traderBuys:false},
{name:'Lfpg Furnace Kit',className:'LFPG_Furnace_Kit',category:'Bbp Addons',buyPrice:131250,traderSells:true,traderBuys:false},
{name:'Lfpg Generator',className:'LFPG_Generator',category:'Bbp Addons',buyPrice:300000,traderSells:true,traderBuys:false},
{name:'Lfpg Intercom Kit',className:'LFPG_Intercom_Kit',category:'Bbp Addons',buyPrice:37500,traderSells:true,traderBuys:false},
{name:'Lfpg Laser Detector Kit',className:'LFPG_LaserDetector_Kit',category:'Bbp Addons',buyPrice:93750,traderSells:true,traderBuys:false},
{name:'Lfpg Memory Cell Kit',className:'LFPG_MemoryCell_Kit',category:'Bbp Addons',buyPrice:56250,traderSells:true,traderBuys:false},
{name:'Lfpg Monitor Kit',className:'LFPG_Monitor_Kit',category:'Bbp Addons',buyPrice:45000,traderSells:true,traderBuys:false},
{name:'Lfpg Motion Sensor Kit',className:'LFPG_MotionSensor_Kit',category:'Bbp Addons',buyPrice:75000,traderSells:true,traderBuys:false},
{name:'Lfpg Or Gate Kit',className:'LFPG_OR_Gate_Kit',category:'Bbp Addons',buyPrice:18750,traderSells:true,traderBuys:false},
{name:'Lfpg Pressure Pad Kit',className:'LFPG_PressurePad_Kit',category:'Bbp Addons',buyPrice:56250,traderSells:true,traderBuys:false},
{name:'Lfpg Push Button Kit',className:'LFPG_PushButton_Kit',category:'Bbp Addons',buyPrice:18750,traderSells:true,traderBuys:false},
{name:'Lfpg Remote Controller',className:'LFPG_RemoteController',category:'Bbp Addons',buyPrice:75000,traderSells:true,traderBuys:false},
{name:'Lfpg Searchlight Kit',className:'LFPG_Searchlight_Kit',category:'Bbp Addons',buyPrice:56250,traderSells:true,traderBuys:false},
{name:'Lfpg Solar Panel Kit',className:'LFPG_SolarPanel_Kit',category:'Bbp Addons',buyPrice:225000,traderSells:true,traderBuys:false},
{name:'Lfpg Sorter Kit',className:'LFPG_Sorter_Kit',category:'Bbp Addons',buyPrice:131250,traderSells:true,traderBuys:false},
{name:'Lfpg Speaker Kit',className:'LFPG_Speaker_Kit',category:'Bbp Addons',buyPrice:30000,traderSells:true,traderBuys:false},
{name:'Lfpg Splitter Kit',className:'LFPG_Splitter_Kit',category:'Bbp Addons',buyPrice:30000,traderSells:true,traderBuys:false},
{name:'Lfpg Sprinkler Kit',className:'LFPG_Sprinkler_Kit',category:'Bbp Addons',buyPrice:37500,traderSells:true,traderBuys:false},
{name:'Lfpg Switch V2 Kit',className:'LFPG_SwitchV2_Kit',category:'Bbp Addons',buyPrice:26250,traderSells:true,traderBuys:false},
{name:'Lfpg Switch V2 Remote Kit',className:'LFPG_SwitchV2Remote_Kit',category:'Bbp Addons',buyPrice:45000,traderSells:true,traderBuys:false},
{name:'Lfpg Wall Lamp Kit',className:'LFPG_WallLamp_Kit',category:'Bbp Addons',buyPrice:22500,traderSells:true,traderBuys:false},
{name:'Lfpg Water Pump Kit',className:'LFPG_WaterPump_Kit',category:'Bbp Addons',buyPrice:150000,traderSells:true,traderBuys:false},
{name:'Lfpg Xor Gate Kit',className:'LFPG_XOR_Gate_Kit',category:'Bbp Addons',buyPrice:22500,traderSells:true,traderBuys:false},
{name:'Bbp Bedding',className:'bbp_bedding',category:'Bbp Items',buyPrice:92875,traderSells:true,traderBuys:false},
{name:'Bbp Bedkit',className:'bbp_bedkit',category:'Bbp Items',buyPrice:96340,traderSells:true,traderBuys:false},
{name:'Bbp Bucket',className:'bbp_bucket',category:'Bbp Items',buyPrice:89160,traderSells:true,traderBuys:false},
{name:'Bbp Gang Plug',className:'bbp_gang_plug',category:'Bbp Items',buyPrice:104825,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large A',className:'bbp_letter_large_a',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large B',className:'bbp_letter_large_b',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large C',className:'bbp_letter_large_c',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large D',className:'bbp_letter_large_d',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large E',className:'bbp_letter_large_e',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large F',className:'bbp_letter_large_f',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large G',className:'bbp_letter_large_g',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large H',className:'bbp_letter_large_h',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large I',className:'bbp_letter_large_i',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large J',className:'bbp_letter_large_j',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large K',className:'bbp_letter_large_k',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large L',className:'bbp_letter_large_l',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large M',className:'bbp_letter_large_m',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large N',className:'bbp_letter_large_n',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large O',className:'bbp_letter_large_o',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large P',className:'bbp_letter_large_p',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large Q',className:'bbp_letter_large_q',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large R',className:'bbp_letter_large_r',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large S',className:'bbp_letter_large_s',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large T',className:'bbp_letter_large_t',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large U',className:'bbp_letter_large_u',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large V',className:'bbp_letter_large_v',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large W',className:'bbp_letter_large_w',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large X',className:'bbp_letter_large_x',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large Y',className:'bbp_letter_large_y',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Letter Large Z',className:'bbp_letter_large_z',category:'Bbp Items',buyPrice:91745,traderSells:true,traderBuys:false},
{name:'Bbp Magnet A',className:'bbp_magnet_a',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet B',className:'bbp_magnet_b',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet C',className:'bbp_magnet_c',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet D',className:'bbp_magnet_d',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet E',className:'bbp_magnet_e',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet F',className:'bbp_magnet_f',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet G',className:'bbp_magnet_g',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet H',className:'bbp_magnet_h',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet I',className:'bbp_magnet_i',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet J',className:'bbp_magnet_j',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet K',className:'bbp_magnet_k',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet L',className:'bbp_magnet_l',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet M',className:'bbp_magnet_m',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet N',className:'bbp_magnet_n',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet O',className:'bbp_magnet_o',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet P',className:'bbp_magnet_p',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet Q',className:'bbp_magnet_q',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet R',className:'bbp_magnet_r',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet S',className:'bbp_magnet_s',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet T',className:'bbp_magnet_t',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet U',className:'bbp_magnet_u',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet V',className:'bbp_magnet_v',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet W',className:'bbp_magnet_w',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet X',className:'bbp_magnet_x',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet Y',className:'bbp_magnet_y',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnet Z',className:'bbp_magnet_z',category:'Bbp Items',buyPrice:90395,traderSells:true,traderBuys:false},
{name:'Bbp Magnetbox',className:'bbp_magnetbox',category:'Bbp Items',buyPrice:98720,traderSells:true,traderBuys:false},
{name:'Bbp Old Lamp',className:'bbp_old_lamp',category:'Bbp Items',buyPrice:94860,traderSells:true,traderBuys:false},
{name:'Bbp Painting',className:'bbp_painting',category:'Bbp Items',buyPrice:97535,traderSells:true,traderBuys:false},
{name:'Bbp Painting 1',className:'bbp_painting_1',category:'Bbp Items',buyPrice:101280,traderSells:true,traderBuys:false},
{name:'Bbp Painting 2',className:'bbp_painting_2',category:'Bbp Items',buyPrice:93915,traderSells:true,traderBuys:false},
{name:'Bbp Painting Landscape',className:'bbp_painting_landscape',category:'Bbp Items',buyPrice:106450,traderSells:true,traderBuys:false},
{name:'Bbp Photoframe Landscape',className:'bbp_photoframe_landscape',category:'Bbp Items',buyPrice:92210,traderSells:true,traderBuys:false},
{name:'Bbp Photoframe Portrait',className:'bbp_photoframe_portrait',category:'Bbp Items',buyPrice:93680,traderSells:true,traderBuys:false},
{name:'Bbp Sofakit',className:'bbp_sofakit',category:'Bbp Items',buyPrice:112640,traderSells:true,traderBuys:false},
{name:'Bbp Solarplus Panelkit',className:'bbp_solarplus_panelkit',category:'Bbp Items',buyPrice:119875,traderSells:true,traderBuys:false},
{name:'Bbp Toilet',className:'bbp_toilet',category:'Bbp Items',buyPrice:90840,traderSells:true,traderBuys:false},
{name:'Bbp Xmaslights 9v',className:'bbp_xmaslights_9v',category:'Bbp Items',buyPrice:99560,traderSells:true,traderBuys:false},
{name:'Bbp Xmaslights Solar',className:'bbp_xmaslights_solar',category:'Bbp Items',buyPrice:108735,traderSells:true,traderBuys:false},
{name:'Ammobox',className:'ammobox',category:'Containers',buyPrice:44865,traderSells:true,traderBuys:false},
{name:'Barrel Blue',className:'barrel_blue',category:'Containers',buyPrice:98235,traderSells:true,traderBuys:false},
{name:'Barrel Green',className:'barrel_green',category:'Containers',buyPrice:98235,traderSells:true,traderBuys:false},
{name:'Barrel Red',className:'barrel_red',category:'Containers',buyPrice:98235,traderSells:true,traderBuys:false},
{name:'Barrel Yellow',className:'barrel_yellow',category:'Containers',buyPrice:98235,traderSells:true,traderBuys:false},
{name:'Seachest',className:'seachest',category:'Containers',buyPrice:88790,traderSells:true,traderBuys:false},
{name:'Smallprotectorcase',className:'smallprotectorcase',category:'Containers',buyPrice:74955,traderSells:true,traderBuys:false},
{name:'Alarmclock Blue',className:'alarmclock_blue',category:'Electronics',buyPrice:9845,traderSells:true,traderBuys:false},
{name:'Alarmclock Green',className:'alarmclock_green',category:'Electronics',buyPrice:9845,traderSells:true,traderBuys:false},
{name:'Alarmclock Red',className:'alarmclock_red',category:'Electronics',buyPrice:9845,traderSells:true,traderBuys:false},
{name:'Cablereel',className:'cablereel',category:'Electronics',buyPrice:74865,traderSells:true,traderBuys:false},
{name:'Electronicrepairkit',className:'electronicrepairkit',category:'Electronics',buyPrice:76235,traderSells:true,traderBuys:false},
{name:'Kitchentimer',className:'kitchentimer',category:'Electronics',buyPrice:11285,traderSells:true,traderBuys:false},
{name:'Megaphone',className:'megaphone',category:'Electronics',buyPrice:24675,traderSells:true,traderBuys:false},
{name:'Rangefinder',className:'rangefinder',category:'Electronics',buyPrice:73955,traderSells:true,traderBuys:false},
{name:'Flag Altis',className:'flag_altis',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Apa',className:'flag_apa',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Babydeer',className:'flag_babydeer',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Bear',className:'flag_bear',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Bohemia',className:'flag_bohemia',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Brainz',className:'flag_brainz',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Cannibals',className:'flag_cannibals',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Cdf',className:'flag_cdf',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Chedaki',className:'flag_chedaki',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Chel',className:'flag_chel',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Chernarus',className:'flag_chernarus',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Cmc',className:'flag_cmc',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Crook',className:'flag_crook',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Dayz',className:'flag_dayz',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Hunterz',className:'flag_hunterz',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Livonia',className:'flag_livonia',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Livoniaarmy',className:'flag_livoniaarmy',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Livoniapolice',className:'flag_livoniapolice',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Napa',className:'flag_napa',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Nsahrani',className:'flag_nsahrani',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Pirates',className:'flag_pirates',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Refuge',className:'flag_refuge',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Rex',className:'flag_rex',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Rooster',className:'flag_rooster',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Rsta',className:'flag_rsta',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Snake',className:'flag_snake',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Ssahrani',className:'flag_ssahrani',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Tec',className:'flag_tec',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Uec',className:'flag_uec',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag White',className:'flag_white',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Wolf',className:'flag_wolf',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Zagorky',className:'flag_zagorky',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Flag Zenit',className:'flag_zenit',category:'Flags',buyPrice:500,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Antique Dresser Kit',className:'rag_baseitems_antique_dresser_kit',category:'Furnishings',sellPrice:843,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Antique Wall Clock Kit',className:'rag_baseitems_antique_wall_clock_kit',category:'Furnishings',buyPrice:75235,sellPrice:752,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Barrelshelf Kit',className:'rag_baseitems_barrelshelf_kit',category:'Furnishings',sellPrice:918,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Basket Kit',className:'rag_baseitems_basket_kit',category:'Furnishings',buyPrice:72145,sellPrice:721,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Beach Chair Kit',className:'rag_baseitems_beach_chair_kit',category:'Furnishings',buyPrice:74785,sellPrice:748,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Beach Umbrella Beige Kit',className:'rag_baseitems_beach_umbrella_beige_kit',category:'Furnishings',buyPrice:74890,sellPrice:749,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Bed Kit',className:'rag_baseitems_bed_kit',category:'Furnishings',buyPrice:75110,sellPrice:751,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Bedside Table Kit',className:'rag_baseitems_bedside_table_kit',category:'Furnishings',buyPrice:76870,sellPrice:769,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Big Drawer Cabinet Darkwood Kit',className:'rag_baseitems_big_drawer_cabinet_darkwood_kit',category:'Furnishings',sellPrice:956,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Big Drawer Cabinet Kit',className:'rag_baseitems_big_drawer_cabinet_kit',category:'Furnishings',sellPrice:956,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Big Safe Kit',className:'rag_baseitems_big_safe_kit',category:'Furnishings',sellPrice:1284,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Brazier Kit',className:'rag_baseitems_brazier_kit',category:'Furnishings',buyPrice:75325,sellPrice:753,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Brazier Small Kit',className:'rag_baseitems_brazier_small_kit',category:'Furnishings',buyPrice:74675,sellPrice:747,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Celtic Shelter Kit',className:'rag_baseitems_celtic_shelter_kit',category:'Furnishings',sellPrice:883,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Coffee Grinder Kit',className:'rag_baseitems_coffee_grinder_kit',category:'Furnishings',buyPrice:81365,sellPrice:814,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Coffee Hutch Kit',className:'rag_baseitems_coffee_hutch_kit',category:'Furnishings',sellPrice:868,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Coffee Machine Kit',className:'rag_baseitems_coffee_machine_kit',category:'Furnishings',buyPrice:85420,sellPrice:854,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Crateshelf Kit',className:'rag_baseitems_crateshelf_kit',category:'Furnishings',sellPrice:928,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Crystal Ball Kit',className:'rag_baseitems_crystal_ball_kit',category:'Furnishings',buyPrice:88695,sellPrice:887,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Cuckoo Clock Kit',className:'rag_baseitems_cuckoo_clock_kit',category:'Furnishings',buyPrice:75410,sellPrice:754,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Dinner Table Chair Kit',className:'rag_baseitems_dinner_table_chair_kit',category:'Furnishings',buyPrice:75270,sellPrice:753,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Dinner Table Kit',className:'rag_baseitems_dinner_table_kit',category:'Furnishings',buyPrice:74855,sellPrice:749,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Firstaid Cabinet Big Kit',className:'rag_baseitems_firstaid_cabinet_big_kit',category:'Furnishings',sellPrice:1028,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Firstaid Cabinet Kit',className:'rag_baseitems_firstaid_cabinet_kit',category:'Furnishings',sellPrice:938,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Fishing Rod Rack Kit',className:'rag_baseitems_fishing_rod_rack_kit',category:'Furnishings',buyPrice:75015,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Food Dono Stand Kit',className:'rag_baseitems_food_dono_stand_kit',category:'Furnishings',sellPrice:873,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Fridge Twodoor Old Kit',className:'rag_baseitems_fridge_twodoor_old_kit',category:'Furnishings',sellPrice:915,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Gazebo Kit',className:'rag_baseitems_gazebo_kit',category:'Furnishings',buyPrice:75620,sellPrice:756,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Globe Kit',className:'rag_baseitems_globe_kit',category:'Furnishings',buyPrice:75145,sellPrice:751,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Grammophone Kit',className:'rag_baseitems_grammophone_kit',category:'Furnishings',buyPrice:89580,sellPrice:896,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Gramophone Table Kit',className:'rag_baseitems_gramophone_table_kit',category:'Furnishings',buyPrice:74910,sellPrice:749,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Grandfathers Clock Kit',className:'rag_baseitems_grandfathers_clock_kit',category:'Furnishings',buyPrice:75575,sellPrice:756,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Gun Cabinet Kit',className:'rag_baseitems_gun_cabinet_kit',category:'Furnishings',sellPrice:1183,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Gunrack Kit',className:'rag_baseitems_gunrack_kit',category:'Furnishings',sellPrice:1096,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Gunwall Kit',className:'rag_baseitems_gunwall_kit',category:'Furnishings',sellPrice:1169,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Improvised Bed Kit',className:'rag_baseitems_improvised_bed_kit',category:'Furnishings',buyPrice:73440,sellPrice:734,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Jd Fridge Kit',className:'rag_baseitems_jd_fridge_kit',category:'Furnishings',sellPrice:970,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Lantern Kit',className:'rag_baseitems_lantern_kit',category:'Furnishings',buyPrice:100945,sellPrice:1009,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Lantern Wall Kit',className:'rag_baseitems_lantern_wall_kit',category:'Furnishings',buyPrice:101375,sellPrice:1014,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Log Holder Kit',className:'rag_baseitems_log_holder_kit',category:'Furnishings',buyPrice:77860,sellPrice:779,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Magpump Kit',className:'rag_baseitems_magpump_kit',category:'Furnishings',sellPrice:1032,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Manikin Kit',className:'rag_baseitems_manikin_kit',category:'Furnishings',sellPrice:882,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Mask Head Kit',className:'rag_baseitems_mask_head_kit',category:'Furnishings',buyPrice:78295,sellPrice:783,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Medic Box Kit',className:'rag_baseitems_medic_box_kit',category:'Furnishings',sellPrice:895,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Medieval Fireplace Kit',className:'rag_baseitems_medieval_fireplace_kit',category:'Furnishings',buyPrice:97465,sellPrice:975,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Medium Safe Kit',className:'rag_baseitems_medium_safe_kit',category:'Furnishings',sellPrice:1218,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Mesh Locker Kit',className:'rag_baseitems_mesh_locker_kit',category:'Furnishings',sellPrice:985,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Military Locker Big Kit',className:'rag_baseitems_military_locker_big_kit',category:'Furnishings',sellPrice:1259,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Military Locker Small Kit',className:'rag_baseitems_military_locker_small_kit',category:'Furnishings',sellPrice:1119,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Military Locker Threedoor Kit',className:'rag_baseitems_military_locker_threedoor_kit',category:'Furnishings',sellPrice:1197,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Odin Kit',className:'rag_baseitems_odin_kit',category:'Furnishings',buyPrice:90785,sellPrice:908,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Pistol Cabinet Kit',className:'rag_baseitems_pistol_cabinet_kit',category:'Furnishings',sellPrice:1048,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Plank Holder Kit',className:'rag_baseitems_plank_holder_kit',category:'Furnishings',buyPrice:79735,sellPrice:797,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Plant Rack Kit',className:'rag_baseitems_plant_rack_kit',category:'Furnishings',buyPrice:76925,sellPrice:769,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Planterbox High Kit',className:'rag_baseitems_planterbox_high_kit',category:'Furnishings',buyPrice:78460,sellPrice:785,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Planterbox Low Kit',className:'rag_baseitems_planterbox_low_kit',category:'Furnishings',buyPrice:76380,sellPrice:764,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Repair Station Kit',className:'rag_baseitems_repair_station_kit',category:'Furnishings',sellPrice:1144,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Retro Fridge Kit',className:'rag_baseitems_retro_fridge_kit',category:'Furnishings',sellPrice:935,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Roomdivider Beach Kit',className:'rag_baseitems_roomdivider_beach_kit',category:'Furnishings',buyPrice:75835,sellPrice:758,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Sewing Machine Kit',className:'rag_baseitems_sewing_machine_kit',category:'Furnishings',sellPrice:837,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Side Table White Kit',className:'rag_baseitems_side_table_white_kit',category:'Furnishings',buyPrice:76255,sellPrice:763,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Single Locker Kit',className:'rag_baseitems_single_locker_kit',category:'Furnishings',sellPrice:947,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Small Iron Safe Kit',className:'rag_baseitems_small_iron_safe_kit',category:'Furnishings',sellPrice:1125,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Small Pool Blue Kit',className:'rag_baseitems_small_pool_blue_kit',category:'Furnishings',buyPrice:73165,sellPrice:732,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Small Safe Kit',className:'rag_baseitems_small_safe_kit',category:'Furnishings',sellPrice:1087,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Smoker Kit',className:'rag_baseitems_smoker_kit',category:'Furnishings',buyPrice:87645,sellPrice:876,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Sofa Kit',className:'rag_baseitems_sofa_kit',category:'Furnishings',buyPrice:91390,sellPrice:914,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Solarpanel Kit',className:'rag_baseitems_solarpanel_kit',category:'Furnishings',sellPrice:1190,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Table Lamp Oval Kit',className:'rag_baseitems_table_lamp_oval_kit',category:'Furnishings',buyPrice:72485,sellPrice:725,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Table Saw Kit',className:'rag_baseitems_table_saw_kit',category:'Furnishings',sellPrice:1099,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Teddyshelf Kit',className:'rag_baseitems_teddyshelf_kit',category:'Furnishings',buyPrice:75295,sellPrice:753,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Toolbench Kit',className:'rag_baseitems_toolbench_kit',category:'Furnishings',sellPrice:1056,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Tools Drawer Kit',className:'rag_baseitems_tools_drawer_kit',category:'Furnishings',sellPrice:993,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Totem Kit',className:'rag_baseitems_totem_kit',category:'Furnishings',buyPrice:80645,sellPrice:806,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Triple Locker Kit',className:'rag_baseitems_triple_locker_kit',category:'Furnishings',sellPrice:1068,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Tv Vintage Kit',className:'rag_baseitems_tv_vintage_kit',category:'Furnishings',buyPrice:85365,sellPrice:854,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Victorian Table White Kit',className:'rag_baseitems_victorian_table_white_kit',category:'Furnishings',buyPrice:81745,sellPrice:817,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Volleyball Net Kit',className:'rag_baseitems_volleyball_net_kit',category:'Furnishings',buyPrice:73385,sellPrice:734,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Wall Clock Kit',className:'rag_baseitems_wall_clock_kit',category:'Furnishings',buyPrice:74420,sellPrice:744,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Wardrobe Kit',className:'rag_baseitems_wardrobe_kit',category:'Furnishings',sellPrice:959,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Warrior Kit',className:'rag_baseitems_warrior_kit',category:'Furnishings',buyPrice:90165,sellPrice:902,traderSells:true,traderBuys:true},
{name:'Rag Baseitems Weapon Cleaner Kit',className:'rag_baseitems_weapon_cleaner_kit',category:'Furnishings',sellPrice:1043,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Woodenshelf Big Kit',className:'rag_baseitems_woodenshelf_big_kit',category:'Furnishings',sellPrice:918,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Woodenshelf Small Kit',className:'rag_baseitems_woodenshelf_small_kit',category:'Furnishings',sellPrice:855,traderSells:false,traderBuys:true},
{name:'Rag Baseitems Workbench Kit',className:'rag_baseitems_workbench_kit',category:'Furnishings',buyPrice:107540,sellPrice:1075,traderSells:true,traderBuys:true},
{name:'Chemlight Blue',className:'chemlight_blue',category:'Lights',buyPrice:30455,traderSells:true,traderBuys:false},
{name:'Chemlight Green',className:'chemlight_green',category:'Lights',buyPrice:30455,traderSells:true,traderBuys:false},
{name:'Chemlight Red',className:'chemlight_red',category:'Lights',buyPrice:30455,traderSells:true,traderBuys:false},
{name:'Chemlight White',className:'chemlight_white',category:'Lights',buyPrice:30455,traderSells:true,traderBuys:false},
{name:'Chemlight Yellow',className:'chemlight_yellow',category:'Lights',buyPrice:30455,traderSells:true,traderBuys:false},
{name:'Fireworkslauncher',className:'fireworkslauncher',category:'Lights',buyPrice:31375,traderSells:true,traderBuys:false},
{name:'Flashlight',className:'flashlight',category:'Lights',buyPrice:30490,traderSells:true,traderBuys:false},
{name:'Headtorch Black',className:'headtorch_black',category:'Lights',buyPrice:29980,traderSells:true,traderBuys:false},
{name:'Headtorch Grey',className:'headtorch_grey',category:'Lights',buyPrice:29980,traderSells:true,traderBuys:false},
{name:'Matchbox',className:'matchbox',category:'Lights',buyPrice:29705,traderSells:true,traderBuys:false},
{name:'Petrollighter',className:'petrollighter',category:'Lights',buyPrice:30720,traderSells:true,traderBuys:false},
{name:'Portablegaslamp',className:'portablegaslamp',category:'Lights',buyPrice:29600,traderSells:true,traderBuys:false},
{name:'Roadflare',className:'roadflare',category:'Lights',buyPrice:31010,traderSells:true,traderBuys:false},
{name:'Spotlight',className:'spotlight',category:'Lights',buyPrice:29085,traderSells:true,traderBuys:false},
{name:'Tlrlight',className:'tlrlight',category:'Lights',buyPrice:29480,traderSells:true,traderBuys:false},
{name:'Universallight',className:'universallight',category:'Lights',buyPrice:29520,traderSells:true,traderBuys:false},
{name:'Xmaslights',className:'xmaslights',category:'Lights',buyPrice:30505,traderSells:true,traderBuys:false},
{name:'Codelock',className:'codelock',category:'Locks',buyPrice:36555,sellPrice:366,traderSells:true,traderBuys:true},
{name:'Brown Sleeping Bag',className:'lbs_sleepingpacked_old_brown',category:'Sleeping Bags',buyPrice:14045,sellPrice:140,traderSells:true,traderBuys:true},
{name:'Bbp Blueprint',className:'bbp_blueprint',category:'Supplies',buyPrice:79790,traderSells:true,traderBuys:false},
{name:'Bbp Carpet 1',className:'bbp_carpet_1',category:'Supplies',buyPrice:77705,traderSells:true,traderBuys:false},
{name:'Bbp Carpet 2',className:'bbp_carpet_2',category:'Supplies',buyPrice:77705,traderSells:true,traderBuys:false},
{name:'Bbp Cement',className:'bbp_cement',category:'Supplies',buyPrice:78115,traderSells:true,traderBuys:false},
{name:'Bbp Mortar Mix',className:'bbp_mortar_mix',category:'Supplies',buyPrice:76475,traderSells:true,traderBuys:false},
{name:'Bbp Plaster 1',className:'bbp_plaster_1',category:'Supplies',buyPrice:78650,traderSells:true,traderBuys:false},
{name:'Bbp Plaster 2',className:'bbp_plaster_2',category:'Supplies',buyPrice:78650,traderSells:true,traderBuys:false},
{name:'Bbp Tapemeasure',className:'bbp_tapemeasure',category:'Supplies',buyPrice:79450,traderSells:true,traderBuys:false},
{name:'Bbp Wallpaper 1',className:'bbp_wallpaper_1',category:'Supplies',buyPrice:75855,traderSells:true,traderBuys:false},
{name:'Bbp Wallpaper 2',className:'bbp_wallpaper_2',category:'Supplies',buyPrice:75855,traderSells:true,traderBuys:false},
{name:'Bbp Wallpaper Mural 1',className:'bbp_wallpaper_mural_1',category:'Supplies',buyPrice:75105,traderSells:true,traderBuys:false},
{name:'Bbp Wallpaper Mural 2',className:'bbp_wallpaper_mural_2',category:'Supplies',buyPrice:75105,traderSells:true,traderBuys:false},
{name:'Bear Beige',className:'bear_beige',category:'Supplies',buyPrice:78410,traderSells:true,traderBuys:false},
{name:'Bear Dark',className:'bear_dark',category:'Supplies',buyPrice:78410,traderSells:true,traderBuys:false},
{name:'Bear Pink',className:'bear_pink',category:'Supplies',buyPrice:78410,traderSells:true,traderBuys:false},
{name:'Bear White',className:'bear_white',category:'Supplies',buyPrice:78410,traderSells:true,traderBuys:false},
{name:'Camonet',className:'camonet',category:'Supplies',buyPrice:24125,traderSells:true,traderBuys:false},
{name:'Epoxyputty',className:'epoxyputty',category:'Supplies',buyPrice:79415,traderSells:true,traderBuys:false},
{name:'Largegascanister',className:'largegascanister',category:'Supplies',buyPrice:77905,traderSells:true,traderBuys:false},
{name:'Nailbox',className:'nailbox',category:'Supplies',buyPrice:78395,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Cleaning Patches',className:'rag_baseitems_cleaning_patches',category:'Supplies',buyPrice:37250,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Jar',className:'rag_baseitems_coffee_jar',category:'Supplies',buyPrice:78930,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Blue Bar',className:'rag_baseitems_coffee_mug_blue_bar',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Blue Break',className:'rag_baseitems_coffee_mug_blue_break',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Green Bar',className:'rag_baseitems_coffee_mug_green_bar',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Green Break',className:'rag_baseitems_coffee_mug_green_break',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Green Fresh',className:'rag_baseitems_coffee_mug_green_fresh',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Purple Bar',className:'rag_baseitems_coffee_mug_purple_bar',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Purple Break',className:'rag_baseitems_coffee_mug_purple_break',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Rag',className:'rag_baseitems_coffee_mug_rag',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Red Bar',className:'rag_baseitems_coffee_mug_red_bar',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Red Break',className:'rag_baseitems_coffee_mug_red_break',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Yellow Break',className:'rag_baseitems_coffee_mug_yellow_break',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Yellow Fresh',className:'rag_baseitems_coffee_mug_yellow_fresh',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Mug Yellow Shop',className:'rag_baseitems_coffee_mug_yellow_shop',category:'Supplies',buyPrice:75060,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Pack',className:'rag_baseitems_coffee_pack',category:'Supplies',buyPrice:79200,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Coffee Thermos',className:'rag_baseitems_coffee_thermos',category:'Supplies',buyPrice:78225,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Grammophone 2 Disk',className:'rag_baseitems_grammophone_2_disk',category:'Supplies',buyPrice:75230,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Grammophone 3 Disk',className:'rag_baseitems_grammophone_3_disk',category:'Supplies',buyPrice:75230,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Grammophone 4 Disk',className:'rag_baseitems_grammophone_4_disk',category:'Supplies',buyPrice:75230,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Grammophone 5 Disk',className:'rag_baseitems_grammophone_5_disk',category:'Supplies',buyPrice:75230,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Grammophone Disk',className:'rag_baseitems_grammophone_disk',category:'Supplies',buyPrice:75230,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Portafilter',className:'rag_baseitems_portafilter',category:'Supplies',buyPrice:79095,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Sawblade',className:'rag_baseitems_sawblade',category:'Supplies',buyPrice:76775,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Spraycan Paint',className:'rag_baseitems_spraycan_paint',category:'Supplies',buyPrice:75045,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Spraycan White',className:'rag_baseitems_spraycan_white',category:'Supplies',buyPrice:75360,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Weapon Solvent',className:'rag_baseitems_weapon_solvent',category:'Supplies',buyPrice:35000,traderSells:true,traderBuys:false},
{name:'Rag Baseitems Workbench Blueprint',className:'rag_baseitems_workbench_blueprint',category:'Supplies',buyPrice:78795,traderSells:true,traderBuys:false},
{name:'Tripod',className:'tripod',category:'Supplies',buyPrice:78545,traderSells:true,traderBuys:false},
{name:'Cartent',className:'cartent',category:'Tents',sellPrice:1000,traderSells:false,traderBuys:true},
{name:'Largetent',className:'largetent',category:'Tents',sellPrice:756,traderSells:false,traderBuys:true},
{name:'Mediumtent',className:'mediumtent',category:'Tents',sellPrice:253,traderSells:false,traderBuys:true},
{name:'Mediumtent Green',className:'mediumtent_green',category:'Tents',sellPrice:252,traderSells:false,traderBuys:true},
{name:'Mediumtent Orange',className:'mediumtent_orange',category:'Tents',sellPrice:253,traderSells:false,traderBuys:true},
{name:'Partytent',className:'partytent',category:'Tents',sellPrice:443,traderSells:false,traderBuys:true},
{name:'Partytent Blue',className:'partytent_blue',category:'Tents',sellPrice:443,traderSells:false,traderBuys:true},
{name:'Partytent Brown',className:'partytent_brown',category:'Tents',sellPrice:443,traderSells:false,traderBuys:true},
{name:'Partytent Lunapark',className:'partytent_lunapark',category:'Tents',sellPrice:460,traderSells:false,traderBuys:true},
{name:'Territoryflagkit',className:'territoryflagkit',category:'Territory Flagpole',buyPrice:150000,traderSells:true,traderBuys:false},
{name:'Bbp Cement Mixer Kit',className:'bbp_cement_mixer_kit',category:'Tools',buyPrice:52485,traderSells:true,traderBuys:false},
{name:'Canopener',className:'canopener',category:'Tools',buyPrice:49245,traderSells:true,traderBuys:false},
{name:'Farminghoe',className:'farminghoe',category:'Tools',buyPrice:51390,traderSells:true,traderBuys:false},
{name:'Fieldshovel',className:'fieldshovel',category:'Tools',buyPrice:48270,traderSells:true,traderBuys:false},
{name:'Firefighteraxe',className:'firefighteraxe',category:'Tools',buyPrice:49320,traderSells:true,traderBuys:false},
{name:'Fryingpan',className:'fryingpan',category:'Tools',buyPrice:51630,traderSells:true,traderBuys:false},
{name:'Hacksaw',className:'hacksaw',category:'Tools',sellPrice:508,traderSells:false,traderBuys:true},
{name:'Hammer',className:'hammer',category:'Tools',buyPrice:49735,traderSells:true,traderBuys:false},
{name:'Handsaw',className:'handsaw',category:'Tools',buyPrice:48605,traderSells:true,traderBuys:false},
{name:'Hatchet',className:'hatchet',category:'Tools',buyPrice:50270,traderSells:true,traderBuys:false},
{name:'Pickaxe',className:'pickaxe',category:'Tools',sellPrice:485,traderSells:false,traderBuys:true},
{name:'Pitchfork',className:'pitchfork',category:'Tools',buyPrice:50650,traderSells:true,traderBuys:false},
{name:'Pliers',className:'pliers',category:'Tools',buyPrice:50130,traderSells:true,traderBuys:false},
{name:'Portablegasstove',className:'portablegasstove',category:'Tools',buyPrice:30330,traderSells:true,traderBuys:false},
{name:'Screwdriver',className:'screwdriver',category:'Tools',buyPrice:50465,traderSells:true,traderBuys:false},
{name:'Shovel',className:'shovel',category:'Tools',buyPrice:50775,traderSells:true,traderBuys:false},
{name:'Sickle',className:'sickle',category:'Tools',buyPrice:50815,traderSells:true,traderBuys:false},
{name:'Sledgehammer',className:'sledgehammer',category:'Tools',sellPrice:519,traderSells:false,traderBuys:true},
{name:'Woodaxe',className:'woodaxe',category:'Tools',buyPrice:51625,traderSells:true,traderBuys:false},
{name:'Wrench',className:'wrench',category:'Tools',buyPrice:50320,traderSells:true,traderBuys:false}
]};
