window.traderCatalogue={traderName:'Emberline Motors',currency:'ZOMBIE_NOTES',currencyLabel:'Zombie Notes',items:[
{name:'Armada Bearcat',className:'armada_bearcat',category:'Armored Vehicle',buyPrice:24000,traderSells:true,traderBuys:false},
{name:'Armada Bearcat Black',className:'armada_bearcat_black',category:'Armored Vehicle',buyPrice:24000,traderSells:true,traderBuys:false},
{name:'Car Military Big Crate',className:'car_military_big_crate',category:'Car Crates',buyPrice:600,traderSells:true,traderBuys:false},
{name:'Car Military Big Crate Black',className:'car_military_big_crate_black',category:'Car Crates',buyPrice:600,traderSells:true,traderBuys:false},
{name:'Car Military Crate',className:'car_military_crate',category:'Car Crates',buyPrice:400,traderSells:true,traderBuys:false},
{name:'Car Military Crate Black',className:'car_military_crate_black',category:'Car Crates',buyPrice:400,traderSells:true,traderBuys:false},
{name:'Car Military Crate Lila',className:'car_military_crate_lila',category:'Car Crates',buyPrice:400,traderSells:true,traderBuys:false},
{name:'Car Military Crate Red',className:'car_military_crate_red',category:'Car Crates',buyPrice:400,traderSells:true,traderBuys:false},
{name:'Car Military Small Crate',className:'car_military_small_crate',category:'Car Crates',buyPrice:200,traderSells:true,traderBuys:false},
{name:'Car Military Small Crate Black',className:'car_military_small_crate_black',category:'Car Crates',buyPrice:200,traderSells:true,traderBuys:false},
{name:'Camaro',className:'camaro',category:'Muscle',buyPrice:16000,traderSells:true,traderBuys:false},
{name:'Camaro Blue',className:'camaro_blue',category:'Muscle',buyPrice:16000,traderSells:true,traderBuys:false},
{name:'Camaro Red',className:'camaro_red',category:'Muscle',buyPrice:16000,traderSells:true,traderBuys:false},
{name:'Camaro White',className:'camaro_white',category:'Muscle',buyPrice:16000,traderSells:true,traderBuys:false},
{name:'Camaro Yellow',className:'camaro_yellow',category:'Muscle',buyPrice:16000,traderSells:true,traderBuys:false},
{name:'Chevelle1970',className:'chevelle1970',category:'Muscle',buyPrice:11000,traderSells:true,traderBuys:false},
{name:'Chevelle1970 Blue',className:'chevelle1970_blue',category:'Muscle',buyPrice:11000,traderSells:true,traderBuys:false},
{name:'Chevelle1970 Red',className:'chevelle1970_red',category:'Muscle',buyPrice:11000,traderSells:true,traderBuys:false},
{name:'Chevelle1970 White',className:'chevelle1970_white',category:'Muscle',buyPrice:11000,traderSells:true,traderBuys:false},
{name:'Chevelle1970 Yellow',className:'chevelle1970_yellow',category:'Muscle',buyPrice:11000,traderSells:true,traderBuys:false},
{name:'Widebody Hellcat',className:'widebody_hellcat',category:'Muscle',buyPrice:25000,traderSells:true,traderBuys:false},
{name:'Widebody Hellcat Blue',className:'widebody_hellcat_blue',category:'Muscle',buyPrice:25000,traderSells:true,traderBuys:false},
{name:'Widebody Hellcat Red',className:'widebody_hellcat_red',category:'Muscle',buyPrice:25000,traderSells:true,traderBuys:false},
{name:'Widebody Hellcat White',className:'widebody_hellcat_white',category:'Muscle',buyPrice:25000,traderSells:true,traderBuys:false},
{name:'Widebody Hellcat Yellow',className:'widebody_hellcat_yellow',category:'Muscle',buyPrice:25000,traderSells:true,traderBuys:false},
{name:'A M5',className:'a_m5',category:'Sedans',buyPrice:18000,traderSells:true,traderBuys:false},
{name:'A M5 Blue',className:'a_m5_blue',category:'Sedans',buyPrice:18000,traderSells:true,traderBuys:false},
{name:'A M5 Red',className:'a_m5_red',category:'Sedans',buyPrice:18000,traderSells:true,traderBuys:false},
{name:'A M5 White',className:'a_m5_white',category:'Sedans',buyPrice:18000,traderSells:true,traderBuys:false},
{name:'A M5 Yellow',className:'a_m5_yellow',category:'Sedans',buyPrice:18000,traderSells:true,traderBuys:false},
{name:'E60',className:'e60',category:'Sedans',buyPrice:17000,traderSells:true,traderBuys:false},
{name:'E60 Blue',className:'e60_blue',category:'Sedans',buyPrice:17000,traderSells:true,traderBuys:false},
{name:'E60 Red',className:'e60_red',category:'Sedans',buyPrice:17000,traderSells:true,traderBuys:false},
{name:'E60 White',className:'e60_white',category:'Sedans',buyPrice:17000,traderSells:true,traderBuys:false},
{name:'E60 Yellow',className:'e60_yellow',category:'Sedans',buyPrice:17000,traderSells:true,traderBuys:false},
{name:'Gt63',className:'gt63',category:'Sedans',buyPrice:22000,traderSells:true,traderBuys:false},
{name:'Gt63 Blue',className:'gt63_blue',category:'Sedans',buyPrice:22000,traderSells:true,traderBuys:false},
{name:'Gt63 Red',className:'gt63_red',category:'Sedans',buyPrice:22000,traderSells:true,traderBuys:false},
{name:'Gt63 White',className:'gt63_white',category:'Sedans',buyPrice:22000,traderSells:true,traderBuys:false},
{name:'Gt63 Yellow',className:'gt63_yellow',category:'Sedans',buyPrice:22000,traderSells:true,traderBuys:false},
{name:'M3 G80',className:'m3_g80',category:'Sedans',buyPrice:21000,traderSells:true,traderBuys:false},
{name:'M3 G80 Blue',className:'m3_g80_blue',category:'Sedans',buyPrice:21000,traderSells:true,traderBuys:false},
{name:'M3 G80 Police',className:'m3_g80_police',category:'Sedans',buyPrice:21000,traderSells:true,traderBuys:false},
{name:'M3 G80 Police2',className:'m3_g80_police2',category:'Sedans',buyPrice:21000,traderSells:true,traderBuys:false},
{name:'M3 G80 Red',className:'m3_g80_red',category:'Sedans',buyPrice:21000,traderSells:true,traderBuys:false},
{name:'M3 G80 Un',className:'m3_g80_un',category:'Sedans',buyPrice:21000,traderSells:true,traderBuys:false},
{name:'M3 G80 White',className:'m3_g80_white',category:'Sedans',buyPrice:21000,traderSells:true,traderBuys:false},
{name:'M3 G80 Yellow',className:'m3_g80_yellow',category:'Sedans',buyPrice:21000,traderSells:true,traderBuys:false},
{name:'M4w',className:'m4w',category:'Sedans',buyPrice:20000,traderSells:true,traderBuys:false},
{name:'M4w Black',className:'m4w_black',category:'Sedans',buyPrice:20000,traderSells:true,traderBuys:false},
{name:'M4w Blue',className:'m4w_blue',category:'Sedans',buyPrice:20000,traderSells:true,traderBuys:false},
{name:'M4w Red',className:'m4w_red',category:'Sedans',buyPrice:20000,traderSells:true,traderBuys:false},
{name:'M4w White',className:'m4w_white',category:'Sedans',buyPrice:20000,traderSells:true,traderBuys:false},
{name:'M4w Yellow',className:'m4w_yellow',category:'Sedans',buyPrice:20000,traderSells:true,traderBuys:false},
{name:'Mk5',className:'mk5',category:'Sport Cars',buyPrice:12000,traderSells:true,traderBuys:false},
{name:'Mk5 Blue',className:'mk5_blue',category:'Sport Cars',buyPrice:12000,traderSells:true,traderBuys:false},
{name:'Mk5 Red',className:'mk5_red',category:'Sport Cars',buyPrice:12000,traderSells:true,traderBuys:false},
{name:'Mk5 White',className:'mk5_white',category:'Sport Cars',buyPrice:12000,traderSells:true,traderBuys:false},
{name:'Mk5 Yellow',className:'mk5_yellow',category:'Sport Cars',buyPrice:12000,traderSells:true,traderBuys:false},
{name:'Star Audi Rs5',className:'star_audi_rs5',category:'Sport Cars',buyPrice:23000,traderSells:true,traderBuys:false},
{name:'Star Audi Rs5 Blue',className:'star_audi_rs5_blue',category:'Sport Cars',buyPrice:23000,traderSells:true,traderBuys:false},
{name:'Star Audi Rs5 Carbon',className:'star_audi_rs5_carbon',category:'Sport Cars',buyPrice:23000,traderSells:true,traderBuys:false},
{name:'Star Audi Rs5 Orange',className:'star_audi_rs5_orange',category:'Sport Cars',buyPrice:23000,traderSells:true,traderBuys:false},
{name:'Star Audi Rs5 Pink',className:'star_audi_rs5_pink',category:'Sport Cars',buyPrice:23000,traderSells:true,traderBuys:false},
{name:'Star Audi Rs5 Red',className:'star_audi_rs5_red',category:'Sport Cars',buyPrice:23000,traderSells:true,traderBuys:false},
{name:'Star Audi Rs5 Silver',className:'star_audi_rs5_silver',category:'Sport Cars',buyPrice:23000,traderSells:true,traderBuys:false},
{name:'Star Audi Rs5 White',className:'star_audi_rs5_white',category:'Sport Cars',buyPrice:23000,traderSells:true,traderBuys:false},
{name:'Star Audi Rs5 Yellow',className:'star_audi_rs5_yellow',category:'Sport Cars',buyPrice:23000,traderSells:true,traderBuys:false},
{name:'Toyota 86 Rb Black',className:'toyota_86_rb_black',category:'Sport Cars',buyPrice:15000,traderSells:true,traderBuys:false},
{name:'Toyota 86 Rb Green',className:'toyota_86_rb_green',category:'Sport Cars',buyPrice:15000,traderSells:true,traderBuys:false},
{name:'Toyota 86 Rb Lightblue',className:'toyota_86_rb_lightblue',category:'Sport Cars',buyPrice:15000,traderSells:true,traderBuys:false},
{name:'Toyota 86 Rb Red',className:'toyota_86_rb_red',category:'Sport Cars',buyPrice:15000,traderSells:true,traderBuys:false},
{name:'Toyota 86 Rb White',className:'toyota_86_rb_white',category:'Sport Cars',buyPrice:15000,traderSells:true,traderBuys:false},
{name:'Toyota 86 Rb Yellow',className:'toyota_86_rb_yellow',category:'Sport Cars',buyPrice:15000,traderSells:true,traderBuys:false},
{name:'Star Bmw G81',className:'star_bmw_g81',category:'Station Wagon',buyPrice:19000,traderSells:true,traderBuys:false},
{name:'Star Bmw G81 Black',className:'star_bmw_g81_black',category:'Station Wagon',buyPrice:19000,traderSells:true,traderBuys:false},
{name:'Star Bmw G81 Blue',className:'star_bmw_g81_blue',category:'Station Wagon',buyPrice:19000,traderSells:true,traderBuys:false},
{name:'Star Bmw G81 Red',className:'star_bmw_g81_red',category:'Station Wagon',buyPrice:19000,traderSells:true,traderBuys:false},
{name:'Star Bmw G81 Yellow',className:'star_bmw_g81_yellow',category:'Station Wagon',buyPrice:19000,traderSells:true,traderBuys:false},
{name:'Esc',className:'esc',category:'SUV',buyPrice:10000,traderSells:true,traderBuys:false},
{name:'Esc Blue',className:'esc_blue',category:'SUV',buyPrice:10000,traderSells:true,traderBuys:false},
{name:'Esc Red',className:'esc_red',category:'SUV',buyPrice:10000,traderSells:true,traderBuys:false},
{name:'Esc White',className:'esc_white',category:'SUV',buyPrice:10000,traderSells:true,traderBuys:false},
{name:'Esc Yellow',className:'esc_yellow',category:'SUV',buyPrice:10000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71',className:'star_chevrolet_z71',category:'SUV',buyPrice:13000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Blue',className:'star_chevrolet_z71_blue',category:'SUV',buyPrice:13000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Brown',className:'star_chevrolet_z71_brown',category:'SUV',buyPrice:13000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Lifted',className:'star_chevrolet_z71_lifted',category:'SUV',buyPrice:14000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Lifted Blue',className:'star_chevrolet_z71_lifted_blue',category:'SUV',buyPrice:14000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Lifted Brown',className:'star_chevrolet_z71_lifted_brown',category:'SUV',buyPrice:14000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Lifted Orange',className:'star_chevrolet_z71_lifted_orange',category:'SUV',buyPrice:14000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Lifted Pink',className:'star_chevrolet_z71_lifted_pink',category:'SUV',buyPrice:14000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Lifted Red',className:'star_chevrolet_z71_lifted_red',category:'SUV',buyPrice:14000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Lifted White',className:'star_chevrolet_z71_lifted_white',category:'SUV',buyPrice:14000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Lifted Yellow',className:'star_chevrolet_z71_lifted_yellow',category:'SUV',buyPrice:14000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Orange',className:'star_chevrolet_z71_orange',category:'SUV',buyPrice:13000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Pink',className:'star_chevrolet_z71_pink',category:'SUV',buyPrice:13000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Red',className:'star_chevrolet_z71_red',category:'SUV',buyPrice:13000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 White',className:'star_chevrolet_z71_white',category:'SUV',buyPrice:13000,traderSells:true,traderBuys:false},
{name:'Star Chevrolet Z71 Yellow',className:'star_chevrolet_z71_yellow',category:'SUV',buyPrice:13000,traderSells:true,traderBuys:false}
]};
