window.traderCatalogue={traderName:'Peter',currency:'USD',groupCollectableVariants:true,items:[
{name:'Bone',className:'Bone',category:'Animal Byproducts',buyPrice:50,sellPrice:50,traderSells:true,traderBuys:true},
{name:'Lard',className:'Lard',category:'Animal Byproducts',buyPrice:75,sellPrice:75,traderSells:true,traderBuys:true},
{name:'Crossbow Autumn',className:'crossbow_autumn',category:'Crossbows',buyPrice:2000,sellPrice:2000,traderSells:true,traderBuys:true},
{name:'Crossbow Black',className:'crossbow_black',category:'Crossbows',buyPrice:2000,sellPrice:2000,traderSells:true,traderBuys:true},
{name:'Crossbow Summer',className:'crossbow_summer',category:'Crossbows',buyPrice:2000,sellPrice:2000,traderSells:true,traderBuys:true},
{name:'Crossbow Wood',className:'crossbow_wood',category:'Crossbows',buyPrice:2000,sellPrice:2000,traderSells:true,traderBuys:true},
{name:'Headdress Bear',className:'Headdress_Bear',category:'Headdresses',buyPrice:2500,sellPrice:2500,traderSells:true,traderBuys:true},
{name:'Headdress Fox',className:'Headdress_Fox',category:'Headdresses',buyPrice:750,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Headdress Wolf',className:'Headdress_Wolf',category:'Headdresses',buyPrice:1250,sellPrice:1250,traderSells:true,traderBuys:true},
{name:'Head Bear',className:'head_bear',category:'Heads',buyPrice:2344,sellPrice:2344,traderSells:true,traderBuys:true},
{name:'Head Bull',className:'head_bull',category:'Heads',buyPrice:681,sellPrice:681,traderSells:true,traderBuys:true},
{name:'Head Bull Brown',className:'head_bull_brown',category:'Heads',buyPrice:681,sellPrice:681,traderSells:true,traderBuys:true},
{name:'Head Bull Spotted',className:'head_bull_spotted',category:'Heads',buyPrice:681,sellPrice:681,traderSells:true,traderBuys:true},
{name:'Head Bull White',className:'head_bull_white',category:'Heads',buyPrice:681,sellPrice:681,traderSells:true,traderBuys:true},
{name:'Head Deer',className:'head_deer',category:'Heads',buyPrice:781,sellPrice:781,traderSells:true,traderBuys:true},
{name:'Head Fox',className:'head_fox',category:'Heads',buyPrice:494,sellPrice:494,traderSells:true,traderBuys:true},
{name:'Head Goat',className:'head_goat',category:'Heads',buyPrice:594,sellPrice:594,traderSells:true,traderBuys:true},
{name:'Head Goat Black',className:'head_goat_black',category:'Heads',buyPrice:594,sellPrice:594,traderSells:true,traderBuys:true},
{name:'Head Goat Brown',className:'head_goat_brown',category:'Heads',buyPrice:594,sellPrice:594,traderSells:true,traderBuys:true},
{name:'Head Goat Spooky',className:'head_goat_spooky',category:'Heads',buyPrice:594,sellPrice:594,traderSells:true,traderBuys:true},
{name:'Head Goat White',className:'head_goat_white',category:'Heads',buyPrice:594,sellPrice:594,traderSells:true,traderBuys:true},
{name:'Head Pig',className:'head_pig',category:'Heads',buyPrice:569,sellPrice:569,traderSells:true,traderBuys:true},
{name:'Head Reddeer',className:'head_reddeer',category:'Heads',buyPrice:819,sellPrice:819,traderSells:true,traderBuys:true},
{name:'Head Reindeer',className:'head_reindeer',category:'Heads',buyPrice:856,sellPrice:856,traderSells:true,traderBuys:true},
{name:'Head Reindeer Xmas',className:'head_reindeer_xmas',category:'Heads',buyPrice:856,sellPrice:856,traderSells:true,traderBuys:true},
{name:'Head Sheep',className:'head_sheep',category:'Heads',buyPrice:544,sellPrice:544,traderSells:true,traderBuys:true},
{name:'Head Wildboar',className:'head_wildboar',category:'Heads',buyPrice:756,sellPrice:756,traderSells:true,traderBuys:true},
{name:'Head Wolf',className:'head_wolf',category:'Heads',buyPrice:981,sellPrice:981,traderSells:true,traderBuys:true},
{name:'Head Wolf Grey',className:'head_wolf_grey',category:'Heads',buyPrice:981,sellPrice:981,traderSells:true,traderBuys:true},
{name:'Head Wolf White',className:'head_wolf_white',category:'Heads',buyPrice:981,sellPrice:981,traderSells:true,traderBuys:true},
{name:'Fangeknife',className:'fangeknife',category:'Knifes',buyPrice:974,sellPrice:974,traderSells:true,traderBuys:true},
{name:'Huntingknife',className:'huntingknife',category:'Knifes',buyPrice:992,sellPrice:992,traderSells:true,traderBuys:true},
{name:'Bearsteakmeat',className:'bearsteakmeat',category:'Meat',buyPrice:406,sellPrice:406,traderSells:true,traderBuys:true},
{name:'Boarsteakmeat',className:'boarsteakmeat',category:'Meat',buyPrice:269,sellPrice:269,traderSells:true,traderBuys:true},
{name:'Chickenbreastmeat',className:'chickenbreastmeat',category:'Meat',buyPrice:119,sellPrice:119,traderSells:true,traderBuys:true},
{name:'Cowsteakmeat',className:'cowsteakmeat',category:'Meat',buyPrice:194,sellPrice:194,traderSells:true,traderBuys:true},
{name:'Deersteakmeat',className:'deersteakmeat',category:'Meat',buyPrice:306,sellPrice:306,traderSells:true,traderBuys:true},
{name:'Foxsteakmeat',className:'foxsteakmeat',category:'Meat',buyPrice:156,sellPrice:156,traderSells:true,traderBuys:true},
{name:'Goatsteakmeat',className:'goatsteakmeat',category:'Meat',buyPrice:181,sellPrice:181,traderSells:true,traderBuys:true},
{name:'Gold Cow Steak Meat',className:'gold_cow_steak_meat',category:'Meat',buyPrice:1875,sellPrice:1875,traderSells:true,traderBuys:true},
{name:'Humansteakmeat',className:'humansteakmeat',category:'Meat',buyPrice:175,sellPrice:175,traderSells:true,traderBuys:true},
{name:'Mouflonsteakmeat',className:'mouflonsteakmeat',category:'Meat',buyPrice:219,sellPrice:219,traderSells:true,traderBuys:true},
{name:'Pigsteakmeat',className:'pigsteakmeat',category:'Meat',buyPrice:206,sellPrice:206,traderSells:true,traderBuys:true},
{name:'Rabbitlegmeat',className:'rabbitlegmeat',category:'Meat',buyPrice:106,sellPrice:106,traderSells:true,traderBuys:true},
{name:'Reindeersteakmeat',className:'reindeersteakmeat',category:'Meat',buyPrice:319,sellPrice:319,traderSells:true,traderBuys:true},
{name:'Sheepsteakmeat',className:'sheepsteakmeat',category:'Meat',buyPrice:169,sellPrice:169,traderSells:true,traderBuys:true},
{name:'Wolfsteakmeat',className:'wolfsteakmeat',category:'Meat',buyPrice:231,sellPrice:231,traderSells:true,traderBuys:true},
{name:'Bearpelt',className:'bearpelt',category:'Pelts',buyPrice:3731,sellPrice:3731,traderSells:true,traderBuys:true},
{name:'Cj Cowpelt Brown',className:'cj_cowpelt_brown',category:'Pelts',buyPrice:981,sellPrice:981,traderSells:true,traderBuys:true},
{name:'Cj Cowpelt Spotted',className:'cj_cowpelt_spotted',category:'Pelts',buyPrice:981,sellPrice:981,traderSells:true,traderBuys:true},
{name:'Cj Cowpelt White',className:'cj_cowpelt_white',category:'Pelts',buyPrice:981,sellPrice:981,traderSells:true,traderBuys:true},
{name:'Cj Deerpelt Fawn',className:'cj_deerpelt_fawn',category:'Pelts',buyPrice:1931,sellPrice:1931,traderSells:true,traderBuys:true},
{name:'Cj Foxpelt',className:'cj_foxpelt',category:'Pelts',buyPrice:1144,sellPrice:1144,traderSells:true,traderBuys:true},
{name:'Cj Goatpelt Black',className:'cj_goatpelt_black',category:'Pelts',buyPrice:1094,sellPrice:1094,traderSells:true,traderBuys:true},
{name:'Cj Goatpelt Brown',className:'cj_goatpelt_brown',category:'Pelts',buyPrice:1094,sellPrice:1094,traderSells:true,traderBuys:true},
{name:'Cj Goatpelt White',className:'cj_goatpelt_white',category:'Pelts',buyPrice:1094,sellPrice:1094,traderSells:true,traderBuys:true},
{name:'Cj Rabbitpelt Brown',className:'cj_rabbitpelt_brown',category:'Pelts',buyPrice:794,sellPrice:794,traderSells:true,traderBuys:true},
{name:'Cj Wolfpelt Grey',className:'cj_wolfpelt_grey',category:'Pelts',buyPrice:2094,sellPrice:2094,traderSells:true,traderBuys:true},
{name:'Cj Wolfpelt White',className:'cj_wolfpelt_white',category:'Pelts',buyPrice:2094,sellPrice:2094,traderSells:true,traderBuys:true},
{name:'Cowpelt',className:'cowpelt',category:'Pelts',buyPrice:981,sellPrice:981,traderSells:true,traderBuys:true},
{name:'Cowpelt Brown',className:'cowpelt_brown',category:'Pelts',buyPrice:981,sellPrice:981,traderSells:true,traderBuys:true},
{name:'Cowpelt Spotted',className:'cowpelt_spotted',category:'Pelts',buyPrice:981,sellPrice:981,traderSells:true,traderBuys:true},
{name:'Cowpelt White',className:'cowpelt_white',category:'Pelts',buyPrice:981,sellPrice:981,traderSells:true,traderBuys:true},
{name:'Deerpelt',className:'deerpelt',category:'Pelts',buyPrice:1931,sellPrice:1931,traderSells:true,traderBuys:true},
{name:'Foxpelt',className:'foxpelt',category:'Pelts',buyPrice:1144,sellPrice:1144,traderSells:true,traderBuys:true},
{name:'Goatpelt',className:'goatpelt',category:'Pelts',buyPrice:1094,sellPrice:1094,traderSells:true,traderBuys:true},
{name:'Goatpelt Black',className:'goatpelt_black',category:'Pelts',buyPrice:1094,sellPrice:1094,traderSells:true,traderBuys:true},
{name:'Goatpelt Brown',className:'goatpelt_brown',category:'Pelts',buyPrice:1094,sellPrice:1094,traderSells:true,traderBuys:true},
{name:'Goatpelt Spooky',className:'goatpelt_spooky',category:'Pelts',buyPrice:1094,sellPrice:1094,traderSells:true,traderBuys:true},
{name:'Goatpelt White',className:'goatpelt_white',category:'Pelts',buyPrice:1094,sellPrice:1094,traderSells:true,traderBuys:true},
{name:'Gold Bull Pelt',className:'gold_bull_pelt',category:'Pelts',buyPrice:6250,sellPrice:6250,traderSells:true,traderBuys:true},
{name:'Mouflonpelt',className:'mouflonpelt',category:'Pelts',buyPrice:1131,sellPrice:1131,traderSells:true,traderBuys:true},
{name:'Pigpelt',className:'pigpelt',category:'Pelts',buyPrice:1056,sellPrice:1056,traderSells:true,traderBuys:true},
{name:'Rabbitpelt',className:'rabbitpelt',category:'Pelts',buyPrice:794,sellPrice:794,traderSells:true,traderBuys:true},
{name:'Reddeerpelt',className:'reddeerpelt',category:'Pelts',buyPrice:1931,sellPrice:1931,traderSells:true,traderBuys:true},
{name:'Reindeerpelt',className:'reindeerpelt',category:'Pelts',buyPrice:1931,sellPrice:1931,traderSells:true,traderBuys:true},
{name:'Sheeppelt',className:'sheeppelt',category:'Pelts',buyPrice:1069,sellPrice:1069,traderSells:true,traderBuys:true},
{name:'Wildboarpelt',className:'wildboarpelt',category:'Pelts',buyPrice:1844,sellPrice:1844,traderSells:true,traderBuys:true},
{name:'Wolfpelt',className:'wolfpelt',category:'Pelts',buyPrice:2094,sellPrice:2094,traderSells:true,traderBuys:true},
{name:'Wolfpelt Grey',className:'wolfpelt_grey',category:'Pelts',buyPrice:2094,sellPrice:2094,traderSells:true,traderBuys:true},
{name:'Wolfpelt White',className:'wolfpelt_white',category:'Pelts',buyPrice:2094,sellPrice:2094,traderSells:true,traderBuys:true},
{name:'Bearskinrug',className:'bearskinrug',category:'Rugs',buyPrice:1185,sellPrice:1185,traderSells:true,traderBuys:true},
{name:'Cowskinrug Brown',className:'cowskinrug_brown',category:'Rugs',buyPrice:765,sellPrice:765,traderSells:true,traderBuys:true},
{name:'Cowskinrug Spotted',className:'cowskinrug_spotted',category:'Rugs',buyPrice:785,sellPrice:785,traderSells:true,traderBuys:true},
{name:'Cowskinrug White',className:'cowskinrug_white',category:'Rugs',buyPrice:805,sellPrice:805,traderSells:true,traderBuys:true},
{name:'Deerskinrug',className:'deerskinrug',category:'Rugs',buyPrice:885,sellPrice:885,traderSells:true,traderBuys:true},
{name:'Foxskinrug',className:'foxskinrug',category:'Rugs',buyPrice:605,sellPrice:605,traderSells:true,traderBuys:true},
{name:'Goatskinrug Black',className:'goatskinrug_black',category:'Rugs',buyPrice:635,sellPrice:635,traderSells:true,traderBuys:true},
{name:'Goatskinrug Brown',className:'goatskinrug_brown',category:'Rugs',buyPrice:655,sellPrice:655,traderSells:true,traderBuys:true},
{name:'Goatskinrug White',className:'goatskinrug_white',category:'Rugs',buyPrice:675,sellPrice:675,traderSells:true,traderBuys:true},
{name:'Reddeerskinrug',className:'reddeerskinrug',category:'Rugs',buyPrice:915,sellPrice:915,traderSells:true,traderBuys:true},
{name:'Reindeerskinrug',className:'reindeerskinrug',category:'Rugs',buyPrice:945,sellPrice:945,traderSells:true,traderBuys:true},
{name:'Sheepskinrug',className:'sheepskinrug',category:'Rugs',buyPrice:715,sellPrice:715,traderSells:true,traderBuys:true},
{name:'Wildboarskinrug',className:'wildboarskinrug',category:'Rugs',buyPrice:845,sellPrice:845,traderSells:true,traderBuys:true},
{name:'Wolfskinrug',className:'wolfskinrug',category:'Rugs',buyPrice:925,sellPrice:925,traderSells:true,traderBuys:true},
{name:'Wolfskinrug Grey',className:'wolfskinrug_grey',category:'Rugs',buyPrice:955,sellPrice:955,traderSells:true,traderBuys:true},
{name:'Wolfskinrug White',className:'wolfskinrug_white',category:'Rugs',buyPrice:975,sellPrice:975,traderSells:true,traderBuys:true},
{name:'Ammo Huntingbolt',className:'ammo_huntingbolt',category:'Vanilla Ammo',buyPrice:40,sellPrice:40,traderSells:true,traderBuys:true}
]};
