window.traderCatalogue={traderName:'Peter',currency:'USD',groupCollectableVariants:true,items:[
{name:'Hunting Bolt',className:'ammo_huntingbolt',category:'Ammo',buyPrice:27,sellPrice:8,traderSells:true,traderBuys:true},
{name:'Crossbow — Autumn',className:'crossbow_autumn',category:'Crossbows',buyPrice:1050,sellPrice:315,traderSells:true,traderBuys:true},
{name:'Crossbow — Black',className:'crossbow_black',category:'Crossbows',buyPrice:1050,sellPrice:315,traderSells:true,traderBuys:true},
{name:'Crossbow — Summer',className:'crossbow_summer',category:'Crossbows',buyPrice:1050,sellPrice:315,traderSells:true,traderBuys:true},
{name:'Crossbow — Wood',className:'crossbow_wood',category:'Crossbows',buyPrice:1050,sellPrice:315,traderSells:true,traderBuys:true},
{name:'Bear Head',className:'head_bear',category:'Heads',sellPrice:3399,traderSells:false,traderBuys:true},
{name:'Black Goat Head',className:'head_goat_black',category:'Heads',sellPrice:861,traderSells:false,traderBuys:true},
{name:'Brown Bull Head',className:'head_bull_brown',category:'Heads',sellPrice:987,traderSells:false,traderBuys:true},
{name:'Brown Goat Head',className:'head_goat_brown',category:'Heads',sellPrice:861,traderSells:false,traderBuys:true},
{name:'Bull Head',className:'head_bull',category:'Heads',sellPrice:987,traderSells:false,traderBuys:true},
{name:'Christmas Reindeer Head',className:'head_reindeer_xmas',category:'Heads',sellPrice:1241,traderSells:false,traderBuys:true},
{name:'Deer Head',className:'head_deer',category:'Heads',sellPrice:1132,traderSells:false,traderBuys:true},
{name:'Fox Head',className:'head_fox',category:'Heads',sellPrice:716,traderSells:false,traderBuys:true},
{name:'Goat Head',className:'head_goat',category:'Heads',sellPrice:861,traderSells:false,traderBuys:true},
{name:'Grey Wolf Head',className:'head_wolf_grey',category:'Heads',sellPrice:1422,traderSells:false,traderBuys:true},
{name:'Pig Head',className:'head_pig',category:'Heads',sellPrice:825,traderSells:false,traderBuys:true},
{name:'Red Deer Head',className:'head_reddeer',category:'Heads',sellPrice:1188,traderSells:false,traderBuys:true},
{name:'Reindeer Head',className:'head_reindeer',category:'Heads',sellPrice:1241,traderSells:false,traderBuys:true},
{name:'Sheep Head',className:'head_sheep',category:'Heads',sellPrice:789,traderSells:false,traderBuys:true},
{name:'Spooky Goat Head',className:'head_goat_spooky',category:'Heads',sellPrice:861,traderSells:false,traderBuys:true},
{name:'Spotted Bull Head',className:'head_bull_spotted',category:'Heads',sellPrice:987,traderSells:false,traderBuys:true},
{name:'White Bull Head',className:'head_bull_white',category:'Heads',sellPrice:987,traderSells:false,traderBuys:true},
{name:'White Goat Head',className:'head_goat_white',category:'Heads',sellPrice:861,traderSells:false,traderBuys:true},
{name:'White Wolf Head',className:'head_wolf_white',category:'Heads',sellPrice:1422,traderSells:false,traderBuys:true},
{name:'Wild Boar Head',className:'head_wildboar',category:'Heads',sellPrice:1096,traderSells:false,traderBuys:true},
{name:'Wolf Head',className:'head_wolf',category:'Heads',sellPrice:1422,traderSells:false,traderBuys:true},
{name:'Fang Knife',className:'fangeknife',category:'Knives',buyPrice:974,sellPrice:292,traderSells:true,traderBuys:true},
{name:'Hunting Knife',className:'huntingknife',category:'Knives',buyPrice:992,sellPrice:298,traderSells:true,traderBuys:true},
{name:'Bear Steak',className:'bearsteakmeat',category:'Meat',sellPrice:589,traderSells:false,traderBuys:true},
{name:'Boar Steak',className:'boarsteakmeat',category:'Meat',sellPrice:390,traderSells:false,traderBuys:true},
{name:'Chicken Breast',className:'chickenbreastmeat',category:'Meat',sellPrice:173,traderSells:false,traderBuys:true},
{name:'Cow Steak',className:'cowsteakmeat',category:'Meat',sellPrice:281,traderSells:false,traderBuys:true},
{name:'Deer Steak',className:'deersteakmeat',category:'Meat',sellPrice:444,traderSells:false,traderBuys:true},
{name:'Fox Steak',className:'foxsteakmeat',category:'Meat',sellPrice:226,traderSells:false,traderBuys:true},
{name:'Goat Steak',className:'goatsteakmeat',category:'Meat',sellPrice:262,traderSells:false,traderBuys:true},
{name:'Gold Cow Steak',className:'gold_cow_steak_meat',category:'Meat',sellPrice:2719,traderSells:false,traderBuys:true},
{name:'Mouflon Steak',className:'mouflonsteakmeat',category:'Meat',sellPrice:318,traderSells:false,traderBuys:true},
{name:'Pig Steak',className:'pigsteakmeat',category:'Meat',sellPrice:299,traderSells:false,traderBuys:true},
{name:'Rabbit Leg',className:'rabbitlegmeat',category:'Meat',sellPrice:154,traderSells:false,traderBuys:true},
{name:'Reindeer Steak',className:'reindeersteakmeat',category:'Meat',sellPrice:463,traderSells:false,traderBuys:true},
{name:'Sheep Steak',className:'sheepsteakmeat',category:'Meat',sellPrice:245,traderSells:false,traderBuys:true},
{name:'Wolf Steak',className:'wolfsteakmeat',category:'Meat',sellPrice:335,traderSells:false,traderBuys:true},
{name:'Bear Pelt',className:'bearpelt',category:'Pelts',sellPrice:5410,traderSells:false,traderBuys:true},
{name:'Black Goat Pelt',className:'goatpelt_black',category:'Pelts',sellPrice:1586,traderSells:false,traderBuys:true},
{name:'Black Goat Pelt (CJ)',className:'cj_goatpelt_black',category:'Pelts',sellPrice:1586,traderSells:false,traderBuys:true},
{name:'Brown Cow Pelt',className:'cowpelt_brown',category:'Pelts',sellPrice:1422,traderSells:false,traderBuys:true},
{name:'Brown Cow Pelt (CJ)',className:'cj_cowpelt_brown',category:'Pelts',sellPrice:1422,traderSells:false,traderBuys:true},
{name:'Brown Goat Pelt',className:'goatpelt_brown',category:'Pelts',sellPrice:1586,traderSells:false,traderBuys:true},
{name:'Brown Goat Pelt (CJ)',className:'cj_goatpelt_brown',category:'Pelts',sellPrice:1586,traderSells:false,traderBuys:true},
{name:'Brown Rabbit Pelt (CJ)',className:'cj_rabbitpelt_brown',category:'Pelts',sellPrice:1151,traderSells:false,traderBuys:true},
{name:'Cow Pelt',className:'cowpelt',category:'Pelts',sellPrice:1422,traderSells:false,traderBuys:true},
{name:'Deer Pelt',className:'deerpelt',category:'Pelts',sellPrice:2800,traderSells:false,traderBuys:true},
{name:'Fawn Deer Pelt (CJ)',className:'cj_deerpelt_fawn',category:'Pelts',sellPrice:2800,traderSells:false,traderBuys:true},
{name:'Fox Pelt',className:'foxpelt',category:'Pelts',sellPrice:1659,traderSells:false,traderBuys:true},
{name:'Fox Pelt (CJ)',className:'cj_foxpelt',category:'Pelts',sellPrice:1659,traderSells:false,traderBuys:true},
{name:'Goat Pelt',className:'goatpelt',category:'Pelts',sellPrice:1586,traderSells:false,traderBuys:true},
{name:'Gold Bull Pelt',className:'gold_bull_pelt',category:'Pelts',sellPrice:9062,traderSells:false,traderBuys:true},
{name:'Grey Wolf Pelt',className:'wolfpelt_grey',category:'Pelts',sellPrice:3036,traderSells:false,traderBuys:true},
{name:'Grey Wolf Pelt (CJ)',className:'cj_wolfpelt_grey',category:'Pelts',sellPrice:3036,traderSells:false,traderBuys:true},
{name:'Mouflon Pelt',className:'mouflonpelt',category:'Pelts',sellPrice:1640,traderSells:false,traderBuys:true},
{name:'Pig Pelt',className:'pigpelt',category:'Pelts',sellPrice:1531,traderSells:false,traderBuys:true},
{name:'Rabbit Pelt',className:'rabbitpelt',category:'Pelts',sellPrice:1151,traderSells:false,traderBuys:true},
{name:'Red Deer Pelt',className:'reddeerpelt',category:'Pelts',sellPrice:2800,traderSells:false,traderBuys:true},
{name:'Reindeer Pelt',className:'reindeerpelt',category:'Pelts',sellPrice:2800,traderSells:false,traderBuys:true},
{name:'Sheep Pelt',className:'sheeppelt',category:'Pelts',sellPrice:1550,traderSells:false,traderBuys:true},
{name:'Spooky Goat Pelt',className:'goatpelt_spooky',category:'Pelts',sellPrice:1586,traderSells:false,traderBuys:true},
{name:'Spotted Cow Pelt',className:'cowpelt_spotted',category:'Pelts',sellPrice:1422,traderSells:false,traderBuys:true},
{name:'Spotted Cow Pelt (CJ)',className:'cj_cowpelt_spotted',category:'Pelts',sellPrice:1422,traderSells:false,traderBuys:true},
{name:'White Cow Pelt',className:'cowpelt_white',category:'Pelts',sellPrice:1422,traderSells:false,traderBuys:true},
{name:'White Cow Pelt (CJ)',className:'cj_cowpelt_white',category:'Pelts',sellPrice:1422,traderSells:false,traderBuys:true},
{name:'White Goat Pelt',className:'goatpelt_white',category:'Pelts',sellPrice:1586,traderSells:false,traderBuys:true},
{name:'White Goat Pelt (CJ)',className:'cj_goatpelt_white',category:'Pelts',sellPrice:1586,traderSells:false,traderBuys:true},
{name:'White Wolf Pelt',className:'wolfpelt_white',category:'Pelts',sellPrice:3036,traderSells:false,traderBuys:true},
{name:'White Wolf Pelt (CJ)',className:'cj_wolfpelt_white',category:'Pelts',sellPrice:3036,traderSells:false,traderBuys:true},
{name:'Wild Boar Pelt',className:'wildboarpelt',category:'Pelts',sellPrice:2674,traderSells:false,traderBuys:true},
{name:'Wolf Pelt',className:'wolfpelt',category:'Pelts',sellPrice:3036,traderSells:false,traderBuys:true},
{name:'Bear Skin Rug',className:'bearskinrug',category:'Rugs',sellPrice:1718,traderSells:false,traderBuys:true},
{name:'Black Goat Skin Rug',className:'goatskinrug_black',category:'Rugs',sellPrice:921,traderSells:false,traderBuys:true},
{name:'Brown Cow Skin Rug',className:'cowskinrug_brown',category:'Rugs',sellPrice:1109,traderSells:false,traderBuys:true},
{name:'Brown Goat Skin Rug',className:'goatskinrug_brown',category:'Rugs',sellPrice:950,traderSells:false,traderBuys:true},
{name:'Deer Skin Rug',className:'deerskinrug',category:'Rugs',sellPrice:1283,traderSells:false,traderBuys:true},
{name:'Fox Skin Rug',className:'foxskinrug',category:'Rugs',sellPrice:877,traderSells:false,traderBuys:true},
{name:'Grey Wolf Skin Rug',className:'wolfskinrug_grey',category:'Rugs',sellPrice:1385,traderSells:false,traderBuys:true},
{name:'Red Deer Skin Rug',className:'reddeerskinrug',category:'Rugs',sellPrice:1327,traderSells:false,traderBuys:true},
{name:'Reindeer Skin Rug',className:'reindeerskinrug',category:'Rugs',sellPrice:1370,traderSells:false,traderBuys:true},
{name:'Sheep Skin Rug',className:'sheepskinrug',category:'Rugs',sellPrice:1037,traderSells:false,traderBuys:true},
{name:'Spotted Cow Skin Rug',className:'cowskinrug_spotted',category:'Rugs',sellPrice:1138,traderSells:false,traderBuys:true},
{name:'White Cow Skin Rug',className:'cowskinrug_white',category:'Rugs',sellPrice:1167,traderSells:false,traderBuys:true},
{name:'White Goat Skin Rug',className:'goatskinrug_white',category:'Rugs',sellPrice:979,traderSells:false,traderBuys:true},
{name:'White Wolf Skin Rug',className:'wolfskinrug_white',category:'Rugs',sellPrice:1414,traderSells:false,traderBuys:true},
{name:'Wild Boar Skin Rug',className:'wildboarskinrug',category:'Rugs',sellPrice:1225,traderSells:false,traderBuys:true},
{name:'Wolf Skin Rug',className:'wolfskinrug',category:'Rugs',sellPrice:1341,traderSells:false,traderBuys:true}
]};
