window.traderCatalogue={traderName:'Keiko',currency:'USD',groupCollectableVariants:true,items:[
{name:'Carp',className:'carp',category:'Fish',buyPrice:1400,sellPrice:700,traderSells:true,traderBuys:true},
{name:'Mackerel',className:'mackerel',category:'Fish',buyPrice:1400,sellPrice:700,traderSells:true,traderBuys:true},
{name:'Redcaviar',className:'redcaviar',category:'Fish',buyPrice:2500,sellPrice:1250,traderSells:true,traderBuys:true},
{name:'Sardines',className:'sardines',category:'Fish',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Shrimp',className:'shrimp',category:'Fish',buyPrice:1200,sellPrice:600,traderSells:true,traderBuys:true},
{name:'Steelheadtrout',className:'steelheadtrout',category:'Fish',buyPrice:1800,sellPrice:900,traderSells:true,traderBuys:true},
{name:'Walleyepollock',className:'walleyepollock',category:'Fish',buyPrice:1000,sellPrice:500,traderSells:true,traderBuys:true},
{name:'Carpfilletmeat',className:'carpfilletmeat',category:'Fish Meat',buyPrice:120,sellPrice:60,traderSells:true,traderBuys:true},
{name:'Mackerelfilletmeat',className:'mackerelfilletmeat',category:'Fish Meat',buyPrice:125,sellPrice:62,traderSells:true,traderBuys:true},
{name:'Steelheadtroutfilletmeat',className:'steelheadtroutfilletmeat',category:'Fish Meat',buyPrice:160,sellPrice:80,traderSells:true,traderBuys:true},
{name:'Walleyepollockfilletmeat',className:'walleyepollockfilletmeat',category:'Fish Meat',buyPrice:175,sellPrice:88,traderSells:true,traderBuys:true},
{name:'Fishingrod',className:'fishingrod',category:'Fishing Equipment',buyPrice:12000,sellPrice:6000,traderSells:true,traderBuys:true},
{name:'Hook',className:'hook',category:'Fishing Equipment',buyPrice:650,sellPrice:325,traderSells:true,traderBuys:true},
{name:'Jig',className:'jig',category:'Fishing Equipment',buyPrice:1250,sellPrice:625,traderSells:true,traderBuys:true},
{name:'Worm',className:'worm',category:'Fishing Equipment',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Geb Americanlobsterclaw',className:'geb_americanlobsterclaw',category:'Geb\'s Fish Meat',buyPrice:865,sellPrice:432,traderSells:true,traderBuys:true},
{name:'Geb Americanlobstertail',className:'geb_americanlobstertail',category:'Geb\'s Fish Meat',buyPrice:1170,sellPrice:585,traderSells:true,traderBuys:true},
{name:'Geb Angelfishfilletmeat',className:'geb_angelfishfilletmeat',category:'Geb\'s Fish Meat',buyPrice:490,sellPrice:245,traderSells:true,traderBuys:true},
{name:'Geb Angelsharkfilletmeat',className:'geb_angelsharkfilletmeat',category:'Geb\'s Fish Meat',buyPrice:1138,sellPrice:569,traderSells:true,traderBuys:true},
{name:'Geb Asianseabassfilletmeat',className:'geb_asianseabassfilletmeat',category:'Geb\'s Fish Meat',buyPrice:650,sellPrice:325,traderSells:true,traderBuys:true},
{name:'Geb Atlanticbluemarlinfilletmeat',className:'geb_atlanticbluemarlinfilletmeat',category:'Geb\'s Fish Meat',buyPrice:1088,sellPrice:544,traderSells:true,traderBuys:true},
{name:'Geb Atlanticsailfishfilletmeat',className:'geb_atlanticsailfishfilletmeat',category:'Geb\'s Fish Meat',buyPrice:928,sellPrice:464,traderSells:true,traderBuys:true},
{name:'Geb Blackbassfilletmeat',className:'geb_blackbassfilletmeat',category:'Geb\'s Fish Meat',buyPrice:555,sellPrice:278,traderSells:true,traderBuys:true},
{name:'Geb Bluegillfilletmeat',className:'geb_bluegillfilletmeat',category:'Geb\'s Fish Meat',buyPrice:432,sellPrice:216,traderSells:true,traderBuys:true},
{name:'Geb Bluejellyfishfilletmeat',className:'geb_bluejellyfishfilletmeat',category:'Geb\'s Fish Meat',buyPrice:662,sellPrice:331,traderSells:true,traderBuys:true},
{name:'Geb Bluetangfilletmeat',className:'geb_bluetangfilletmeat',category:'Geb\'s Fish Meat',buyPrice:510,sellPrice:255,traderSells:true,traderBuys:true},
{name:'Geb Bonitafilletmeat',className:'geb_bonitafilletmeat',category:'Geb\'s Fish Meat',buyPrice:498,sellPrice:249,traderSells:true,traderBuys:true},
{name:'Geb Bowfinfilletmeat',className:'geb_bowfinfilletmeat',category:'Geb\'s Fish Meat',buyPrice:630,sellPrice:315,traderSells:true,traderBuys:true},
{name:'Geb Brooktroutfilletmeat',className:'geb_brooktroutfilletmeat',category:'Geb\'s Fish Meat',buyPrice:588,sellPrice:294,traderSells:true,traderBuys:true},
{name:'Geb Browntroutfilletmeat',className:'geb_browntroutfilletmeat',category:'Geb\'s Fish Meat',buyPrice:582,sellPrice:291,traderSells:true,traderBuys:true},
{name:'Geb Cherrysalmonfilletmeat',className:'geb_cherrysalmonfilletmeat',category:'Geb\'s Fish Meat',buyPrice:658,sellPrice:329,traderSells:true,traderBuys:true},
{name:'Geb Chinooksalmonfilletmeat',className:'geb_chinooksalmonfilletmeat',category:'Geb\'s Fish Meat',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Geb Cutthroattroutfilletmeat',className:'geb_cutthroattroutfilletmeat',category:'Geb\'s Fish Meat',buyPrice:622,sellPrice:311,traderSells:true,traderBuys:true},
{name:'Geb Europeanlobsterclaw',className:'geb_europeanlobsterclaw',category:'Geb\'s Fish Meat',buyPrice:885,sellPrice:442,traderSells:true,traderBuys:true},
{name:'Geb Europeanlobstertail',className:'geb_europeanlobstertail',category:'Geb\'s Fish Meat',buyPrice:1200,sellPrice:600,traderSells:true,traderBuys:true},
{name:'Geb Fatheadminnowfilletmeat',className:'geb_fatheadminnowfilletmeat',category:'Geb\'s Fish Meat',buyPrice:395,sellPrice:198,traderSells:true,traderBuys:true},
{name:'Geb Flatheadcatfishfilletmeat',className:'geb_flatheadcatfishfilletmeat',category:'Geb\'s Fish Meat',buyPrice:730,sellPrice:365,traderSells:true,traderBuys:true},
{name:'Geb Flatheadmulletfilletmeat',className:'geb_flatheadmulletfilletmeat',category:'Geb\'s Fish Meat',buyPrice:502,sellPrice:251,traderSells:true,traderBuys:true},
{name:'Geb Greatwhitesharkfilletmeat',className:'geb_greatwhitesharkfilletmeat',category:'Geb\'s Fish Meat',buyPrice:1395,sellPrice:698,traderSells:true,traderBuys:true},
{name:'Geb Humpheadwrassefilletmeat',className:'geb_humpheadwrassefilletmeat',category:'Geb\'s Fish Meat',buyPrice:830,sellPrice:415,traderSells:true,traderBuys:true},
{name:'Geb Kingcrablegs',className:'geb_kingcrablegs',category:'Geb\'s Fish Meat',buyPrice:932,sellPrice:466,traderSells:true,traderBuys:true},
{name:'Geb Laketroutfilletmeat',className:'geb_laketroutfilletmeat',category:'Geb\'s Fish Meat',buyPrice:615,sellPrice:308,traderSells:true,traderBuys:true},
{name:'Geb Largeheadhairtailfish',className:'geb_largeheadhairtailfish',category:'Geb\'s Fish Meat',buyPrice:810,sellPrice:405,traderSells:true,traderBuys:true},
{name:'Geb Largeheadhairtailfishfilletmeat',className:'geb_largeheadhairtailfishfilletmeat',category:'Geb\'s Fish Meat',buyPrice:812,sellPrice:406,traderSells:true,traderBuys:true},
{name:'Geb Largemouthbassfilletmeat',className:'geb_largemouthbassfilletmeat',category:'Geb\'s Fish Meat',buyPrice:535,sellPrice:268,traderSells:true,traderBuys:true},
{name:'Geb Leopardsharkfilletmeat',className:'geb_leopardsharkfilletmeat',category:'Geb\'s Fish Meat',buyPrice:960,sellPrice:480,traderSells:true,traderBuys:true},
{name:'Geb Mahimahifilletmeat',className:'geb_mahimahifilletmeat',category:'Geb\'s Fish Meat',buyPrice:785,sellPrice:392,traderSells:true,traderBuys:true},
{name:'Geb Northernpikefilletmeat',className:'geb_northernpikefilletmeat',category:'Geb\'s Fish Meat',buyPrice:602,sellPrice:301,traderSells:true,traderBuys:true},
{name:'Geb Pacificcodfilletmeat',className:'geb_pacificcodfilletmeat',category:'Geb\'s Fish Meat',buyPrice:600,sellPrice:300,traderSells:true,traderBuys:true},
{name:'Geb Rainbowtroutfilletmeat',className:'geb_rainbowtroutfilletmeat',category:'Geb\'s Fish Meat',buyPrice:575,sellPrice:288,traderSells:true,traderBuys:true},
{name:'Geb Redheadcichlidfilletmeat',className:'geb_redheadcichlidfilletmeat',category:'Geb\'s Fish Meat',buyPrice:608,sellPrice:304,traderSells:true,traderBuys:true},
{name:'Geb Roughneckrockfilletmeat',className:'geb_roughneckrockfilletmeat',category:'Geb\'s Fish Meat',buyPrice:618,sellPrice:309,traderSells:true,traderBuys:true},
{name:'Geb Saugerfilletmeat',className:'geb_saugerfilletmeat',category:'Geb\'s Fish Meat',buyPrice:595,sellPrice:298,traderSells:true,traderBuys:true},
{name:'Geb Severumfilletmeat',className:'geb_severumfilletmeat',category:'Geb\'s Fish Meat',buyPrice:642,sellPrice:321,traderSells:true,traderBuys:true},
{name:'Geb Siamesetigerfishfilletmeat',className:'geb_siamesetigerfishfilletmeat',category:'Geb\'s Fish Meat',buyPrice:930,sellPrice:465,traderSells:true,traderBuys:true},
{name:'Geb Slimysculpinfilletmeat',className:'geb_slimysculpinfilletmeat',category:'Geb\'s Fish Meat',buyPrice:635,sellPrice:318,traderSells:true,traderBuys:true},
{name:'Geb Smallmouthbassfilletmeat',className:'geb_smallmouthbassfilletmeat',category:'Geb\'s Fish Meat',buyPrice:542,sellPrice:271,traderSells:true,traderBuys:true},
{name:'Geb Snowcrablegs',className:'geb_snowcrablegs',category:'Geb\'s Fish Meat',buyPrice:905,sellPrice:452,traderSells:true,traderBuys:true},
{name:'Geb Sockeyesalmonfilletmeat',className:'geb_sockeyesalmonfilletmeat',category:'Geb\'s Fish Meat',buyPrice:760,sellPrice:380,traderSells:true,traderBuys:true},
{name:'Geb Sunfishfilletmeat',className:'geb_sunfishfilletmeat',category:'Geb\'s Fish Meat',buyPrice:422,sellPrice:211,traderSells:true,traderBuys:true},
{name:'Geb Walleyefilletmeat',className:'geb_walleyefilletmeat',category:'Geb\'s Fish Meat',buyPrice:570,sellPrice:285,traderSells:true,traderBuys:true},
{name:'Geb Whitebassfilletmeat',className:'geb_whitebassfilletmeat',category:'Geb\'s Fish Meat',buyPrice:548,sellPrice:274,traderSells:true,traderBuys:true},
{name:'Geb Yellowfintunafilletmeat',className:'geb_yellowfintunafilletmeat',category:'Geb\'s Fish Meat',buyPrice:985,sellPrice:492,traderSells:true,traderBuys:true},
{name:'Geb Yellowperchfilletmeat',className:'geb_yellowperchfilletmeat',category:'Geb\'s Fish Meat',buyPrice:430,sellPrice:215,traderSells:true,traderBuys:true},
{name:'Geb Bamboofishingnet',className:'geb_bamboofishingnet',category:'Geb\'s Fishing Supplies',buyPrice:6800,sellPrice:3400,traderSells:true,traderBuys:true},
{name:'Geb Bluefishingrod',className:'geb_bluefishingrod',category:'Geb\'s Fishing Supplies',buyPrice:14750,sellPrice:7375,traderSells:true,traderBuys:true},
{name:'Geb Bluefishknife',className:'geb_bluefishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:2212,traderSells:true,traderBuys:true},
{name:'Geb Bluetackle',className:'geb_bluetackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Browntackle',className:'geb_browntackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Bugcontainer',className:'geb_bugcontainer',category:'Geb\'s Fishing Supplies',buyPrice:650,sellPrice:325,traderSells:true,traderBuys:true},
{name:'Geb Camotackle',className:'geb_camotackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Fieldcricket',className:'geb_fieldcricket',category:'Geb\'s Fishing Supplies',buyPrice:145,sellPrice:72,traderSells:true,traderBuys:true},
{name:'Geb Fishingrodrepairkit',className:'geb_fishingrodrepairkit',category:'Geb\'s Fishing Supplies',buyPrice:4200,sellPrice:2100,traderSells:true,traderBuys:true},
{name:'Geb Fungreentackle',className:'geb_fungreentackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Funpurpletackle',className:'geb_funpurpletackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Funredtackle',className:'geb_funredtackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Funyellowtackle',className:'geb_funyellowtackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Grasshopper',className:'geb_grasshopper',category:'Geb\'s Fishing Supplies',buyPrice:165,sellPrice:82,traderSells:true,traderBuys:true},
{name:'Geb Greenfishingrod',className:'geb_greenfishingrod',category:'Geb\'s Fishing Supplies',buyPrice:14750,sellPrice:7375,traderSells:true,traderBuys:true},
{name:'Geb Greenfishknife',className:'geb_greenfishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:2212,traderSells:true,traderBuys:true},
{name:'Geb Greentackle',className:'geb_greentackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Grubworm',className:'geb_grubworm',category:'Geb\'s Fishing Supplies',buyPrice:185,sellPrice:92,traderSells:true,traderBuys:true},
{name:'Geb Lightbluetackle',className:'geb_lightbluetackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Limetackle',className:'geb_limetackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Lure',className:'geb_lure',category:'Geb\'s Fishing Supplies',buyPrice:1850,sellPrice:925,traderSells:true,traderBuys:true},
{name:'Geb Lure1',className:'geb_lure1',category:'Geb\'s Fishing Supplies',buyPrice:1850,sellPrice:925,traderSells:true,traderBuys:true},
{name:'Geb Lure2',className:'geb_lure2',category:'Geb\'s Fishing Supplies',buyPrice:1850,sellPrice:925,traderSells:true,traderBuys:true},
{name:'Geb Lure3',className:'geb_lure3',category:'Geb\'s Fishing Supplies',buyPrice:1850,sellPrice:925,traderSells:true,traderBuys:true},
{name:'Geb Lure4',className:'geb_lure4',category:'Geb\'s Fishing Supplies',buyPrice:1850,sellPrice:925,traderSells:true,traderBuys:true},
{name:'Geb Minnowbucket',className:'geb_minnowbucket',category:'Geb\'s Fishing Supplies',buyPrice:2400,sellPrice:1200,traderSells:true,traderBuys:true},
{name:'Geb Oldbluetackle',className:'geb_oldbluetackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Oldgreentackle',className:'geb_oldgreentackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Oldpurpletackle',className:'geb_oldpurpletackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Oldredtackle',className:'geb_oldredtackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Oldtacklebase',className:'geb_oldtacklebase',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Orangefishknife',className:'geb_orangefishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:2212,traderSells:true,traderBuys:true},
{name:'Geb Orangetackle',className:'geb_orangetackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Pinktackle',className:'geb_pinktackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Purplefishingrod',className:'geb_purplefishingrod',category:'Geb\'s Fishing Supplies',buyPrice:14750,sellPrice:7375,traderSells:true,traderBuys:true},
{name:'Geb Purplefishknife',className:'geb_purplefishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:2212,traderSells:true,traderBuys:true},
{name:'Geb Purpletackle',className:'geb_purpletackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Redfishingrod',className:'geb_redfishingrod',category:'Geb\'s Fishing Supplies',buyPrice:14750,sellPrice:7375,traderSells:true,traderBuys:true},
{name:'Geb Redfishknife',className:'geb_redfishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:2212,traderSells:true,traderBuys:true},
{name:'Geb Redtackle',className:'geb_redtackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Rubberworm',className:'geb_rubberworm',category:'Geb\'s Fishing Supplies',buyPrice:275,sellPrice:138,traderSells:true,traderBuys:true},
{name:'Geb Smalltackle',className:'geb_smalltackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Spinnerbait1',className:'geb_spinnerbait1',category:'Geb\'s Fishing Supplies',buyPrice:2750,sellPrice:1375,traderSells:true,traderBuys:true},
{name:'Geb Spinnerbait2',className:'geb_spinnerbait2',category:'Geb\'s Fishing Supplies',buyPrice:2750,sellPrice:1375,traderSells:true,traderBuys:true},
{name:'Geb Spinnerbait3',className:'geb_spinnerbait3',category:'Geb\'s Fishing Supplies',buyPrice:2750,sellPrice:1375,traderSells:true,traderBuys:true},
{name:'Geb Spinnerbait4',className:'geb_spinnerbait4',category:'Geb\'s Fishing Supplies',buyPrice:2750,sellPrice:1375,traderSells:true,traderBuys:true},
{name:'Geb Tackle Base',className:'geb_tackle_base',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Wormcontainer',className:'geb_wormcontainer',category:'Geb\'s Fishing Supplies',buyPrice:650,sellPrice:325,traderSells:true,traderBuys:true},
{name:'Geb Yellowfishknife',className:'geb_yellowfishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:2212,traderSells:true,traderBuys:true},
{name:'Geb Yellowtackle',className:'geb_yellowtackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:575,traderSells:true,traderBuys:true},
{name:'Geb Americanlobster',className:'geb_americanlobster',category:'Gebs Fish',buyPrice:6360,sellPrice:3180,traderSells:true,traderBuys:true},
{name:'Geb Angelfish',className:'geb_angelfish',category:'Gebs Fish',buyPrice:2352,sellPrice:1176,traderSells:true,traderBuys:true},
{name:'Geb Angelshark',className:'geb_angelshark',category:'Gebs Fish',buyPrice:7906,sellPrice:3953,traderSells:true,traderBuys:true},
{name:'Geb Asianseabass',className:'geb_asianseabass',category:'Gebs Fish',buyPrice:3390,sellPrice:1695,traderSells:true,traderBuys:true},
{name:'Geb Atlanticbluemarlin',className:'geb_atlanticbluemarlin',category:'Gebs Fish',buyPrice:6798,sellPrice:3399,traderSells:true,traderBuys:true},
{name:'Geb Atlanticsailfish',className:'geb_atlanticsailfish',category:'Gebs Fish',buyPrice:5265,sellPrice:2632,traderSells:true,traderBuys:true},
{name:'Geb Blackbass',className:'geb_blackbass',category:'Gebs Fish',buyPrice:2672,sellPrice:1336,traderSells:true,traderBuys:true},
{name:'Geb Blackdevilsnail',className:'geb_blackdevilsnail',category:'Gebs Fish',buyPrice:2485,sellPrice:1242,traderSells:true,traderBuys:true},
{name:'Geb Bloodclam',className:'geb_bloodclam',category:'Gebs Fish',buyPrice:2165,sellPrice:1082,traderSells:true,traderBuys:true},
{name:'Geb Bluegill',className:'geb_bluegill',category:'Gebs Fish',buyPrice:1935,sellPrice:968,traderSells:true,traderBuys:true},
{name:'Geb Bluejellyfish',className:'geb_bluejellyfish',category:'Gebs Fish',buyPrice:3452,sellPrice:1726,traderSells:true,traderBuys:true},
{name:'Geb Bluetang',className:'geb_bluetang',category:'Gebs Fish',buyPrice:2452,sellPrice:1226,traderSells:true,traderBuys:true},
{name:'Geb Bonita',className:'geb_bonita',category:'Gebs Fish',buyPrice:2390,sellPrice:1195,traderSells:true,traderBuys:true},
{name:'Geb Bowfin',className:'geb_bowfin',category:'Gebs Fish',buyPrice:3278,sellPrice:1639,traderSells:true,traderBuys:true},
{name:'Geb Brooktrout',className:'geb_brooktrout',category:'Gebs Fish',buyPrice:2828,sellPrice:1414,traderSells:true,traderBuys:true},
{name:'Geb Browntrout',className:'geb_browntrout',category:'Gebs Fish',buyPrice:2798,sellPrice:1399,traderSells:true,traderBuys:true},
{name:'Geb Cherrysalmon',className:'geb_cherrysalmon',category:'Gebs Fish',buyPrice:3428,sellPrice:1714,traderSells:true,traderBuys:true},
{name:'Geb Chinooksalmon',className:'geb_chinooksalmon',category:'Gebs Fish',buyPrice:3902,sellPrice:1951,traderSells:true,traderBuys:true},
{name:'Geb Cutthroattrout',className:'geb_cutthroattrout',category:'Gebs Fish',buyPrice:3240,sellPrice:1620,traderSells:true,traderBuys:true},
{name:'Geb Europeancrayfish',className:'geb_europeancrayfish',category:'Gebs Fish',buyPrice:2048,sellPrice:1024,traderSells:true,traderBuys:true},
{name:'Geb Europeanlobster',className:'geb_europeanlobster',category:'Gebs Fish',buyPrice:6515,sellPrice:3258,traderSells:true,traderBuys:true},
{name:'Geb Fatheadminnow',className:'geb_fatheadminnow',category:'Gebs Fish',buyPrice:1765,sellPrice:882,traderSells:true,traderBuys:true},
{name:'Geb Flatheadcatfish',className:'geb_flatheadcatfish',category:'Gebs Fish',buyPrice:3798,sellPrice:1899,traderSells:true,traderBuys:true},
{name:'Geb Flatheadmullet',className:'geb_flatheadmullet',category:'Gebs Fish',buyPrice:2415,sellPrice:1208,traderSells:true,traderBuys:true},
{name:'Geb Greatwhiteshark',className:'geb_greatwhiteshark',category:'Gebs Fish',buyPrice:9688,sellPrice:4844,traderSells:true,traderBuys:true},
{name:'Geb Humpheadwrasse',className:'geb_humpheadwrasse',category:'Gebs Fish',buyPrice:4715,sellPrice:2358,traderSells:true,traderBuys:true},
{name:'Geb Kingcrab',className:'geb_kingcrab',category:'Gebs Fish',buyPrice:6140,sellPrice:3070,traderSells:true,traderBuys:true},
{name:'Geb Laketrout',className:'geb_laketrout',category:'Gebs Fish',buyPrice:3202,sellPrice:1601,traderSells:true,traderBuys:true},
{name:'Geb Largemouthbass',className:'geb_largemouthbass',category:'Gebs Fish',buyPrice:2572,sellPrice:1286,traderSells:true,traderBuys:true},
{name:'Geb Leopardshark',className:'geb_leopardshark',category:'Gebs Fish',buyPrice:5452,sellPrice:2726,traderSells:true,traderBuys:true},
{name:'Geb Mahimahi',className:'geb_mahimahi',category:'Gebs Fish',buyPrice:4452,sellPrice:2226,traderSells:true,traderBuys:true},
{name:'Geb Mussel',className:'geb_mussel',category:'Gebs Fish',buyPrice:2185,sellPrice:1092,traderSells:true,traderBuys:true},
{name:'Geb Northernpike',className:'geb_northernpike',category:'Gebs Fish',buyPrice:3140,sellPrice:1570,traderSells:true,traderBuys:true},
{name:'Geb Pacificcod',className:'geb_pacificcod',category:'Gebs Fish',buyPrice:2890,sellPrice:1445,traderSells:true,traderBuys:true},
{name:'Geb Rainbowtrout',className:'geb_rainbowtrout',category:'Gebs Fish',buyPrice:2765,sellPrice:1382,traderSells:true,traderBuys:true},
{name:'Geb Redheadcichlid',className:'geb_redheadcichlid',category:'Gebs Fish',buyPrice:2922,sellPrice:1461,traderSells:true,traderBuys:true},
{name:'Geb Roughneckrock',className:'geb_roughneckrock',category:'Gebs Fish',buyPrice:2952,sellPrice:1476,traderSells:true,traderBuys:true},
{name:'Geb Sauger',className:'geb_sauger',category:'Gebs Fish',buyPrice:2865,sellPrice:1432,traderSells:true,traderBuys:true},
{name:'Geb Severum',className:'geb_severum',category:'Gebs Fish',buyPrice:3340,sellPrice:1670,traderSells:true,traderBuys:true},
{name:'Geb Siamesetigerfish',className:'geb_siamesetigerfish',category:'Gebs Fish',buyPrice:5798,sellPrice:2899,traderSells:true,traderBuys:true},
{name:'Geb Signalcrayfish',className:'geb_signalcrayfish',category:'Gebs Fish',buyPrice:2028,sellPrice:1014,traderSells:true,traderBuys:true},
{name:'Geb Slimysculpin',className:'geb_slimysculpin',category:'Gebs Fish',buyPrice:3310,sellPrice:1655,traderSells:true,traderBuys:true},
{name:'Geb Smallmouthbass',className:'geb_smallmouthbass',category:'Gebs Fish',buyPrice:2602,sellPrice:1301,traderSells:true,traderBuys:true},
{name:'Geb Snowcrab',className:'geb_snowcrab',category:'Gebs Fish',buyPrice:5952,sellPrice:2976,traderSells:true,traderBuys:true},
{name:'Geb Sockeyesalmon',className:'geb_sockeyesalmon',category:'Gebs Fish',buyPrice:3952,sellPrice:1976,traderSells:true,traderBuys:true},
{name:'Geb Starfish',className:'geb_starfish',category:'Gebs Fish',buyPrice:2515,sellPrice:1258,traderSells:true,traderBuys:true},
{name:'Geb Sunfish',className:'geb_sunfish',category:'Gebs Fish',buyPrice:1890,sellPrice:945,traderSells:true,traderBuys:true},
{name:'Geb Walleye',className:'geb_walleye',category:'Gebs Fish',buyPrice:2740,sellPrice:1370,traderSells:true,traderBuys:true},
{name:'Geb Whitebass',className:'geb_whitebass',category:'Gebs Fish',buyPrice:2635,sellPrice:1318,traderSells:true,traderBuys:true},
{name:'Geb Yellowfintuna',className:'geb_yellowfintuna',category:'Gebs Fish',buyPrice:5590,sellPrice:2795,traderSells:true,traderBuys:true},
{name:'Geb Yellowperch',className:'geb_yellowperch',category:'Gebs Fish',buyPrice:1915,sellPrice:958,traderSells:true,traderBuys:true}
]};
