window.traderCatalogue={traderName:'Keiko',currency:'USD',groupCollectableVariants:true,items:[
{name:'Carp',className:'carp',category:'Fish',sellPrice:1050,traderSells:false,traderBuys:true},
{name:'Mackerel',className:'mackerel',category:'Fish',sellPrice:1052,traderSells:false,traderBuys:true},
{name:'Redcaviar',className:'redcaviar',category:'Fish',sellPrice:1096,traderSells:false,traderBuys:true},
{name:'Sardines',className:'sardines',category:'Fish',sellPrice:1099,traderSells:false,traderBuys:true},
{name:'Shrimp',className:'shrimp',category:'Fish',sellPrice:1101,traderSells:false,traderBuys:true},
{name:'Steelheadtrout',className:'steelheadtrout',category:'Fish',sellPrice:1102,traderSells:false,traderBuys:true},
{name:'Walleyepollock',className:'walleyepollock',category:'Fish',sellPrice:1104,traderSells:false,traderBuys:true},
{name:'Carpfilletmeat',className:'carpfilletmeat',category:'Fish Meat',sellPrice:62,traderSells:false,traderBuys:true},
{name:'Mackerelfilletmeat',className:'mackerelfilletmeat',category:'Fish Meat',sellPrice:62,traderSells:false,traderBuys:true},
{name:'Steelheadtroutfilletmeat',className:'steelheadtroutfilletmeat',category:'Fish Meat',sellPrice:72,traderSells:false,traderBuys:true},
{name:'Walleyepollockfilletmeat',className:'walleyepollockfilletmeat',category:'Fish Meat',sellPrice:73,traderSells:false,traderBuys:true},
{name:'Fishingrod',className:'fishingrod',category:'Fishing Equipment',buyPrice:12000,sellPrice:9000,traderSells:true,traderBuys:true},
{name:'Hook',className:'hook',category:'Fishing Equipment',buyPrice:650,sellPrice:488,traderSells:true,traderBuys:true},
{name:'Jig',className:'jig',category:'Fishing Equipment',buyPrice:1250,sellPrice:938,traderSells:true,traderBuys:true},
{name:'Worm',className:'worm',category:'Fishing Equipment',buyPrice:250,sellPrice:188,traderSells:true,traderBuys:true},
{name:'Geb Americanlobsterclaw',className:'geb_americanlobsterclaw',category:'Geb\'s Fish Meat',sellPrice:649,traderSells:false,traderBuys:true},
{name:'Geb Americanlobstertail',className:'geb_americanlobstertail',category:'Geb\'s Fish Meat',sellPrice:878,traderSells:false,traderBuys:true},
{name:'Geb Angelfishfilletmeat',className:'geb_angelfishfilletmeat',category:'Geb\'s Fish Meat',sellPrice:368,traderSells:false,traderBuys:true},
{name:'Geb Angelsharkfilletmeat',className:'geb_angelsharkfilletmeat',category:'Geb\'s Fish Meat',sellPrice:854,traderSells:false,traderBuys:true},
{name:'Geb Asianseabassfilletmeat',className:'geb_asianseabassfilletmeat',category:'Geb\'s Fish Meat',sellPrice:488,traderSells:false,traderBuys:true},
{name:'Geb Atlanticbluemarlinfilletmeat',className:'geb_atlanticbluemarlinfilletmeat',category:'Geb\'s Fish Meat',sellPrice:816,traderSells:false,traderBuys:true},
{name:'Geb Atlanticsailfishfilletmeat',className:'geb_atlanticsailfishfilletmeat',category:'Geb\'s Fish Meat',sellPrice:696,traderSells:false,traderBuys:true},
{name:'Geb Blackbassfilletmeat',className:'geb_blackbassfilletmeat',category:'Geb\'s Fish Meat',sellPrice:416,traderSells:false,traderBuys:true},
{name:'Geb Bluegillfilletmeat',className:'geb_bluegillfilletmeat',category:'Geb\'s Fish Meat',sellPrice:324,traderSells:false,traderBuys:true},
{name:'Geb Bluejellyfishfilletmeat',className:'geb_bluejellyfishfilletmeat',category:'Geb\'s Fish Meat',sellPrice:496,traderSells:false,traderBuys:true},
{name:'Geb Bluetangfilletmeat',className:'geb_bluetangfilletmeat',category:'Geb\'s Fish Meat',sellPrice:382,traderSells:false,traderBuys:true},
{name:'Geb Bonitafilletmeat',className:'geb_bonitafilletmeat',category:'Geb\'s Fish Meat',sellPrice:374,traderSells:false,traderBuys:true},
{name:'Geb Bowfinfilletmeat',className:'geb_bowfinfilletmeat',category:'Geb\'s Fish Meat',sellPrice:472,traderSells:false,traderBuys:true},
{name:'Geb Brooktroutfilletmeat',className:'geb_brooktroutfilletmeat',category:'Geb\'s Fish Meat',sellPrice:441,traderSells:false,traderBuys:true},
{name:'Geb Browntroutfilletmeat',className:'geb_browntroutfilletmeat',category:'Geb\'s Fish Meat',sellPrice:436,traderSells:false,traderBuys:true},
{name:'Geb Cherrysalmonfilletmeat',className:'geb_cherrysalmonfilletmeat',category:'Geb\'s Fish Meat',sellPrice:494,traderSells:false,traderBuys:true},
{name:'Geb Chinooksalmonfilletmeat',className:'geb_chinooksalmonfilletmeat',category:'Geb\'s Fish Meat',sellPrice:562,traderSells:false,traderBuys:true},
{name:'Geb Cutthroattroutfilletmeat',className:'geb_cutthroattroutfilletmeat',category:'Geb\'s Fish Meat',sellPrice:466,traderSells:false,traderBuys:true},
{name:'Geb Europeanlobsterclaw',className:'geb_europeanlobsterclaw',category:'Geb\'s Fish Meat',sellPrice:664,traderSells:false,traderBuys:true},
{name:'Geb Europeanlobstertail',className:'geb_europeanlobstertail',category:'Geb\'s Fish Meat',sellPrice:900,traderSells:false,traderBuys:true},
{name:'Geb Fatheadminnowfilletmeat',className:'geb_fatheadminnowfilletmeat',category:'Geb\'s Fish Meat',sellPrice:296,traderSells:false,traderBuys:true},
{name:'Geb Flatheadcatfishfilletmeat',className:'geb_flatheadcatfishfilletmeat',category:'Geb\'s Fish Meat',sellPrice:548,traderSells:false,traderBuys:true},
{name:'Geb Flatheadmulletfilletmeat',className:'geb_flatheadmulletfilletmeat',category:'Geb\'s Fish Meat',sellPrice:376,traderSells:false,traderBuys:true},
{name:'Geb Greatwhitesharkfilletmeat',className:'geb_greatwhitesharkfilletmeat',category:'Geb\'s Fish Meat',sellPrice:1046,traderSells:false,traderBuys:true},
{name:'Geb Humpheadwrassefilletmeat',className:'geb_humpheadwrassefilletmeat',category:'Geb\'s Fish Meat',sellPrice:622,traderSells:false,traderBuys:true},
{name:'Geb Kingcrablegs',className:'geb_kingcrablegs',category:'Geb\'s Fish Meat',sellPrice:699,traderSells:false,traderBuys:true},
{name:'Geb Laketroutfilletmeat',className:'geb_laketroutfilletmeat',category:'Geb\'s Fish Meat',sellPrice:461,traderSells:false,traderBuys:true},
{name:'Geb Largeheadhairtailfish',className:'geb_largeheadhairtailfish',category:'Geb\'s Fish Meat',sellPrice:608,traderSells:false,traderBuys:true},
{name:'Geb Largeheadhairtailfishfilletmeat',className:'geb_largeheadhairtailfishfilletmeat',category:'Geb\'s Fish Meat',sellPrice:609,traderSells:false,traderBuys:true},
{name:'Geb Largemouthbassfilletmeat',className:'geb_largemouthbassfilletmeat',category:'Geb\'s Fish Meat',sellPrice:401,traderSells:false,traderBuys:true},
{name:'Geb Leopardsharkfilletmeat',className:'geb_leopardsharkfilletmeat',category:'Geb\'s Fish Meat',sellPrice:720,traderSells:false,traderBuys:true},
{name:'Geb Mahimahifilletmeat',className:'geb_mahimahifilletmeat',category:'Geb\'s Fish Meat',sellPrice:589,traderSells:false,traderBuys:true},
{name:'Geb Northernpikefilletmeat',className:'geb_northernpikefilletmeat',category:'Geb\'s Fish Meat',sellPrice:452,traderSells:false,traderBuys:true},
{name:'Geb Pacificcodfilletmeat',className:'geb_pacificcodfilletmeat',category:'Geb\'s Fish Meat',sellPrice:450,traderSells:false,traderBuys:true},
{name:'Geb Rainbowtroutfilletmeat',className:'geb_rainbowtroutfilletmeat',category:'Geb\'s Fish Meat',sellPrice:431,traderSells:false,traderBuys:true},
{name:'Geb Redheadcichlidfilletmeat',className:'geb_redheadcichlidfilletmeat',category:'Geb\'s Fish Meat',sellPrice:456,traderSells:false,traderBuys:true},
{name:'Geb Roughneckrockfilletmeat',className:'geb_roughneckrockfilletmeat',category:'Geb\'s Fish Meat',sellPrice:464,traderSells:false,traderBuys:true},
{name:'Geb Saugerfilletmeat',className:'geb_saugerfilletmeat',category:'Geb\'s Fish Meat',sellPrice:446,traderSells:false,traderBuys:true},
{name:'Geb Severumfilletmeat',className:'geb_severumfilletmeat',category:'Geb\'s Fish Meat',sellPrice:482,traderSells:false,traderBuys:true},
{name:'Geb Siamesetigerfishfilletmeat',className:'geb_siamesetigerfishfilletmeat',category:'Geb\'s Fish Meat',sellPrice:698,traderSells:false,traderBuys:true},
{name:'Geb Slimysculpinfilletmeat',className:'geb_slimysculpinfilletmeat',category:'Geb\'s Fish Meat',sellPrice:476,traderSells:false,traderBuys:true},
{name:'Geb Smallmouthbassfilletmeat',className:'geb_smallmouthbassfilletmeat',category:'Geb\'s Fish Meat',sellPrice:406,traderSells:false,traderBuys:true},
{name:'Geb Snowcrablegs',className:'geb_snowcrablegs',category:'Geb\'s Fish Meat',sellPrice:679,traderSells:false,traderBuys:true},
{name:'Geb Sockeyesalmonfilletmeat',className:'geb_sockeyesalmonfilletmeat',category:'Geb\'s Fish Meat',sellPrice:570,traderSells:false,traderBuys:true},
{name:'Geb Sunfishfilletmeat',className:'geb_sunfishfilletmeat',category:'Geb\'s Fish Meat',sellPrice:316,traderSells:false,traderBuys:true},
{name:'Geb Walleyefilletmeat',className:'geb_walleyefilletmeat',category:'Geb\'s Fish Meat',sellPrice:428,traderSells:false,traderBuys:true},
{name:'Geb Whitebassfilletmeat',className:'geb_whitebassfilletmeat',category:'Geb\'s Fish Meat',sellPrice:411,traderSells:false,traderBuys:true},
{name:'Geb Yellowfintunafilletmeat',className:'geb_yellowfintunafilletmeat',category:'Geb\'s Fish Meat',sellPrice:739,traderSells:false,traderBuys:true},
{name:'Geb Yellowperchfilletmeat',className:'geb_yellowperchfilletmeat',category:'Geb\'s Fish Meat',sellPrice:322,traderSells:false,traderBuys:true},
{name:'Geb Bamboofishingnet',className:'geb_bamboofishingnet',category:'Geb\'s Fishing Supplies',buyPrice:6800,sellPrice:5100,traderSells:true,traderBuys:true},
{name:'Geb Bluefishingrod',className:'geb_bluefishingrod',category:'Geb\'s Fishing Supplies',buyPrice:14750,sellPrice:11062,traderSells:true,traderBuys:true},
{name:'Geb Bluefishknife',className:'geb_bluefishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:3319,traderSells:true,traderBuys:true},
{name:'Geb Bluetackle',className:'geb_bluetackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Browntackle',className:'geb_browntackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Bugcontainer',className:'geb_bugcontainer',category:'Geb\'s Fishing Supplies',buyPrice:650,sellPrice:0,traderSells:true,traderBuys:true},
{name:'Geb Camotackle',className:'geb_camotackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Fieldcricket',className:'geb_fieldcricket',category:'Geb\'s Fishing Supplies',buyPrice:145,sellPrice:0,traderSells:true,traderBuys:true},
{name:'Geb Fishingrodrepairkit',className:'geb_fishingrodrepairkit',category:'Geb\'s Fishing Supplies',buyPrice:4200,sellPrice:3150,traderSells:true,traderBuys:true},
{name:'Geb Fungreentackle',className:'geb_fungreentackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Funpurpletackle',className:'geb_funpurpletackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Funredtackle',className:'geb_funredtackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Funyellowtackle',className:'geb_funyellowtackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Grasshopper',className:'geb_grasshopper',category:'Geb\'s Fishing Supplies',buyPrice:165,sellPrice:0,traderSells:true,traderBuys:true},
{name:'Geb Greenfishingrod',className:'geb_greenfishingrod',category:'Geb\'s Fishing Supplies',buyPrice:14750,sellPrice:11062,traderSells:true,traderBuys:true},
{name:'Geb Greenfishknife',className:'geb_greenfishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:3319,traderSells:true,traderBuys:true},
{name:'Geb Greentackle',className:'geb_greentackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Grubworm',className:'geb_grubworm',category:'Geb\'s Fishing Supplies',buyPrice:185,sellPrice:0,traderSells:true,traderBuys:true},
{name:'Geb Lightbluetackle',className:'geb_lightbluetackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Limetackle',className:'geb_limetackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Lure',className:'geb_lure',category:'Geb\'s Fishing Supplies',buyPrice:1850,sellPrice:1388,traderSells:true,traderBuys:true},
{name:'Geb Lure1',className:'geb_lure1',category:'Geb\'s Fishing Supplies',buyPrice:1850,sellPrice:1388,traderSells:true,traderBuys:true},
{name:'Geb Lure2',className:'geb_lure2',category:'Geb\'s Fishing Supplies',buyPrice:1850,sellPrice:1388,traderSells:true,traderBuys:true},
{name:'Geb Lure3',className:'geb_lure3',category:'Geb\'s Fishing Supplies',buyPrice:1850,sellPrice:1388,traderSells:true,traderBuys:true},
{name:'Geb Lure4',className:'geb_lure4',category:'Geb\'s Fishing Supplies',buyPrice:1850,sellPrice:1388,traderSells:true,traderBuys:true},
{name:'Geb Minnowbucket',className:'geb_minnowbucket',category:'Geb\'s Fishing Supplies',buyPrice:2400,sellPrice:1800,traderSells:true,traderBuys:true},
{name:'Geb Oldbluetackle',className:'geb_oldbluetackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Oldgreentackle',className:'geb_oldgreentackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Oldpurpletackle',className:'geb_oldpurpletackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Oldredtackle',className:'geb_oldredtackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Oldtacklebase',className:'geb_oldtacklebase',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Orangefishknife',className:'geb_orangefishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:3319,traderSells:true,traderBuys:true},
{name:'Geb Orangetackle',className:'geb_orangetackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Pinktackle',className:'geb_pinktackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Purplefishingrod',className:'geb_purplefishingrod',category:'Geb\'s Fishing Supplies',buyPrice:14750,sellPrice:11062,traderSells:true,traderBuys:true},
{name:'Geb Purplefishknife',className:'geb_purplefishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:3319,traderSells:true,traderBuys:true},
{name:'Geb Purpletackle',className:'geb_purpletackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Redfishingrod',className:'geb_redfishingrod',category:'Geb\'s Fishing Supplies',buyPrice:14750,sellPrice:11062,traderSells:true,traderBuys:true},
{name:'Geb Redfishknife',className:'geb_redfishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:3319,traderSells:true,traderBuys:true},
{name:'Geb Redtackle',className:'geb_redtackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Rubberworm',className:'geb_rubberworm',category:'Geb\'s Fishing Supplies',buyPrice:275,sellPrice:0,traderSells:true,traderBuys:true},
{name:'Geb Smalltackle',className:'geb_smalltackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Spinnerbait1',className:'geb_spinnerbait1',category:'Geb\'s Fishing Supplies',buyPrice:2750,sellPrice:2062,traderSells:true,traderBuys:true},
{name:'Geb Spinnerbait2',className:'geb_spinnerbait2',category:'Geb\'s Fishing Supplies',buyPrice:2750,sellPrice:2062,traderSells:true,traderBuys:true},
{name:'Geb Spinnerbait3',className:'geb_spinnerbait3',category:'Geb\'s Fishing Supplies',buyPrice:2750,sellPrice:2062,traderSells:true,traderBuys:true},
{name:'Geb Spinnerbait4',className:'geb_spinnerbait4',category:'Geb\'s Fishing Supplies',buyPrice:2750,sellPrice:2062,traderSells:true,traderBuys:true},
{name:'Geb Tackle Base',className:'geb_tackle_base',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Wormcontainer',className:'geb_wormcontainer',category:'Geb\'s Fishing Supplies',buyPrice:650,sellPrice:0,traderSells:true,traderBuys:true},
{name:'Geb Yellowfishknife',className:'geb_yellowfishknife',category:'Geb\'s Fishing Supplies',buyPrice:4425,sellPrice:3319,traderSells:true,traderBuys:true},
{name:'Geb Yellowtackle',className:'geb_yellowtackle',category:'Geb\'s Fishing Supplies',buyPrice:1150,sellPrice:862,traderSells:true,traderBuys:true},
{name:'Geb Americanlobster',className:'geb_americanlobster',category:'Gebs Fish',sellPrice:4770,traderSells:false,traderBuys:true},
{name:'Geb Angelfish',className:'geb_angelfish',category:'Gebs Fish',sellPrice:1764,traderSells:false,traderBuys:true},
{name:'Geb Angelshark',className:'geb_angelshark',category:'Gebs Fish',sellPrice:5930,traderSells:false,traderBuys:true},
{name:'Geb Asianseabass',className:'geb_asianseabass',category:'Gebs Fish',sellPrice:2542,traderSells:false,traderBuys:true},
{name:'Geb Atlanticbluemarlin',className:'geb_atlanticbluemarlin',category:'Gebs Fish',sellPrice:5098,traderSells:false,traderBuys:true},
{name:'Geb Atlanticsailfish',className:'geb_atlanticsailfish',category:'Gebs Fish',sellPrice:3949,traderSells:false,traderBuys:true},
{name:'Geb Blackbass',className:'geb_blackbass',category:'Gebs Fish',sellPrice:2004,traderSells:false,traderBuys:true},
{name:'Geb Blackdevilsnail',className:'geb_blackdevilsnail',category:'Gebs Fish',sellPrice:1864,traderSells:false,traderBuys:true},
{name:'Geb Bloodclam',className:'geb_bloodclam',category:'Gebs Fish',sellPrice:1624,traderSells:false,traderBuys:true},
{name:'Geb Bluegill',className:'geb_bluegill',category:'Gebs Fish',sellPrice:1451,traderSells:false,traderBuys:true},
{name:'Geb Bluejellyfish',className:'geb_bluejellyfish',category:'Gebs Fish',sellPrice:2589,traderSells:false,traderBuys:true},
{name:'Geb Bluetang',className:'geb_bluetang',category:'Gebs Fish',sellPrice:1839,traderSells:false,traderBuys:true},
{name:'Geb Bonita',className:'geb_bonita',category:'Gebs Fish',sellPrice:1792,traderSells:false,traderBuys:true},
{name:'Geb Bowfin',className:'geb_bowfin',category:'Gebs Fish',sellPrice:2458,traderSells:false,traderBuys:true},
{name:'Geb Brooktrout',className:'geb_brooktrout',category:'Gebs Fish',sellPrice:2121,traderSells:false,traderBuys:true},
{name:'Geb Browntrout',className:'geb_browntrout',category:'Gebs Fish',sellPrice:2098,traderSells:false,traderBuys:true},
{name:'Geb Cherrysalmon',className:'geb_cherrysalmon',category:'Gebs Fish',sellPrice:2571,traderSells:false,traderBuys:true},
{name:'Geb Chinooksalmon',className:'geb_chinooksalmon',category:'Gebs Fish',sellPrice:2926,traderSells:false,traderBuys:true},
{name:'Geb Cutthroattrout',className:'geb_cutthroattrout',category:'Gebs Fish',sellPrice:2430,traderSells:false,traderBuys:true},
{name:'Geb Europeancrayfish',className:'geb_europeancrayfish',category:'Gebs Fish',sellPrice:1536,traderSells:false,traderBuys:true},
{name:'Geb Europeanlobster',className:'geb_europeanlobster',category:'Gebs Fish',sellPrice:4886,traderSells:false,traderBuys:true},
{name:'Geb Fatheadminnow',className:'geb_fatheadminnow',category:'Gebs Fish',sellPrice:1324,traderSells:false,traderBuys:true},
{name:'Geb Flatheadcatfish',className:'geb_flatheadcatfish',category:'Gebs Fish',sellPrice:2848,traderSells:false,traderBuys:true},
{name:'Geb Flatheadmullet',className:'geb_flatheadmullet',category:'Gebs Fish',sellPrice:1811,traderSells:false,traderBuys:true},
{name:'Geb Greatwhiteshark',className:'geb_greatwhiteshark',category:'Gebs Fish',sellPrice:7266,traderSells:false,traderBuys:true},
{name:'Geb Humpheadwrasse',className:'geb_humpheadwrasse',category:'Gebs Fish',sellPrice:3536,traderSells:false,traderBuys:true},
{name:'Geb Kingcrab',className:'geb_kingcrab',category:'Gebs Fish',sellPrice:4605,traderSells:false,traderBuys:true},
{name:'Geb Laketrout',className:'geb_laketrout',category:'Gebs Fish',sellPrice:2402,traderSells:false,traderBuys:true},
{name:'Geb Largemouthbass',className:'geb_largemouthbass',category:'Gebs Fish',sellPrice:1929,traderSells:false,traderBuys:true},
{name:'Geb Leopardshark',className:'geb_leopardshark',category:'Gebs Fish',sellPrice:4089,traderSells:false,traderBuys:true},
{name:'Geb Mahimahi',className:'geb_mahimahi',category:'Gebs Fish',sellPrice:3339,traderSells:false,traderBuys:true},
{name:'Geb Mussel',className:'geb_mussel',category:'Gebs Fish',sellPrice:1639,traderSells:false,traderBuys:true},
{name:'Geb Northernpike',className:'geb_northernpike',category:'Gebs Fish',sellPrice:2355,traderSells:false,traderBuys:true},
{name:'Geb Pacificcod',className:'geb_pacificcod',category:'Gebs Fish',sellPrice:2168,traderSells:false,traderBuys:true},
{name:'Geb Rainbowtrout',className:'geb_rainbowtrout',category:'Gebs Fish',sellPrice:2074,traderSells:false,traderBuys:true},
{name:'Geb Redheadcichlid',className:'geb_redheadcichlid',category:'Gebs Fish',sellPrice:2192,traderSells:false,traderBuys:true},
{name:'Geb Roughneckrock',className:'geb_roughneckrock',category:'Gebs Fish',sellPrice:2214,traderSells:false,traderBuys:true},
{name:'Geb Sauger',className:'geb_sauger',category:'Gebs Fish',sellPrice:2149,traderSells:false,traderBuys:true},
{name:'Geb Severum',className:'geb_severum',category:'Gebs Fish',sellPrice:2505,traderSells:false,traderBuys:true},
{name:'Geb Siamesetigerfish',className:'geb_siamesetigerfish',category:'Gebs Fish',sellPrice:4348,traderSells:false,traderBuys:true},
{name:'Geb Signalcrayfish',className:'geb_signalcrayfish',category:'Gebs Fish',sellPrice:1521,traderSells:false,traderBuys:true},
{name:'Geb Slimysculpin',className:'geb_slimysculpin',category:'Gebs Fish',sellPrice:2482,traderSells:false,traderBuys:true},
{name:'Geb Smallmouthbass',className:'geb_smallmouthbass',category:'Gebs Fish',sellPrice:1952,traderSells:false,traderBuys:true},
{name:'Geb Snowcrab',className:'geb_snowcrab',category:'Gebs Fish',sellPrice:4464,traderSells:false,traderBuys:true},
{name:'Geb Sockeyesalmon',className:'geb_sockeyesalmon',category:'Gebs Fish',sellPrice:2964,traderSells:false,traderBuys:true},
{name:'Geb Starfish',className:'geb_starfish',category:'Gebs Fish',sellPrice:1886,traderSells:false,traderBuys:true},
{name:'Geb Sunfish',className:'geb_sunfish',category:'Gebs Fish',sellPrice:1418,traderSells:false,traderBuys:true},
{name:'Geb Walleye',className:'geb_walleye',category:'Gebs Fish',sellPrice:2055,traderSells:false,traderBuys:true},
{name:'Geb Whitebass',className:'geb_whitebass',category:'Gebs Fish',sellPrice:1976,traderSells:false,traderBuys:true},
{name:'Geb Yellowfintuna',className:'geb_yellowfintuna',category:'Gebs Fish',sellPrice:4192,traderSells:false,traderBuys:true},
{name:'Geb Yellowperch',className:'geb_yellowperch',category:'Gebs Fish',sellPrice:1436,traderSells:false,traderBuys:true}
]};
