window.traderCatalogue={traderName:'Naomi',currency:'USD',items:[
{name:'Loner Can Empty',className:'loner_can_empty',category:'Cans',mode:'buy',price:300,buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Loner Can Small Empty',className:'loner_can_small_empty',category:'Cans',mode:'sell',price:250,buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Expansionmilkbottle',className:'expansionmilkbottle',category:'Drinks',mode:'sell',price:9845,buyPrice:9845,sellPrice:4922,traderSells:true,traderBuys:true},
{name:'Sodacan Cola',className:'sodacan_cola',category:'Drinks',mode:'sell',price:9955,buyPrice:9955,sellPrice:4978,traderSells:true,traderBuys:true},
{name:'Sodacan Fronta',className:'sodacan_fronta',category:'Drinks',mode:'sell',price:10040,buyPrice:10040,sellPrice:5020,traderSells:true,traderBuys:true},
{name:'Sodacan Kvass',className:'sodacan_kvass',category:'Drinks',mode:'sell',price:9860,buyPrice:9860,sellPrice:4930,traderSells:true,traderBuys:true},
{name:'Sodacan Pipsi',className:'sodacan_pipsi',category:'Drinks',mode:'sell',price:10165,buyPrice:10165,sellPrice:5082,traderSells:true,traderBuys:true},
{name:'Sodacan Spite',className:'sodacan_spite',category:'Drinks',mode:'sell',price:9780,buyPrice:9780,sellPrice:4890,traderSells:true,traderBuys:true},
{name:'Waterbottle',className:'waterbottle',category:'Drinks',mode:'sell',price:10310,buyPrice:10310,sellPrice:5155,traderSells:true,traderBuys:true},
{name:'Bakedbeanscan',className:'bakedbeanscan',category:'Food',mode:'sell',price:9965,buyPrice:9965,sellPrice:4982,traderSells:true,traderBuys:true},
{name:'Boxcerealcrunchin',className:'boxcerealcrunchin',category:'Food',mode:'sell',price:10140,buyPrice:10140,sellPrice:5070,traderSells:true,traderBuys:true},
{name:'Brisketspread',className:'brisketspread',category:'Food',mode:'sell',price:10055,buyPrice:10055,sellPrice:5028,traderSells:true,traderBuys:true},
{name:'Catfoodcan',className:'catfoodcan',category:'Food',mode:'sell',price:9885,buyPrice:9885,sellPrice:4942,traderSells:true,traderBuys:true},
{name:'Chips',className:'chips',category:'Food',mode:'sell',price:9715,buyPrice:9715,sellPrice:4858,traderSells:true,traderBuys:true},
{name:'Crabcan',className:'crabcan',category:'Food',mode:'sell',price:10285,buyPrice:10285,sellPrice:5142,traderSells:true,traderBuys:true},
{name:'Crackers',className:'crackers',category:'Food',mode:'sell',price:9830,buyPrice:9830,sellPrice:4915,traderSells:true,traderBuys:true},
{name:'Dogfoodcan',className:'dogfoodcan',category:'Food',mode:'sell',price:9905,buyPrice:9905,sellPrice:4952,traderSells:true,traderBuys:true},
{name:'Honey',className:'honey',category:'Food',mode:'sell',price:10310,buyPrice:10310,sellPrice:5155,traderSells:true,traderBuys:true},
{name:'Lunchmeat',className:'lunchmeat',category:'Food',mode:'sell',price:10020,buyPrice:10020,sellPrice:5010,traderSells:true,traderBuys:true},
{name:'Marmalade',className:'marmalade',category:'Food',mode:'sell',price:9975,buyPrice:9975,sellPrice:4988,traderSells:true,traderBuys:true},
{name:'Pajka',className:'pajka',category:'Food',mode:'sell',price:10345,buyPrice:10345,sellPrice:5172,traderSells:true,traderBuys:true},
{name:'Pate',className:'pate',category:'Food',mode:'sell',price:9945,buyPrice:9945,sellPrice:4972,traderSells:true,traderBuys:true},
{name:'Peachescan',className:'peachescan',category:'Food',mode:'sell',price:10080,buyPrice:10080,sellPrice:5040,traderSells:true,traderBuys:true},
{name:'Porkcan',className:'porkcan',category:'Food',mode:'sell',price:10165,buyPrice:10165,sellPrice:5082,traderSells:true,traderBuys:true},
{name:'Powderedmilk',className:'powderedmilk',category:'Food',mode:'sell',price:9995,buyPrice:9995,sellPrice:4998,traderSells:true,traderBuys:true},
{name:'Rice',className:'rice',category:'Food',mode:'sell',price:9860,buyPrice:9860,sellPrice:4930,traderSells:true,traderBuys:true},
{name:'Saltysticks',className:'saltysticks',category:'Food',mode:'sell',price:9745,buyPrice:9745,sellPrice:4872,traderSells:true,traderBuys:true},
{name:'Sardinescan',className:'sardinescan',category:'Food',mode:'sell',price:9915,buyPrice:9915,sellPrice:4958,traderSells:true,traderBuys:true},
{name:'Spaghettican',className:'spaghettican',category:'Food',mode:'sell',price:10110,buyPrice:10110,sellPrice:5055,traderSells:true,traderBuys:true},
{name:'Tacticalbaconcan',className:'tacticalbaconcan',category:'Food',mode:'sell',price:10395,buyPrice:10395,sellPrice:5198,traderSells:true,traderBuys:true},
{name:'Tunacan',className:'tunacan',category:'Food',mode:'sell',price:9935,buyPrice:9935,sellPrice:4968,traderSells:true,traderBuys:true},
{name:'Unknownfoodcan',className:'unknownfoodcan',category:'Food',mode:'sell',price:9780,buyPrice:9780,sellPrice:4890,traderSells:true,traderBuys:true},
{name:'Zagorky',className:'zagorky',category:'Food',mode:'sell',price:9755,buyPrice:9755,sellPrice:4878,traderSells:true,traderBuys:true},
{name:'Zagorkychocolate',className:'zagorkychocolate',category:'Food',mode:'sell',price:9815,buyPrice:9815,sellPrice:4908,traderSells:true,traderBuys:true},
{name:'Zagorkypeanuts',className:'zagorkypeanuts',category:'Food',mode:'sell',price:9870,buyPrice:9870,sellPrice:4935,traderSells:true,traderBuys:true},
{name:'Agaricusmushroom',className:'agaricusmushroom',category:'Fruit And Vegetables',mode:'sell',price:150,buyPrice:150,sellPrice:75,traderSells:true,traderBuys:true},
{name:'Apple',className:'apple',category:'Fruit And Vegetables',mode:'sell',price:150,buyPrice:150,sellPrice:75,traderSells:true,traderBuys:true},
{name:'Auriculariamushroom',className:'auriculariamushroom',category:'Fruit And Vegetables',mode:'sell',price:150,buyPrice:150,sellPrice:75,traderSells:true,traderBuys:true},
{name:'Boletusmushroom',className:'boletusmushroom',category:'Fruit And Vegetables',mode:'sell',price:150,buyPrice:150,sellPrice:75,traderSells:true,traderBuys:true},
{name:'Craterellusmushroom',className:'craterellusmushroom',category:'Fruit And Vegetables',mode:'sell',price:1200,buyPrice:1200,sellPrice:600,traderSells:true,traderBuys:true},
{name:'Greenbellpepper',className:'greenbellpepper',category:'Fruit And Vegetables',mode:'sell',price:800,buyPrice:800,sellPrice:400,traderSells:true,traderBuys:true},
{name:'Lactariusmushroom',className:'lactariusmushroom',category:'Fruit And Vegetables',mode:'sell',price:150,buyPrice:150,sellPrice:75,traderSells:true,traderBuys:true},
{name:'Macrolepiotamushroom',className:'macrolepiotamushroom',category:'Fruit And Vegetables',mode:'sell',price:150,buyPrice:150,sellPrice:75,traderSells:true,traderBuys:true},
{name:'Pear',className:'pear',category:'Fruit And Vegetables',mode:'sell',price:150,buyPrice:150,sellPrice:75,traderSells:true,traderBuys:true},
{name:'Pleurotusmushroom',className:'pleurotusmushroom',category:'Fruit And Vegetables',mode:'sell',price:150,buyPrice:150,sellPrice:75,traderSells:true,traderBuys:true},
{name:'Plum',className:'plum',category:'Fruit And Vegetables',mode:'sell',price:150,buyPrice:150,sellPrice:75,traderSells:true,traderBuys:true},
{name:'Potato',className:'potato',category:'Fruit And Vegetables',mode:'sell',price:600,buyPrice:600,sellPrice:300,traderSells:true,traderBuys:true},
{name:'Potatoseed',className:'potatoseed',category:'Fruit And Vegetables',mode:'sell',price:600,buyPrice:600,sellPrice:300,traderSells:true,traderBuys:true},
{name:'Pumpkin',className:'pumpkin',category:'Fruit And Vegetables',mode:'sell',price:500,buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Slicedpumpkin',className:'slicedpumpkin',category:'Fruit And Vegetables',mode:'sell',price:250,buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Tomato',className:'tomato',category:'Fruit And Vegetables',mode:'buy',price:200,buyPrice:200,sellPrice:100,traderSells:true,traderBuys:true},
{name:'Zucchini',className:'zucchini',category:'Fruit And Vegetables',mode:'sell',price:900,buyPrice:900,sellPrice:450,traderSells:true,traderBuys:true},
{name:'Gardenlime',className:'gardenlime',category:'Gardening',mode:'sell',price:4000,buyPrice:4000,sellPrice:2000,traderSells:true,traderBuys:true},
{name:'Pepperseedspack',className:'pepperseedspack',category:'Gardening',mode:'sell',price:2000,buyPrice:2000,sellPrice:1000,traderSells:true,traderBuys:true},
{name:'Pumpkinseedspack',className:'pumpkinseedspack',category:'Gardening',mode:'sell',price:2000,buyPrice:2000,sellPrice:1000,traderSells:true,traderBuys:true},
{name:'Tomatoseedspack',className:'tomatoseedspack',category:'Gardening',mode:'sell',price:2000,buyPrice:2000,sellPrice:1000,traderSells:true,traderBuys:true},
{name:'Zucchiniseedspack',className:'zucchiniseedspack',category:'Gardening',mode:'sell',price:2000,buyPrice:2000,sellPrice:1000,traderSells:true,traderBuys:true}
]};
