window.traderCatalogue={traderName:'Naomi',currency:'USD',inheritedCategoryBuyback:true,inheritedSellPercent:50,buybackExcludedCategories:['Gardening'],items:[
{name:'Baked Beans',className:'bakedbeanscan',category:'Food',mode:'sell',price:9965},
{name:'Brisket Spread',className:'brisketspread',category:'Food',mode:'sell',price:10055},
{name:'Canned Peaches',className:'peachescan',category:'Food',mode:'sell',price:10080},
{name:'Canned Pork',className:'porkcan',category:'Food',mode:'sell',price:10165},
{name:'Canned Sardines',className:'sardinescan',category:'Food',mode:'sell',price:9915},
{name:'Canned Spaghetti',className:'spaghettican',category:'Food',mode:'sell',price:10110},
{name:'Canned Tuna',className:'tunacan',category:'Food',mode:'sell',price:9935},
{name:'Cat Food',className:'catfoodcan',category:'Food',mode:'sell',price:9885},
{name:'Chips',className:'chips',category:'Food',mode:'sell',price:9715},
{name:'Crab Can',className:'crabcan',category:'Food',mode:'sell',price:10285},
{name:'Crackers',className:'crackers',category:'Food',mode:'sell',price:9830},
{name:'Crunchin Cereal',className:'boxcerealcrunchin',category:'Food',mode:'sell',price:10140},
{name:'Dog Food',className:'dogfoodcan',category:'Food',mode:'sell',price:9905},
{name:'Honey',className:'honey',category:'Food',mode:'sell',price:10310},
{name:'Lunch Meat',className:'lunchmeat',category:'Food',mode:'sell',price:10020},
{name:'Marmalade',className:'marmalade',category:'Food',mode:'sell',price:9975},
{name:'Pajka',className:'pajka',category:'Food',mode:'sell',price:10345},
{name:'Powdered Milk',className:'powderedmilk',category:'Food',mode:'sell',price:9995},
{name:'Pâté',className:'pate',category:'Food',mode:'sell',price:9945},
{name:'Rice',className:'rice',category:'Food',mode:'sell',price:9860},
{name:'Salty Sticks',className:'saltysticks',category:'Food',mode:'sell',price:9745},
{name:'Tactical Bacon',className:'tacticalbaconcan',category:'Food',mode:'sell',price:10395},
{name:'Unknown Food Can',className:'unknownfoodcan',category:'Food',mode:'sell',price:9780},
{name:'Zagorky',className:'zagorky',category:'Food',mode:'sell',price:9755},
{name:'Zagorky Chocolate',className:'zagorkychocolate',category:'Food',mode:'sell',price:9815},
{name:'Zagorky Peanuts',className:'zagorkypeanuts',category:'Food',mode:'sell',price:9870},
{name:'Cola',className:'sodacan_cola',category:'Drinks',mode:'sell',price:9955},
{name:'Kvass',className:'sodacan_kvass',category:'Drinks',mode:'sell',price:9860},
{name:'Milk Bottle',className:'expansionmilkbottle',category:'Drinks',mode:'sell',price:9845},
{name:'NotaCola',className:'sodacan_fronta',category:'Drinks',mode:'sell',price:10040},
{name:'Pipsi',className:'sodacan_pipsi',category:'Drinks',mode:'sell',price:10165},
{name:'Spite',className:'sodacan_spite',category:'Drinks',mode:'sell',price:9780},
{name:'Water Bottle',className:'waterbottle',category:'Drinks',mode:'sell',price:10310},
{name:'Empty Can',className:'loner_can_empty',category:'Cans',mode:'sell',price:300},
{name:'Small Empty Can',className:'loner_can_small_empty',category:'Cans',mode:'sell',price:250},
{name:'Agaricusmushroom',className:'agaricusmushroom',category:'Fruit And Vegetables',mode:'sell',price:150},
{name:'Apple',className:'apple',category:'Fruit And Vegetables',mode:'sell',price:150},
{name:'Auriculariamushroom',className:'auriculariamushroom',category:'Fruit And Vegetables',mode:'sell',price:150},
{name:'Boletusmushroom',className:'boletusmushroom',category:'Fruit And Vegetables',mode:'sell',price:150},
{name:'Craterellusmushroom',className:'craterellusmushroom',category:'Fruit And Vegetables',mode:'sell',price:1200},
{name:'Greenbellpepper',className:'greenbellpepper',category:'Fruit And Vegetables',mode:'sell',price:800},
{name:'Lactariusmushroom',className:'lactariusmushroom',category:'Fruit And Vegetables',mode:'sell',price:150},
{name:'Macrolepiotamushroom',className:'macrolepiotamushroom',category:'Fruit And Vegetables',mode:'sell',price:150},
{name:'Pear',className:'pear',category:'Fruit And Vegetables',mode:'sell',price:150},
{name:'Pleurotusmushroom',className:'pleurotusmushroom',category:'Fruit And Vegetables',mode:'sell',price:150},
{name:'Plum',className:'plum',category:'Fruit And Vegetables',mode:'sell',price:150},
{name:'Potato',className:'potato',category:'Fruit And Vegetables',mode:'sell',price:600},
{name:'Potatoseed',className:'potatoseed',category:'Fruit And Vegetables',mode:'sell',price:600},
{name:'Pumpkin',className:'pumpkin',category:'Fruit And Vegetables',mode:'sell',price:500},
{name:'Slicedpumpkin',className:'slicedpumpkin',category:'Fruit And Vegetables',mode:'sell',price:250},
{name:'Tomato',className:'tomato',category:'Fruit And Vegetables',mode:'sell',price:200},
{name:'Zucchini',className:'zucchini',category:'Fruit And Vegetables',mode:'sell',price:900},
{name:'Gardenlime',className:'gardenlime',category:'Gardening',mode:'sell',price:35955},
{name:'Pepperseedspack',className:'pepperseedspack',category:'Gardening',mode:'sell',price:35355},
{name:'Pumpkinseedspack',className:'pumpkinseedspack',category:'Gardening',mode:'sell',price:34600},
{name:'Tomatoseedspack',className:'tomatoseedspack',category:'Gardening',mode:'sell',price:34670},
{name:'Zucchiniseedspack',className:'zucchiniseedspack',category:'Gardening',mode:'sell',price:34140}
]};
