window.traderCatalogue={traderName:'Naomi',currency:'USD',items:[
{name:'Baked Beans',className:'bakedbeanscan',category:'Food',mode:'sell',price:9965},
{name:'Crunchin Cereal',className:'boxcerealcrunchin',category:'Food',mode:'sell',price:10140},
{name:'Brisket Spread',className:'brisketspread',category:'Food',mode:'sell',price:10055},
{name:'Cat Food',className:'catfoodcan',category:'Food',mode:'sell',price:9885},
{name:'Chips',className:'chips',category:'Food',mode:'sell',price:9715},
{name:'Crab Can',className:'crabcan',category:'Food',mode:'sell',price:10285},
{name:'Crackers',className:'crackers',category:'Food',mode:'sell',price:9830},
{name:'Dog Food',className:'dogfoodcan',category:'Food',mode:'sell',price:9905},
{name:'Honey',className:'honey',category:'Food',mode:'sell',price:10310},
{name:'Lunch Meat',className:'lunchmeat',category:'Food',mode:'sell',price:10020},
{name:'Marmalade',className:'marmalade',category:'Food',mode:'sell',price:9975},
{name:'Pajka',className:'pajka',category:'Food',mode:'sell',price:10345},
{name:'Pâté',className:'pate',category:'Food',mode:'sell',price:9945},
{name:'Canned Peaches',className:'peachescan',category:'Food',mode:'sell',price:10080},
{name:'Canned Pork',className:'porkcan',category:'Food',mode:'sell',price:10165},
{name:'Powdered Milk',className:'powderedmilk',category:'Food',mode:'sell',price:9995},
{name:'Rice',className:'rice',category:'Food',mode:'sell',price:9860},
{name:'Salty Sticks',className:'saltysticks',category:'Food',mode:'sell',price:9745},
{name:'Canned Sardines',className:'sardinescan',category:'Food',mode:'sell',price:9915},
{name:'Canned Spaghetti',className:'spaghettican',category:'Food',mode:'sell',price:10110},
{name:'Tactical Bacon',className:'tacticalbaconcan',category:'Food',mode:'sell',price:10395},
{name:'Canned Tuna',className:'tunacan',category:'Food',mode:'sell',price:9935},
{name:'Unknown Food Can',className:'unknownfoodcan',category:'Food',mode:'sell',price:9780},
{name:'Zagorky',className:'zagorky',category:'Food',mode:'sell',price:9755},
{name:'Zagorky Chocolate',className:'zagorkychocolate',category:'Food',mode:'sell',price:9815},
{name:'Zagorky Peanuts',className:'zagorkypeanuts',category:'Food',mode:'sell',price:9870},
{name:'Milk Bottle',className:'expansionmilkbottle',category:'Drinks',mode:'sell',price:9845},
{name:'Cola',className:'sodacan_cola',category:'Drinks',mode:'sell',price:9955},
{name:'NotaCola',className:'sodacan_fronta',category:'Drinks',mode:'sell',price:10040},
{name:'Kvass',className:'sodacan_kvass',category:'Drinks',mode:'sell',price:9860},
{name:'Pipsi',className:'sodacan_pipsi',category:'Drinks',mode:'sell',price:10165},
{name:'Spite',className:'sodacan_spite',category:'Drinks',mode:'sell',price:9780},
{name:'Water Bottle',className:'waterbottle',category:'Drinks',mode:'sell',price:10310},
{name:'Empty Can',className:'loner_can_empty',category:'Cans',mode:'sell',price:300},
{name:'Small Empty Can',className:'loner_can_small_empty',category:'Cans',mode:'sell',price:250},
{name:'Garden Lime',className:'gardenlime',category:'Gardening',mode:'buy',price:35955},
{name:'Pepper Seeds Pack',className:'pepperseedspack',category:'Gardening',mode:'buy',price:35355},
{name:'Pumpkin Seeds Pack',className:'pumpkinseedspack',category:'Gardening',mode:'buy',price:34600},
{name:'Tomato Seeds Pack',className:'tomatoseedspack',category:'Gardening',mode:'buy',price:34670},
{name:'Zucchini Seeds Pack',className:'zucchiniseedspack',category:'Gardening',mode:'buy',price:34140}
]};