window.traderCatalogue={traderName:'Mining Trader',currency:'USD',items:[
{name:'Freezebar Adamantite',className:'freezebar_adamantite',category:'Bars',sellPrice:10875,traderSells:false,traderBuys:true},
{name:'Freezebar Cobalt',className:'freezebar_cobalt',category:'Bars',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Freezebar Copper',className:'freezebar_copper',category:'Bars',sellPrice:4800,traderSells:false,traderBuys:true},
{name:'Freezebar Crimant',className:'freezebar_crimant',category:'Bars',sellPrice:10200,traderSells:false,traderBuys:true},
{name:'Freezebar Enchanted',className:'freezebar_enchanted',category:'Bars',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Freezebar Eridium',className:'freezebar_eridium',category:'Bars',sellPrice:9300,traderSells:false,traderBuys:true},
{name:'Freezebar Gold',className:'freezebar_gold',category:'Bars',sellPrice:6600,traderSells:false,traderBuys:true},
{name:'Freezebar Iron',className:'freezebar_iron',category:'Bars',sellPrice:3900,traderSells:false,traderBuys:true},
{name:'Freezebar Silver',className:'freezebar_silver',category:'Bars',sellPrice:5700,traderSells:false,traderBuys:true},
{name:'Freezebar Tin',className:'freezebar_tin',category:'Bars',sellPrice:3000,traderSells:false,traderBuys:true},
{name:'Freezebar Uranium',className:'freezebar_uranium',category:'Bars',sellPrice:8400,traderSells:false,traderBuys:true},
{name:'Freezegem Amber Flawed',className:'freezegem_amber_flawed',category:'Gems',sellPrice:7282,traderSells:false,traderBuys:true},
{name:'Freezegem Amber Perfect',className:'freezegem_amber_perfect',category:'Gems',sellPrice:8782,traderSells:false,traderBuys:true},
{name:'Freezegem Amber Standard',className:'freezegem_amber_standard',category:'Gems',sellPrice:8032,traderSells:false,traderBuys:true},
{name:'Freezegem Amethyst Flawed',className:'freezegem_amethyst_flawed',category:'Gems',sellPrice:6964,traderSells:false,traderBuys:true},
{name:'Freezegem Amethyst Perfect',className:'freezegem_amethyst_perfect',category:'Gems',sellPrice:8464,traderSells:false,traderBuys:true},
{name:'Freezegem Amethyst Standard',className:'freezegem_amethyst_standard',category:'Gems',sellPrice:7714,traderSells:false,traderBuys:true},
{name:'Freezegem Aquamarine Flawed',className:'freezegem_aquamarine_flawed',category:'Gems',sellPrice:7178,traderSells:false,traderBuys:true},
{name:'Freezegem Aquamarine Perfect',className:'freezegem_aquamarine_perfect',category:'Gems',sellPrice:8678,traderSells:false,traderBuys:true},
{name:'Freezegem Aquamarine Standard',className:'freezegem_aquamarine_standard',category:'Gems',sellPrice:7928,traderSells:false,traderBuys:true},
{name:'Freezegem Fancycolourdiamond Flawed',className:'freezegem_fancycolourdiamond_flawed',category:'Gems',sellPrice:6754,traderSells:false,traderBuys:true},
{name:'Freezegem Fancycolourdiamond Perfect',className:'freezegem_fancycolourdiamond_perfect',category:'Gems',sellPrice:9000,traderSells:false,traderBuys:true},
{name:'Freezegem Fancycolourdiamond Standard',className:'freezegem_fancycolourdiamond_standard',category:'Gems',sellPrice:7504,traderSells:false,traderBuys:true},
{name:'Freezegem Iolite Flawed',className:'freezegem_iolite_flawed',category:'Gems',sellPrice:7069,traderSells:false,traderBuys:true},
{name:'Freezegem Iolite Perfect',className:'freezegem_iolite_perfect',category:'Gems',sellPrice:8569,traderSells:false,traderBuys:true},
{name:'Freezegem Iolite Standard',className:'freezegem_iolite_standard',category:'Gems',sellPrice:7819,traderSells:false,traderBuys:true},
{name:'Freezegem Jade Flawed',className:'freezegem_jade_flawed',category:'Gems',sellPrice:6855,traderSells:false,traderBuys:true},
{name:'Freezegem Jade Perfect',className:'freezegem_jade_perfect',category:'Gems',sellPrice:8355,traderSells:false,traderBuys:true},
{name:'Freezegem Jade Standard',className:'freezegem_jade_standard',category:'Gems',sellPrice:7605,traderSells:false,traderBuys:true},
{name:'Freezegem Ruby Flawed',className:'freezegem_ruby_flawed',category:'Gems',sellPrice:7391,traderSells:false,traderBuys:true},
{name:'Freezegem Ruby Perfect',className:'freezegem_ruby_perfect',category:'Gems',sellPrice:8891,traderSells:false,traderBuys:true},
{name:'Freezegem Ruby Standard',className:'freezegem_ruby_standard',category:'Gems',sellPrice:8141,traderSells:false,traderBuys:true},
{name:'Freezegem Turquoise Flawed',className:'freezegem_turquoise_flawed',category:'Gems',sellPrice:6750,traderSells:false,traderBuys:true},
{name:'Freezegem Turquoise Perfect',className:'freezegem_turquoise_perfect',category:'Gems',sellPrice:8250,traderSells:false,traderBuys:true},
{name:'Freezegem Turquoise Standard',className:'freezegem_turquoise_standard',category:'Gems',sellPrice:7500,traderSells:false,traderBuys:true}
]};
