window.traderCatalogue={traderName:'Mining Trader',currency:'USD',currencyLabel:'USD',items:[
{name:'Tin Bar',className:'freezebar_tin',category:'Bars',mode:'buy',price:4000},
{name:'Iron Bar',className:'freezebar_iron',category:'Bars',mode:'buy',price:5200},
{name:'Copper Bar',className:'freezebar_copper',category:'Bars',mode:'buy',price:6400},
{name:'Silver Bar',className:'freezebar_silver',category:'Bars',mode:'buy',price:7600},
{name:'Gold Bar',className:'freezebar_gold',category:'Bars',mode:'buy',price:8800},
{name:'Cobalt Bar',className:'freezebar_cobalt',category:'Bars',mode:'buy',price:10000},
{name:'Uranium Bar',className:'freezebar_uranium',category:'Bars',mode:'buy',price:11200},
{name:'Eridium Bar',className:'freezebar_eridium',category:'Bars',mode:'buy',price:12400},
{name:'Crimant Bar',className:'freezebar_crimant',category:'Bars',mode:'buy',price:13600},
{name:'Adamantite Bar',className:'freezebar_adamantite',category:'Bars',mode:'buy',price:14500},
{name:'Enchanted Bar',className:'freezebar_enchanted',category:'Bars',mode:'buy',price:15000},
{name:'Flawed Turquoise',className:'freezegem_turquoise_flawed',category:'Gems',mode:'buy',price:9000},
{name:'Standard Turquoise',className:'freezegem_turquoise_standard',category:'Gems',mode:'buy',price:10000},
{name:'Perfect Turquoise',className:'freezegem_turquoise_perfect',category:'Gems',mode:'buy',price:11000},
{name:'Flawed Jade',className:'freezegem_jade_flawed',category:'Gems',mode:'buy',price:9140},
{name:'Standard Jade',className:'freezegem_jade_standard',category:'Gems',mode:'buy',price:10140},
{name:'Perfect Jade',className:'freezegem_jade_perfect',category:'Gems',mode:'buy',price:11140},
{name:'Flawed Amethyst',className:'freezegem_amethyst_flawed',category:'Gems',mode:'buy',price:9285},
{name:'Standard Amethyst',className:'freezegem_amethyst_standard',category:'Gems',mode:'buy',price:10285},
{name:'Perfect Amethyst',className:'freezegem_amethyst_perfect',category:'Gems',mode:'buy',price:11285},
{name:'Flawed Iolite',className:'freezegem_iolite_flawed',category:'Gems',mode:'buy',price:9425},
{name:'Standard Iolite',className:'freezegem_iolite_standard',category:'Gems',mode:'buy',price:10425},
{name:'Perfect Iolite',className:'freezegem_iolite_perfect',category:'Gems',mode:'buy',price:11425},
{name:'Flawed Aquamarine',className:'freezegem_aquamarine_flawed',category:'Gems',mode:'buy',price:9570},
{name:'Standard Aquamarine',className:'freezegem_aquamarine_standard',category:'Gems',mode:'buy',price:10570},
{name:'Perfect Aquamarine',className:'freezegem_aquamarine_perfect',category:'Gems',mode:'buy',price:11570},
{name:'Flawed Amber',className:'freezegem_amber_flawed',category:'Gems',mode:'buy',price:9710},
{name:'Standard Amber',className:'freezegem_amber_standard',category:'Gems',mode:'buy',price:10710},
{name:'Perfect Amber',className:'freezegem_amber_perfect',category:'Gems',mode:'buy',price:11710},
{name:'Flawed Ruby',className:'freezegem_ruby_flawed',category:'Gems',mode:'buy',price:9855},
{name:'Standard Ruby',className:'freezegem_ruby_standard',category:'Gems',mode:'buy',price:10855},
{name:'Perfect Ruby',className:'freezegem_ruby_perfect',category:'Gems',mode:'buy',price:11855},
{name:'Flawed Fancy Colour Diamond',className:'freezegem_fancycolourdiamond_flawed',category:'Gems',mode:'buy',price:9005},
{name:'Standard Fancy Colour Diamond',className:'freezegem_fancycolourdiamond_standard',category:'Gems',mode:'buy',price:10005},
{name:'Perfect Fancy Colour Diamond',className:'freezegem_fancycolourdiamond_perfect',category:'Gems',mode:'buy',price:12000}
]};