window.traderCatalogue={traderName:'Mining Trader',currency:'USD',items:[
{name:'Freezegem Amber Flawed',className:'freezegem_amber_flawed',category:'Gems',sellPrice:9710,traderSells:false,traderBuys:true},
{name:'Freezegem Amber Perfect',className:'freezegem_amber_perfect',category:'Gems',sellPrice:11710,traderSells:false,traderBuys:true},
{name:'Freezegem Amber Standard',className:'freezegem_amber_standard',category:'Gems',sellPrice:10710,traderSells:false,traderBuys:true},
{name:'Freezegem Amethyst Flawed',className:'freezegem_amethyst_flawed',category:'Gems',sellPrice:9285,traderSells:false,traderBuys:true},
{name:'Freezegem Amethyst Perfect',className:'freezegem_amethyst_perfect',category:'Gems',sellPrice:11285,traderSells:false,traderBuys:true},
{name:'Freezegem Amethyst Standard',className:'freezegem_amethyst_standard',category:'Gems',sellPrice:10285,traderSells:false,traderBuys:true},
{name:'Freezegem Aquamarine Flawed',className:'freezegem_aquamarine_flawed',category:'Gems',sellPrice:9570,traderSells:false,traderBuys:true},
{name:'Freezegem Aquamarine Perfect',className:'freezegem_aquamarine_perfect',category:'Gems',sellPrice:11570,traderSells:false,traderBuys:true},
{name:'Freezegem Aquamarine Standard',className:'freezegem_aquamarine_standard',category:'Gems',sellPrice:10570,traderSells:false,traderBuys:true},
{name:'Freezegem Fancycolourdiamond Flawed',className:'freezegem_fancycolourdiamond_flawed',category:'Gems',sellPrice:9005,traderSells:false,traderBuys:true},
{name:'Freezegem Fancycolourdiamond Perfect',className:'freezegem_fancycolourdiamond_perfect',category:'Gems',sellPrice:12000,traderSells:false,traderBuys:true},
{name:'Freezegem Fancycolourdiamond Standard',className:'freezegem_fancycolourdiamond_standard',category:'Gems',sellPrice:10005,traderSells:false,traderBuys:true},
{name:'Freezegem Iolite Flawed',className:'freezegem_iolite_flawed',category:'Gems',sellPrice:9425,traderSells:false,traderBuys:true},
{name:'Freezegem Iolite Perfect',className:'freezegem_iolite_perfect',category:'Gems',sellPrice:11425,traderSells:false,traderBuys:true},
{name:'Freezegem Iolite Standard',className:'freezegem_iolite_standard',category:'Gems',sellPrice:10425,traderSells:false,traderBuys:true},
{name:'Freezegem Jade Flawed',className:'freezegem_jade_flawed',category:'Gems',sellPrice:9140,traderSells:false,traderBuys:true},
{name:'Freezegem Jade Perfect',className:'freezegem_jade_perfect',category:'Gems',sellPrice:11140,traderSells:false,traderBuys:true},
{name:'Freezegem Jade Standard',className:'freezegem_jade_standard',category:'Gems',sellPrice:10140,traderSells:false,traderBuys:true},
{name:'Freezegem Ruby Flawed',className:'freezegem_ruby_flawed',category:'Gems',sellPrice:9855,traderSells:false,traderBuys:true},
{name:'Freezegem Ruby Perfect',className:'freezegem_ruby_perfect',category:'Gems',sellPrice:11855,traderSells:false,traderBuys:true},
{name:'Freezegem Ruby Standard',className:'freezegem_ruby_standard',category:'Gems',sellPrice:10855,traderSells:false,traderBuys:true},
{name:'Freezegem Turquoise Flawed',className:'freezegem_turquoise_flawed',category:'Gems',sellPrice:9000,traderSells:false,traderBuys:true},
{name:'Freezegem Turquoise Perfect',className:'freezegem_turquoise_perfect',category:'Gems',sellPrice:11000,traderSells:false,traderBuys:true},
{name:'Freezegem Turquoise Standard',className:'freezegem_turquoise_standard',category:'Gems',sellPrice:10000,traderSells:false,traderBuys:true}
]};
