window.traderCatalogue={traderName:'Hassan',currency:'USD',groupCollectableVariants:true,items:[
{name:'Baby Batter Nug',className:'im7s_smallnug_babybatter',category:'Cannabis Nuggets',sellPrice:481,traderSells:false,traderBuys:true},
{name:'Barney Nug',className:'im7s_smallnug_barney',category:'Cannabis Nuggets',sellPrice:506,traderSells:false,traderBuys:true},
{name:'Blue Cookies Nug',className:'im7s_smallnug_bluecookies',category:'Cannabis Nuggets',sellPrice:525,traderSells:false,traderBuys:true},
{name:'Champagne Nug',className:'im7s_smallnug_champagne',category:'Cannabis Nuggets',sellPrice:550,traderSells:false,traderBuys:true},
{name:'Cheetah Piss Nug',className:'im7s_smallnug_cheetahpiss',category:'Cannabis Nuggets',sellPrice:494,traderSells:false,traderBuys:true},
{name:'Gelato Nug',className:'im7s_smallnug_gelato',category:'Cannabis Nuggets',sellPrice:569,traderSells:false,traderBuys:true},
{name:'Paragon Nug',className:'im7s_smallnug_paragon',category:'Cannabis Nuggets',sellPrice:538,traderSells:false,traderBuys:true},
{name:'Baby Batter Brick',className:'im7s_brick_babybatter',category:'Drug Bricks',sellPrice:27500,traderSells:false,traderBuys:true},
{name:'Barney Brick',className:'im7s_brick_barney',category:'Drug Bricks',sellPrice:28662,traderSells:false,traderBuys:true},
{name:'Black Tar Brick',className:'im7s_brick_blacktar',category:'Drug Bricks',sellPrice:50000,traderSells:false,traderBuys:true},
{name:'Blue Cookies Brick',className:'im7s_brick_bluecookies',category:'Drug Bricks',sellPrice:27506,traderSells:false,traderBuys:true},
{name:'Brown Brick',className:'im7s_brick_brown',category:'Drug Bricks',sellPrice:56250,traderSells:false,traderBuys:true},
{name:'Champagne Brick',className:'im7s_brick_champagne',category:'Drug Bricks',sellPrice:27512,traderSells:false,traderBuys:true},
{name:'Cheetah Piss Brick',className:'im7s_brick_cheetahpiss',category:'Drug Bricks',sellPrice:27519,traderSells:false,traderBuys:true},
{name:'Cocaine Brick',className:'im7s_brick_coke',category:'Drug Bricks',sellPrice:50006,traderSells:false,traderBuys:true},
{name:'Crystal Blue Brick',className:'im7s_brick_crystal_blue',category:'Drug Bricks',sellPrice:43750,traderSells:false,traderBuys:true},
{name:'Crystal PB Brick',className:'im7s_brick_crystal_pb',category:'Drug Bricks',sellPrice:51250,traderSells:false,traderBuys:true},
{name:'Crystal Pink Brick',className:'im7s_brick_crystal_pink',category:'Drug Bricks',sellPrice:46875,traderSells:false,traderBuys:true},
{name:'Fentanyl Brick',className:'im7s_brick_fent',category:'Drug Bricks',sellPrice:62500,traderSells:false,traderBuys:true},
{name:'Gelato Brick',className:'im7s_brick_gelato',category:'Drug Bricks',sellPrice:28006,traderSells:false,traderBuys:true},
{name:'MDMA Brick',className:'im7s_brick_mdma',category:'Drug Bricks',sellPrice:25000,traderSells:false,traderBuys:true},
{name:'Paragon Brick',className:'im7s_brick_paragon',category:'Drug Bricks',sellPrice:27525,traderSells:false,traderBuys:true},
{name:'Thizz Blue Brick',className:'im7s_brick_thizz_blue',category:'Drug Bricks',sellPrice:31250,traderSells:false,traderBuys:true},
{name:'Thizz Green Brick',className:'im7s_brick_thizz_green',category:'Drug Bricks',sellPrice:31256,traderSells:false,traderBuys:true},
{name:'Thizz Purple Brick',className:'im7s_brick_thizz_purple',category:'Drug Bricks',sellPrice:31262,traderSells:false,traderBuys:true},
{name:'Thizz Yellow Brick',className:'im7s_brick_thizz_yellow',category:'Drug Bricks',sellPrice:31269,traderSells:false,traderBuys:true},
{name:'Cocaine Bundle',className:'im7s_bundle_coke',category:'Drug Bundles',sellPrice:5656,traderSells:false,traderBuys:true},
{name:'Crystal Blue Bundle',className:'im7s_bundle_crystal_blue',category:'Drug Bundles',sellPrice:4969,traderSells:false,traderBuys:true},
{name:'Crystal PB Bundle',className:'im7s_bundle_crystal_pb',category:'Drug Bundles',sellPrice:5800,traderSells:false,traderBuys:true},
{name:'Crystal Pink Bundle',className:'im7s_bundle_crystal_pink',category:'Drug Bundles',sellPrice:5331,traderSells:false,traderBuys:true},
{name:'Thizz Blue Bundle',className:'im7s_bundle_thizz_blue',category:'Drug Bundles',sellPrice:3594,traderSells:false,traderBuys:true},
{name:'Thizz Green Bundle',className:'im7s_bundle_thizz_green',category:'Drug Bundles',sellPrice:3619,traderSells:false,traderBuys:true},
{name:'Thizz Purple Bundle',className:'im7s_bundle_thizz_purple',category:'Drug Bundles',sellPrice:3644,traderSells:false,traderBuys:true},
{name:'Thizz Yellow Bundle',className:'im7s_bundle_thizz_yellow',category:'Drug Bundles',sellPrice:3669,traderSells:false,traderBuys:true},
{name:'LSD — Adventure',className:'im7s_lsd_adventure',category:'LSD',sellPrice:33300,traderSells:false,traderBuys:true},
{name:'LSD — G-Code',className:'im7s_lsd_g_code',category:'LSD',sellPrice:34775,traderSells:false,traderBuys:true},
{name:'LSD — Ill',className:'im7s_lsd_ill',category:'LSD',sellPrice:33881,traderSells:false,traderBuys:true},
{name:'LSD — Lemon Carb',className:'im7s_lsd_lemoncarb',category:'LSD',sellPrice:34369,traderSells:false,traderBuys:true},
{name:'LSD — Mickey',className:'im7s_lsd_mickey',category:'LSD',sellPrice:33638,traderSells:false,traderBuys:true},
{name:'LSD — Off-Brand',className:'im7s_lsd_offbrand',category:'LSD',sellPrice:34544,traderSells:false,traderBuys:true},
{name:'LSD — Rick',className:'im7s_lsd_rick',category:'LSD',sellPrice:33481,traderSells:false,traderBuys:true},
{name:'LSD — Sunday Trip',className:'im7s_lsd_sundaytrip',category:'LSD',sellPrice:34200,traderSells:false,traderBuys:true},
{name:'Brick Storage Pallet',className:'im7s_storagepallet_bricks',category:'Production Supplies',buyPrice:29992,sellPrice:24994,traderSells:true,traderBuys:true},
{name:'Bud Trimmer Kit',className:'im7s_budtrimmer_kit',category:'Production Supplies',buyPrice:108000,sellPrice:90000,traderSells:true,traderBuys:true},
{name:'Drying Rack Kit',className:'im7s_dryingrack_kit',category:'Production Supplies',buyPrice:63000,sellPrice:52500,traderSells:true,traderBuys:true},
{name:'Hydro Planter Kit',className:'im7s_hydroplanter_kit',category:'Production Supplies',buyPrice:42000,sellPrice:35000,traderSells:true,traderBuys:true},
{name:'Hydroponics DBS Kit',className:'im7s_hydroponics_dbs_kit',category:'Production Supplies',buyPrice:108000,sellPrice:90000,traderSells:true,traderBuys:true},
{name:'Hydroponics DWC Kit',className:'im7s_hydroponics_dwc_kit',category:'Production Supplies',buyPrice:108000,sellPrice:90000,traderSells:true,traderBuys:true},
{name:'I M7s Chem Barrel Blue',className:'iM7s_Chem_Barrel_Blue',category:'Production Supplies',buyPrice:112500,sellPrice:93750,traderSells:true,traderBuys:true},
{name:'I M7s Chem Barrel Green',className:'iM7s_Chem_Barrel_Green',category:'Production Supplies',buyPrice:112500,sellPrice:93750,traderSells:true,traderBuys:true},
{name:'I M7s Chem Barrel Hazmat',className:'iM7s_Chem_Barrel_Hazmat',category:'Production Supplies',buyPrice:112500,sellPrice:93750,traderSells:true,traderBuys:true},
{name:'I M7s Chem Barrel White',className:'iM7s_Chem_Barrel_White',category:'Production Supplies',buyPrice:112500,sellPrice:93750,traderSells:true,traderBuys:true},
{name:'Industrial Pill Press Kit',className:'im7s_pillpress_industrial_kit',category:'Production Supplies',buyPrice:63000,sellPrice:52500,traderSells:true,traderBuys:true},
{name:'Lab Station Kit',className:'im7s_labstation_kit',category:'Production Supplies',buyPrice:63000,sellPrice:52500,traderSells:true,traderBuys:true},
{name:'LSD Lab Kit',className:'im7s_lsd_lab_kit',category:'Production Supplies',buyPrice:63000,sellPrice:52500,traderSells:true,traderBuys:true},
{name:'Production Table Kit',className:'im7s_productiontable_kit',category:'Production Supplies',buyPrice:63000,sellPrice:52500,traderSells:true,traderBuys:true},
{name:'Zip-Lock Baggies',className:'im7s_ziplock',category:'Production Supplies',buyPrice:13125,sellPrice:10938,traderSells:true,traderBuys:true}
]};
