window.traderCatalogue={traderName:'Linda',currency:'USD',items:[
{name:'Alcohol Tincture',className:'disinfectantalcohol',category:'Medical Supplies',buyPrice:15580,sellPrice:156,traderSells:true,traderBuys:true},
{name:'Bandage Dressing',className:'bandagedressing',category:'Medical Supplies',buyPrice:16285,sellPrice:163,traderSells:true,traderBuys:true},
{name:'Blood Test Kit',className:'bloodtestkit',category:'Medical Supplies',buyPrice:15145,sellPrice:151,traderSells:true,traderBuys:true},
{name:'Charcoal Tablets',className:'charcoaltablets',category:'Medical Supplies',buyPrice:15270,sellPrice:153,traderSells:true,traderBuys:true},
{name:'Chelating Tablets',className:'chelatingtablets',category:'Medical Supplies',buyPrice:18475,sellPrice:185,traderSells:true,traderBuys:true},
{name:'Chlorine Tablets',className:'purificationtablets',category:'Medical Supplies',buyPrice:15105,sellPrice:151,traderSells:true,traderBuys:true},
{name:'Codeine Pills',className:'painkillertablets',category:'Medical Supplies',buyPrice:15330,sellPrice:153,traderSells:true,traderBuys:true},
{name:'Disinfectant Spray',className:'disinfectantspray',category:'Medical Supplies',buyPrice:16050,sellPrice:160,traderSells:true,traderBuys:true},
{name:'Empty Blood Bag',className:'bloodbagempty',category:'Medical Supplies',buyPrice:15535,sellPrice:155,traderSells:true,traderBuys:true},
{name:'Epinephrine Auto-Injector',className:'epinephrine',category:'Medical Supplies',buyPrice:15310,sellPrice:153,traderSells:true,traderBuys:true},
{name:'First Aid Kit',className:'firstaidkit',category:'Medical Supplies',buyPrice:20000,sellPrice:200,traderSells:true,traderBuys:true},
{name:'Gas Mask Filter',className:'gasmask_filter',category:'Medical Supplies',buyPrice:18180,sellPrice:182,traderSells:true,traderBuys:true},
{name:'Heat Pack',className:'heatpack',category:'Medical Supplies',buyPrice:15860,sellPrice:159,traderSells:true,traderBuys:true},
{name:'Iodine Tincture',className:'iodinetincture',category:'Medical Supplies',buyPrice:19885,sellPrice:199,traderSells:true,traderBuys:true},
{name:'IV Start Kit',className:'startkitiv',category:'Medical Supplies',buyPrice:16585,sellPrice:166,traderSells:true,traderBuys:true},
{name:'Medical Thermometer',className:'thermometer',category:'Medical Supplies',buyPrice:17830,sellPrice:178,traderSells:true,traderBuys:true},
{name:'Morphine Auto-Injector',className:'morphine',category:'Medical Supplies',buyPrice:17710,sellPrice:177,traderSells:true,traderBuys:true},
{name:'Multivitamin Pills',className:'vitaminbottle',category:'Medical Supplies',buyPrice:16220,sellPrice:162,traderSells:true,traderBuys:true},
{name:'PO-X Antidote Injector',className:'anticheminjector',category:'Medical Supplies',buyPrice:16125,sellPrice:161,traderSells:true,traderBuys:true},
{name:'Saline Bag',className:'salinebag',category:'Medical Supplies',buyPrice:17470,sellPrice:175,traderSells:true,traderBuys:true},
{name:'Tetracycline Antibiotics',className:'tetracyclineantibiotics',category:'Medical Supplies',buyPrice:19845,sellPrice:198,traderSells:true,traderBuys:true}
]};
