window.traderCatalogue={traderName:'Linda',currency:'USD',items:[
{name:'Alcohol Tincture',className:'disinfectantalcohol',category:'Medical Supplies',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Bandage Dressing',className:'bandagedressing',category:'Medical Supplies',buyPrice:250,sellPrice:125,traderSells:true,traderBuys:true},
{name:'Blood Test Kit',className:'bloodtestkit',category:'Medical Supplies',buyPrice:900,sellPrice:450,traderSells:true,traderBuys:true},
{name:'Charcoal Tablets',className:'charcoaltablets',category:'Medical Supplies',buyPrice:350,sellPrice:175,traderSells:true,traderBuys:true},
{name:'Chelating Tablets',className:'chelatingtablets',category:'Medical Supplies',buyPrice:2500,sellPrice:1250,traderSells:true,traderBuys:true},
{name:'Chlorine Tablets',className:'purificationtablets',category:'Medical Supplies',buyPrice:500,sellPrice:250,traderSells:true,traderBuys:true},
{name:'Codeine Pills',className:'painkillertablets',category:'Medical Supplies',buyPrice:300,sellPrice:150,traderSells:true,traderBuys:true},
{name:'Disinfectant Spray',className:'disinfectantspray',category:'Medical Supplies',buyPrice:600,sellPrice:300,traderSells:true,traderBuys:true},
{name:'Empty Blood Bag',className:'bloodbagempty',category:'Medical Supplies',buyPrice:750,sellPrice:375,traderSells:true,traderBuys:true},
{name:'Epinephrine Auto-Injector',className:'epinephrine',category:'Medical Supplies',buyPrice:1200,sellPrice:600,traderSells:true,traderBuys:true},
{name:'First Aid Kit',className:'firstaidkit',category:'Medical Supplies',buyPrice:2000,sellPrice:1000,traderSells:true,traderBuys:true},
{name:'Gas Mask Filter',className:'gasmask_filter',category:'Medical Supplies',buyPrice:900,sellPrice:450,traderSells:true,traderBuys:true},
{name:'Heat Pack',className:'heatpack',category:'Medical Supplies',buyPrice:400,sellPrice:200,traderSells:true,traderBuys:true},
{name:'Iodine Tincture',className:'iodinetincture',category:'Medical Supplies',buyPrice:700,sellPrice:350,traderSells:true,traderBuys:true},
{name:'IV Start Kit',className:'startkitiv',category:'Medical Supplies',buyPrice:2500,sellPrice:1250,traderSells:true,traderBuys:true},
{name:'Medical Thermometer',className:'thermometer',category:'Medical Supplies',buyPrice:400,sellPrice:200,traderSells:true,traderBuys:true},
{name:'Morphine Auto-Injector',className:'morphine',category:'Medical Supplies',buyPrice:1500,sellPrice:750,traderSells:true,traderBuys:true},
{name:'Multivitamin Pills',className:'vitaminbottle',category:'Medical Supplies',buyPrice:350,sellPrice:175,traderSells:true,traderBuys:true},
{name:'PO-X Antidote Injector',className:'anticheminjector',category:'Medical Supplies',buyPrice:3000,sellPrice:1500,traderSells:true,traderBuys:true},
{name:'Saline Bag',className:'salinebag',category:'Medical Supplies',buyPrice:1800,sellPrice:900,traderSells:true,traderBuys:true},
{name:'Tetracycline Antibiotics',className:'tetracyclineantibiotics',category:'Medical Supplies',buyPrice:1100,sellPrice:550,traderSells:true,traderBuys:true}
]};
