window.traderCatalogue={traderName:'Kaito',currency:'USD',groupCollectableVariants:true,items:[
{name:'Drip Adidascasual Black',className:'drip_adidascasual_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidascasual Black Pearl',className:'drip_adidascasual_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Adidascasual Emerald',className:'drip_adidascasual_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Adidascasual Gold',className:'drip_adidascasual_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Adidascasual Pink',className:'drip_adidascasual_pink',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidascasual Ruby',className:'drip_adidascasual_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Adidascasual Sapphire',className:'drip_adidascasual_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Adidascasual Tan',className:'drip_adidascasual_tan',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidascasual White',className:'drip_adidascasual_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Beluga',className:'drip_adidasyeezy350_beluga',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Beluga 2',className:'drip_adidasyeezy350_beluga_2',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Black Pearl',className:'drip_adidasyeezy350_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Black Red',className:'drip_adidasyeezy350_black_red',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Core Black Copper',className:'drip_adidasyeezy350_core_black_copper',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Core Black Green',className:'drip_adidasyeezy350_core_black_green',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Core Black Red',className:'drip_adidasyeezy350_core_black_red',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Core Black White',className:'drip_adidasyeezy350_core_black_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Cream',className:'drip_adidasyeezy350_cream',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Dazzling Blue',className:'drip_adidasyeezy350_dazzling_blue',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Earth',className:'drip_adidasyeezy350_earth',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Emerald',className:'drip_adidasyeezy350_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Glow',className:'drip_adidasyeezy350_glow',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Gold',className:'drip_adidasyeezy350_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Mx Frost',className:'drip_adidasyeezy350_mx_frost',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Mx Oat',className:'drip_adidasyeezy350_mx_oat',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Mx Rock',className:'drip_adidasyeezy350_mx_rock',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Onyx',className:'drip_adidasyeezy350_onyx',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Ruby',className:'drip_adidasyeezy350_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Salt',className:'drip_adidasyeezy350_salt',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Sapphire',className:'drip_adidasyeezy350_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Semi Frozen Yellow',className:'drip_adidasyeezy350_semi_frozen_yellow',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Slate',className:'drip_adidasyeezy350_slate',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy350 Zebra',className:'drip_adidasyeezy350_zebra',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy750 Black Pearl',className:'drip_adidasyeezy750_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy750 Chocolate',className:'drip_adidasyeezy750_chocolate',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy750 Emerald',className:'drip_adidasyeezy750_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy750 Gold',className:'drip_adidasyeezy750_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy750 Light Brown',className:'drip_adidasyeezy750_light_brown',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy750 Light Grey',className:'drip_adidasyeezy750_light_grey',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy750 Ruby',className:'drip_adidasyeezy750_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy750 Sapphire',className:'drip_adidasyeezy750_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezy750 Triple Black',className:'drip_adidasyeezy750_triple_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Azure',className:'drip_adidasyeezyslides_azure',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Black Pearl',className:'drip_adidasyeezyslides_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Bone',className:'drip_adidasyeezyslides_bone',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Emerald',className:'drip_adidasyeezyslides_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Enflame Orange',className:'drip_adidasyeezyslides_enflame_orange',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Flax',className:'drip_adidasyeezyslides_flax',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Glow',className:'drip_adidasyeezyslides_glow',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Gold',className:'drip_adidasyeezyslides_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Granite',className:'drip_adidasyeezyslides_granite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Mx Cream',className:'drip_adidasyeezyslides_mx_cream',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Mx Moon',className:'drip_adidasyeezyslides_mx_moon',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Ochre',className:'drip_adidasyeezyslides_ochre',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Onyx',className:'drip_adidasyeezyslides_onyx',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Pure',className:'drip_adidasyeezyslides_pure',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Resin',className:'drip_adidasyeezyslides_resin',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Ruby',className:'drip_adidasyeezyslides_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Sand',className:'drip_adidasyeezyslides_sand',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Sapphire',className:'drip_adidasyeezyslides_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Slate',className:'drip_adidasyeezyslides_slate',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Adidasyeezyslides Soot',className:'drip_adidasyeezyslides_soot',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Banana',className:'drip_crocs_relaxed_banana',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Black',className:'drip_crocs_relaxed_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Black Pearl',className:'drip_crocs_relaxed_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Blue Bolt',className:'drip_crocs_relaxed_blue_bolt',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Elmo',className:'drip_crocs_relaxed_elmo',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Emerald',className:'drip_crocs_relaxed_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Evergreen',className:'drip_crocs_relaxed_evergreen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Flame',className:'drip_crocs_relaxed_flame',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Gold',className:'drip_crocs_relaxed_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Juice',className:'drip_crocs_relaxed_juice',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Kfc',className:'drip_crocs_relaxed_kfc',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Lightning Mcqueen',className:'drip_crocs_relaxed_lightning_mcqueen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Limeade',className:'drip_crocs_relaxed_limeade',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Neon Purple',className:'drip_crocs_relaxed_neon_purple',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Orange Sorbet',className:'drip_crocs_relaxed_orange_sorbet',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Orange Zing',className:'drip_crocs_relaxed_orange_zing',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Pistachio',className:'drip_crocs_relaxed_pistachio',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Ruby',className:'drip_crocs_relaxed_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed Sapphire',className:'drip_crocs_relaxed_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Crocs Relaxed White',className:'drip_crocs_relaxed_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Banana',className:'drip_crocs_sport_banana',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Black',className:'drip_crocs_sport_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Black Pearl',className:'drip_crocs_sport_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Blue Bolt',className:'drip_crocs_sport_blue_bolt',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Elmo',className:'drip_crocs_sport_elmo',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Emerald',className:'drip_crocs_sport_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Evergreen',className:'drip_crocs_sport_evergreen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Flame',className:'drip_crocs_sport_flame',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Gold',className:'drip_crocs_sport_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Juice',className:'drip_crocs_sport_juice',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Kfc',className:'drip_crocs_sport_kfc',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Lightning Mcqueen',className:'drip_crocs_sport_lightning_mcqueen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Limeade',className:'drip_crocs_sport_limeade',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Neon Purple',className:'drip_crocs_sport_neon_purple',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Orange Sorbet',className:'drip_crocs_sport_orange_sorbet',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Orange Zing',className:'drip_crocs_sport_orange_zing',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Pistachio',className:'drip_crocs_sport_pistachio',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Ruby',className:'drip_crocs_sport_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport Sapphire',className:'drip_crocs_sport_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Crocs Sport White',className:'drip_crocs_sport_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Banana',className:'drip_crocsocks_relaxed_banana',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Black',className:'drip_crocsocks_relaxed_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Black Pearl',className:'drip_crocsocks_relaxed_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Blue Bolt',className:'drip_crocsocks_relaxed_blue_bolt',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Elmo',className:'drip_crocsocks_relaxed_elmo',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Emerald',className:'drip_crocsocks_relaxed_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Evergreen',className:'drip_crocsocks_relaxed_evergreen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Flame',className:'drip_crocsocks_relaxed_flame',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Gold',className:'drip_crocsocks_relaxed_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Juice',className:'drip_crocsocks_relaxed_juice',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Kfc',className:'drip_crocsocks_relaxed_kfc',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Lightning Mcqueen',className:'drip_crocsocks_relaxed_lightning_mcqueen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Limeade',className:'drip_crocsocks_relaxed_limeade',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Neon Purple',className:'drip_crocsocks_relaxed_neon_purple',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Orange Zing',className:'drip_crocsocks_relaxed_orange_zing',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Pistachio',className:'drip_crocsocks_relaxed_pistachio',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Ruby',className:'drip_crocsocks_relaxed_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed Sapphire',className:'drip_crocsocks_relaxed_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Relaxed White',className:'drip_crocsocks_relaxed_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Banana',className:'drip_crocsocks_sport_banana',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Black',className:'drip_crocsocks_sport_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Black Pearl',className:'drip_crocsocks_sport_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Blue Bolt',className:'drip_crocsocks_sport_blue_bolt',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Elmo',className:'drip_crocsocks_sport_elmo',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Emerald',className:'drip_crocsocks_sport_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Evergreen',className:'drip_crocsocks_sport_evergreen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Flame',className:'drip_crocsocks_sport_flame',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Gold',className:'drip_crocsocks_sport_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Juice',className:'drip_crocsocks_sport_juice',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Kfc',className:'drip_crocsocks_sport_kfc',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Lightning Mcqueen',className:'drip_crocsocks_sport_lightning_mcqueen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Limeade',className:'drip_crocsocks_sport_limeade',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Neon Purple',className:'drip_crocsocks_sport_neon_purple',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Orange Sorbet',className:'drip_crocsocks_sport_orange_sorbet',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Orange Zing',className:'drip_crocsocks_sport_orange_zing',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Pistachio',className:'drip_crocsocks_sport_pistachio',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Ruby',className:'drip_crocsocks_sport_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport Sapphire',className:'drip_crocsocks_sport_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Crocsocks Sport White',className:'drip_crocsocks_sport_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Drippypoo Black Pearl',className:'drip_drippypoo_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Drippypoo Bloody',className:'drip_drippypoo_bloody',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Drippypoo Brown',className:'drip_drippypoo_brown',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Drippypoo Emerald',className:'drip_drippypoo_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Drippypoo Gold',className:'drip_drippypoo_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Drippypoo Green',className:'drip_drippypoo_green',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Drippypoo Ruby',className:'drip_drippypoo_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Drippypoo Sapphire',className:'drip_drippypoo_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Hobbitfeet',className:'drip_hobbitfeet',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Hobbitfeet Xl',className:'drip_hobbitfeet_xl',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Hobbitfeet Xxxl',className:'drip_hobbitfeet_xxxl',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Bape Blue',className:'drip_mschfboots_bape_blue',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Bape Green',className:'drip_mschfboots_bape_green',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Bape Pink',className:'drip_mschfboots_bape_pink',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Bape Purple',className:'drip_mschfboots_bape_purple',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Bape Red',className:'drip_mschfboots_bape_red',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Bape White',className:'drip_mschfboots_bape_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Black',className:'drip_mschfboots_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Black Pearl',className:'drip_mschfboots_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Blue',className:'drip_mschfboots_blue',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Emerald',className:'drip_mschfboots_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Gold',className:'drip_mschfboots_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Green',className:'drip_mschfboots_green',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Pink',className:'drip_mschfboots_pink',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Red',className:'drip_mschfboots_red',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Ruby',className:'drip_mschfboots_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Sapphire',className:'drip_mschfboots_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots White',className:'drip_mschfboots_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Mschfboots Yellow',className:'drip_mschfboots_yellow',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 07 Retro Blue',className:'drip_nikeairforce_1_07_retro_blue',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 07 Retro Pink Gum',className:'drip_nikeairforce_1_07_retro_pink_gum',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 07 Retro Red',className:'drip_nikeairforce_1_07_retro_red',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 07 Retro Red Gum',className:'drip_nikeairforce_1_07_retro_red_gum',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 07 Retro Royal Gum',className:'drip_nikeairforce_1_07_retro_royal_gum',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 07 Retro White Chocolate',className:'drip_nikeairforce_1_07_retro_white_chocolate',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 Black Pearl',className:'drip_nikeairforce_1_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 Emerald',className:'drip_nikeairforce_1_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 Gold',className:'drip_nikeairforce_1_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 Just Orange',className:'drip_nikeairforce_1_just_orange',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 Ruby',className:'drip_nikeairforce_1_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 Sapphire',className:'drip_nikeairforce_1_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 Triple Black',className:'drip_nikeairforce_1_triple_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 Triple Red',className:'drip_nikeairforce_1_triple_red',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 Triple White',className:'drip_nikeairforce_1_triple_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairforce 1 Wheat Black',className:'drip_nikeairforce_1_wheat_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1',className:'drip_nikeairjordan_1',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Black Pearl',className:'drip_nikeairjordan_1_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Chicago',className:'drip_nikeairjordan_1_chicago',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Crimson Pulse',className:'drip_nikeairjordan_1_crimson_pulse',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Diamond Shorts',className:'drip_nikeairjordan_1_diamond_shorts',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Emerald',className:'drip_nikeairjordan_1_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Gold',className:'drip_nikeairjordan_1_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Hyper Royal',className:'drip_nikeairjordan_1_hyper_royal',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Hyper Royal Violet',className:'drip_nikeairjordan_1_hyper_royal_violet',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 John',className:'drip_nikeairjordan_1_john',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Reverse Bred',className:'drip_nikeairjordan_1_reverse_bred',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Ruby',className:'drip_nikeairjordan_1_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Sapphire',className:'drip_nikeairjordan_1_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Taxi',className:'drip_nikeairjordan_1_taxi',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Triple Black',className:'drip_nikeairjordan_1_triple_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Triple White',className:'drip_nikeairjordan_1_triple_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 1 Visionaire',className:'drip_nikeairjordan_1_visionaire',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Black Pearl',className:'drip_nikeairjordan_4_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Bred',className:'drip_nikeairjordan_4_bred',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Bubblegum',className:'drip_nikeairjordan_4_bubblegum',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Emerald',className:'drip_nikeairjordan_4_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Fire',className:'drip_nikeairjordan_4_fire',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Gold',className:'drip_nikeairjordan_4_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Maniere',className:'drip_nikeairjordan_4_maniere',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Miami',className:'drip_nikeairjordan_4_miami',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Neon',className:'drip_nikeairjordan_4_neon',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Red Thunder',className:'drip_nikeairjordan_4_red_thunder',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Ruby',className:'drip_nikeairjordan_4_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Sail',className:'drip_nikeairjordan_4_sail',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Sapphire',className:'drip_nikeairjordan_4_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 What',className:'drip_nikeairjordan_4_what',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 White Cement',className:'drip_nikeairjordan_4_white_cement',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairjordan 4 Yellow Thunder',className:'drip_nikeairjordan_4_yellow_thunder',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairyeezy Black Pearl',className:'drip_nikeairyeezy_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Nikeairyeezy Emerald',className:'drip_nikeairyeezy_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Nikeairyeezy Gold',className:'drip_nikeairyeezy_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Nikeairyeezy Pure Platinum',className:'drip_nikeairyeezy_pure_platinum',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairyeezy Red October',className:'drip_nikeairyeezy_red_october',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairyeezy Ruby',className:'drip_nikeairyeezy_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairyeezy Sapphire',className:'drip_nikeairyeezy_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Nikeairyeezy Solar Red',className:'drip_nikeairyeezy_solar_red',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairzoom Black Pearl',className:'drip_nikeairzoom_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Nikeairzoom Emerald',className:'drip_nikeairzoom_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Nikeairzoom Gold',className:'drip_nikeairzoom_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Nikeairzoom Ruby',className:'drip_nikeairzoom_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairzoom Sapphire',className:'drip_nikeairzoom_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Nikeairzoom Unvrs Flyease Light',className:'drip_nikeairzoom_unvrs_flyease_light',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairzoom Unvrs Flyease Usa',className:'drip_nikeairzoom_unvrs_flyease_usa',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikeairzoom Unvrs Flyease Vivid Purple',className:'drip_nikeairzoom_unvrs_flyease_vivid_purple',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikemag',className:'drip_nikemag',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Nikemag Black Pearl',className:'drip_nikemag_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Nikemag Emerald',className:'drip_nikemag_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Nikemag Gold',className:'drip_nikemag_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Nikemag Ruby',className:'drip_nikemag_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Nikemag Sapphire',className:'drip_nikemag_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Pampaboots Anthracite',className:'drip_pampaboots_anthracite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Pampaboots Black',className:'drip_pampaboots_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Pampaboots Black Pearl',className:'drip_pampaboots_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Pampaboots Emerald',className:'drip_pampaboots_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Pampaboots Gold',className:'drip_pampaboots_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Pampaboots Green',className:'drip_pampaboots_green',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Pampaboots Grey',className:'drip_pampaboots_grey',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Pampaboots Ruby',className:'drip_pampaboots_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Pampaboots Safari',className:'drip_pampaboots_safari',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Pampaboots Sapphire',className:'drip_pampaboots_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Piggyslippers',className:'drip_piggyslippers',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Piggyslippers Black Pearl',className:'drip_piggyslippers_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Piggyslippers Emerald',className:'drip_piggyslippers_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Piggyslippers Gold',className:'drip_piggyslippers_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Piggyslippers Ruby',className:'drip_piggyslippers_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Piggyslippers Sapphire',className:'drip_piggyslippers_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Powersneakers',className:'drip_powersneakers',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Ragezrlegend Black',className:'drip_ragezrlegend_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Ragezrlegend Black Neon',className:'drip_ragezrlegend_black_neon',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Ragezrlegend Black Pearl',className:'drip_ragezrlegend_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Ragezrlegend Emerald',className:'drip_ragezrlegend_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Ragezrlegend Gold',className:'drip_ragezrlegend_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Ragezrlegend Olive',className:'drip_ragezrlegend_olive',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Ragezrlegend Ruby',className:'drip_ragezrlegend_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Ragezrlegend Sapphire',className:'drip_ragezrlegend_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Ragezrlegend White',className:'drip_ragezrlegend_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Ragezrlegend Yellow',className:'drip_ragezrlegend_yellow',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Black',className:'drip_sandals_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Black Ftp',className:'drip_sandals_black_ftp',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Black Nike',className:'drip_sandals_black_nike',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Black Offwhite',className:'drip_sandals_black_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Black Pearl',className:'drip_sandals_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Sandals Blue Offwhite',className:'drip_sandals_blue_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Brown Lv',className:'drip_sandals_brown_lv',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Emerald',className:'drip_sandals_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Sandals Gold',className:'drip_sandals_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Sandals Green Offwhite',className:'drip_sandals_green_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Green Screen',className:'drip_sandals_green_screen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Hello Kitty',className:'drip_sandals_hello_kitty',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Lightb Gucci',className:'drip_sandals_lightb_gucci',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Lightb Lv',className:'drip_sandals_lightb_lv',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Navy',className:'drip_sandals_navy',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Orange Offwhite',className:'drip_sandals_orange_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Pink Offwhite',className:'drip_sandals_pink_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Red Jordan',className:'drip_sandals_red_jordan',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Red Offwhite',className:'drip_sandals_red_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Ruby',className:'drip_sandals_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Sapphire',className:'drip_sandals_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Sandals Stocking',className:'drip_sandals_stocking',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Victori Nike',className:'drip_sandals_victori_nike',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals White',className:'drip_sandals_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals White Ftp',className:'drip_sandals_white_ftp',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals White Lv',className:'drip_sandals_white_lv',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals White Nike',className:'drip_sandals_white_nike',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals White Offwhite',className:'drip_sandals_white_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Wrapping Paper',className:'drip_sandals_wrapping_paper',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Sandals Yellow Offwhite',className:'drip_sandals_yellow_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Black',className:'drip_socks_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Black Ftp',className:'drip_socks_black_ftp',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Black Nike',className:'drip_socks_black_nike',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Black Offwhite',className:'drip_socks_black_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Black Pearl',className:'drip_socks_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Socks Blue Offwhite',className:'drip_socks_blue_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Brown Lv',className:'drip_socks_brown_lv',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Emerald',className:'drip_socks_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Socks Gold',className:'drip_socks_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Socks Green Offwhite',className:'drip_socks_green_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Green Screen',className:'drip_socks_green_screen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Hello Kitty',className:'drip_socks_hello_kitty',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Lightb Gucci',className:'drip_socks_lightb_gucci',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Lightb Lv',className:'drip_socks_lightb_lv',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Navy',className:'drip_socks_navy',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Orange Offwhite',className:'drip_socks_orange_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Pink Offwhite',className:'drip_socks_pink_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Red Jordan',className:'drip_socks_red_jordan',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Red Offwhite',className:'drip_socks_red_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Ruby',className:'drip_socks_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Socks Sapphire',className:'drip_socks_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Socks Stocking',className:'drip_socks_stocking',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Victori Nike',className:'drip_socks_victori_nike',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks White',className:'drip_socks_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks White Ftp',className:'drip_socks_white_ftp',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks White Lv',className:'drip_socks_white_lv',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks White Nike',className:'drip_socks_white_nike',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks White Offwhite',className:'drip_socks_white_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Wrapping Paper',className:'drip_socks_wrapping_paper',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socks Yellow Offwhite',className:'drip_socks_yellow_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Black',className:'drip_socksandals_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Black Ftp',className:'drip_socksandals_black_ftp',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Black Nike',className:'drip_socksandals_black_nike',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Black Offwhite',className:'drip_socksandals_black_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Black Pearl',className:'drip_socksandals_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Blue Offwhite',className:'drip_socksandals_blue_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Brown Lv',className:'drip_socksandals_brown_lv',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Emerald',className:'drip_socksandals_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Gold',className:'drip_socksandals_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Green Offwhite',className:'drip_socksandals_green_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Green Screen',className:'drip_socksandals_green_screen',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Hello Kitty',className:'drip_socksandals_hello_kitty',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Lightb Gucci',className:'drip_socksandals_lightb_gucci',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Lightb Lv',className:'drip_socksandals_lightb_lv',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Navy',className:'drip_socksandals_navy',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Orange Offwhite',className:'drip_socksandals_orange_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Pink Offwhite',className:'drip_socksandals_pink_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Red Jordan',className:'drip_socksandals_red_jordan',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Red Offwhite',className:'drip_socksandals_red_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Ruby',className:'drip_socksandals_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Sapphire',className:'drip_socksandals_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Stocking',className:'drip_socksandals_stocking',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Victori Nike',className:'drip_socksandals_victori_nike',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals White',className:'drip_socksandals_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals White Black',className:'drip_socksandals_white_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals White Ftp',className:'drip_socksandals_white_ftp',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals White Lv',className:'drip_socksandals_white_lv',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals White Nike',className:'drip_socksandals_white_nike',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals White Offwhite',className:'drip_socksandals_white_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Wrapping Paper',className:'drip_socksandals_wrapping_paper',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Socksandals Yellow Offwhite',className:'drip_socksandals_yellow_offwhite',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Timberlandboots Black Pearl',className:'drip_timberlandboots_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Timberlandboots Dark Green Nubuck',className:'drip_timberlandboots_dark_green_nubuck',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Timberlandboots Dark Grey Nubuck',className:'drip_timberlandboots_dark_grey_nubuck',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Timberlandboots Emerald',className:'drip_timberlandboots_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Timberlandboots Gold',className:'drip_timberlandboots_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Timberlandboots Ruby',className:'drip_timberlandboots_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Timberlandboots Sapphire',className:'drip_timberlandboots_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Timberlandboots Wheat Nubuck',className:'drip_timberlandboots_wheat_nubuck',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Birch',className:'drip_vansslipon_birch',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Black',className:'drip_vansslipon_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Black Gray',className:'drip_vansslipon_black_gray',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Black Orange',className:'drip_vansslipon_black_orange',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Black Pearl',className:'drip_vansslipon_black_pearl',category:'Drippy Sneakers',sellPrice:7500,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Blushing',className:'drip_vansslipon_blushing',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Checkered Black',className:'drip_vansslipon_checkered_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Checkered Blue',className:'drip_vansslipon_checkered_blue',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Checkered Green',className:'drip_vansslipon_checkered_green',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Checkered Pink',className:'drip_vansslipon_checkered_pink',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Checkered Purple',className:'drip_vansslipon_checkered_purple',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Checkered Red',className:'drip_vansslipon_checkered_red',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Chilli Pepper',className:'drip_vansslipon_chilli_pepper',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Dakota Roche',className:'drip_vansslipon_dakota_roche',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Drizzle',className:'drip_vansslipon_drizzle',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Emerald',className:'drip_vansslipon_emerald',category:'Drippy Sneakers',sellPrice:8750,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Gold',className:'drip_vansslipon_gold',category:'Drippy Sneakers',sellPrice:10000,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Navy',className:'drip_vansslipon_navy',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Ruby',className:'drip_vansslipon_ruby',category:'Drippy Sneakers',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon Sapphire',className:'drip_vansslipon_sapphire',category:'Drippy Sneakers',sellPrice:12500,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon True Black',className:'drip_vansslipon_true_black',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Drip Vansslipon True White',className:'drip_vansslipon_true_white',category:'Drippy Sneakers',sellPrice:6250,traderSells:false,traderBuys:true},
{name:'Fallout Agility Bobblehead',className:'dlt_falloutz_bobbleheadagility',category:'Fallout Bobbleheads',sellPrice:11250,traderSells:false,traderBuys:true},
{name:'Fallout Barter Bobblehead',className:'dlt_falloutz_bobbleheadbarter',category:'Fallout Bobbleheads',sellPrice:11288,traderSells:false,traderBuys:true},
{name:'Fallout Base Bobblehead',className:'dlt_falloutz_bobbleheadbase',category:'Fallout Bobbleheads',sellPrice:11344,traderSells:false,traderBuys:true},
{name:'Fallout Big Guns Bobblehead',className:'dlt_falloutz_bobbleheadbiggun',category:'Fallout Bobbleheads',sellPrice:11381,traderSells:false,traderBuys:true},
{name:'Fallout Bobblehead Display Stand Kit',className:'dlt_falloutz_bobbleheadstandkit',category:'Fallout Bobbleheads',buyPrice:14558,traderSells:true,traderBuys:false},
{name:'Fallout Charisma Bobblehead',className:'dlt_falloutz_bobbleheadcharisma',category:'Fallout Bobbleheads',sellPrice:11438,traderSells:false,traderBuys:true},
{name:'Fallout Endurance Bobblehead',className:'dlt_falloutz_bobbleheadendurance',category:'Fallout Bobbleheads',sellPrice:11475,traderSells:false,traderBuys:true},
{name:'Fallout Energyweapons Bobblehead',className:'dlt_falloutz_bobbleheadenergyweapons',category:'Fallout Bobbleheads',sellPrice:11531,traderSells:false,traderBuys:true},
{name:'Fallout Explosive Bobblehead',className:'dlt_falloutz_bobbleheadexplosive',category:'Fallout Bobbleheads',sellPrice:11569,traderSells:false,traderBuys:true},
{name:'Fallout Intelligence Bobblehead',className:'dlt_falloutz_bobbleheadintelligence',category:'Fallout Bobbleheads',sellPrice:11606,traderSells:false,traderBuys:true},
{name:'Fallout Lockpicking Bobblehead',className:'dlt_falloutz_bobbleheadlockpicking',category:'Fallout Bobbleheads',sellPrice:11662,traderSells:false,traderBuys:true},
{name:'Fallout Luck Bobblehead',className:'dlt_falloutz_bobbleheadluck',category:'Fallout Bobbleheads',sellPrice:11700,traderSells:false,traderBuys:true},
{name:'Fallout Medicine Bobblehead',className:'dlt_falloutz_bobbleheadmedicine',category:'Fallout Bobbleheads',sellPrice:11738,traderSells:false,traderBuys:true},
{name:'Fallout Melee Bobblehead',className:'dlt_falloutz_bobbleheadmelee',category:'Fallout Bobbleheads',sellPrice:11775,traderSells:false,traderBuys:true},
{name:'Fallout Perception Bobblehead',className:'dlt_falloutz_bobbleheadperception',category:'Fallout Bobbleheads',sellPrice:11831,traderSells:false,traderBuys:true},
{name:'Fallout Repair Bobblehead',className:'dlt_falloutz_bobbleheadrepair',category:'Fallout Bobbleheads',sellPrice:11869,traderSells:false,traderBuys:true},
{name:'Fallout Science Bobblehead',className:'dlt_falloutz_bobbleheadscience',category:'Fallout Bobbleheads',sellPrice:11925,traderSells:false,traderBuys:true},
{name:'Fallout Small Guns Bobblehead',className:'dlt_falloutz_bobbleheadsmallgun',category:'Fallout Bobbleheads',sellPrice:11962,traderSells:false,traderBuys:true},
{name:'Fallout Sneak Bobblehead',className:'dlt_falloutz_bobbleheadsneak',category:'Fallout Bobbleheads',sellPrice:12000,traderSells:false,traderBuys:true},
{name:'Fallout Speech Bobblehead',className:'dlt_falloutz_bobbleheadspeech',category:'Fallout Bobbleheads',sellPrice:12056,traderSells:false,traderBuys:true},
{name:'Fallout Strength Bobblehead',className:'dlt_falloutz_bobbleheadstrength',category:'Fallout Bobbleheads',sellPrice:12169,traderSells:false,traderBuys:true},
{name:'Fallout Unarmed Bobblehead',className:'dlt_falloutz_bobbleheadunarmed',category:'Fallout Bobbleheads',sellPrice:12188,traderSells:false,traderBuys:true},
{name:'Fallout Eyebot Toy',className:'fallout_eyebottoy',category:'Fallout Collectables',sellPrice:1250000,traderSells:false,traderBuys:true},
{name:'Fallout Rocket Toy',className:'fallout_rockettoy',category:'Fallout Collectables',sellPrice:1250000,traderSells:false,traderBuys:true},
{name:'Fallout Sheriff Badge',className:'fallout_sheriffbadge',category:'Fallout Collectables',sellPrice:1250000,traderSells:false,traderBuys:true},
{name:'Fallout Nuka-Cola Cherry',className:'dlt_falloutz_nukacola_cherry',category:'Fallout Nuka-Cola',sellPrice:15125,traderSells:false,traderBuys:true},
{name:'Fallout Nuka-Cola Classic',className:'dlt_falloutz_nukacola',category:'Fallout Nuka-Cola',sellPrice:15000,traderSells:false,traderBuys:true},
{name:'Fallout Nuka-Cola Dark',className:'dlt_falloutz_nukacola_dark',category:'Fallout Nuka-Cola',sellPrice:15250,traderSells:false,traderBuys:true},
{name:'Fallout Nuka-Cola Display Rack Kit',className:'dlt_falloutz_nukacolarackkit',category:'Fallout Nuka-Cola',sellPrice:15625,traderSells:false,traderBuys:true},
{name:'Fallout Nuka-Cola Grape',className:'dlt_falloutz_nukacola_grape',category:'Fallout Nuka-Cola',sellPrice:15375,traderSells:false,traderBuys:true},
{name:'Fallout Nuka-Cola Orange',className:'dlt_falloutz_nukacola_orange',category:'Fallout Nuka-Cola',sellPrice:15500,traderSells:false,traderBuys:true},
{name:'Fallout Nuka-Cola Quantum',className:'dlt_falloutz_nukacola_quantum',category:'Fallout Nuka-Cola',sellPrice:16250,traderSells:false,traderBuys:true},
{name:'Paragon Axe Gold',className:'paragon_axe_gold',category:'Paragon Collectables',sellPrice:21380,traderSells:false,traderBuys:true},
{name:'Paragon Axe Silver',className:'paragon_axe_silver',category:'Paragon Collectables',sellPrice:21675,traderSells:false,traderBuys:true},
{name:'Paragon Bitcoin',className:'paragon_bitcoin',category:'Paragon Collectables',sellPrice:21750,traderSells:false,traderBuys:true},
{name:'Paragon Canister Blue',className:'paragon_canister_blue',category:'Paragon Collectables',sellPrice:20352,traderSells:false,traderBuys:true},
{name:'Paragon Canister Red',className:'paragon_canister_red',category:'Paragon Collectables',sellPrice:22739,traderSells:false,traderBuys:true},
{name:'Paragon Canister White',className:'paragon_canister_white',category:'Paragon Collectables',sellPrice:19885,traderSells:false,traderBuys:true},
{name:'Paragon Canister Yellow',className:'paragon_canister_yellow',category:'Paragon Collectables',sellPrice:22322,traderSells:false,traderBuys:true},
{name:'Paragon Crown',className:'paragon_crown',category:'Paragon Collectables',sellPrice:20812,traderSells:false,traderBuys:true},
{name:'Paragon Crystal Blue',className:'paragon_crystal_blue',category:'Paragon Collectables',sellPrice:19406,traderSells:false,traderBuys:true},
{name:'Paragon Crystal Green',className:'paragon_crystal_green',category:'Paragon Collectables',sellPrice:19548,traderSells:false,traderBuys:true},
{name:'Paragon Crystal Pink',className:'paragon_crystal_pink',category:'Paragon Collectables',sellPrice:23432,traderSells:false,traderBuys:true},
{name:'Paragon Crystal Purple',className:'paragon_crystal_purple',category:'Paragon Collectables',sellPrice:23438,traderSells:false,traderBuys:true},
{name:'Paragon Crystal Rainbow',className:'paragon_crystal_rainbow',category:'Paragon Collectables',sellPrice:18862,traderSells:false,traderBuys:true},
{name:'Paragon Crystal Red',className:'paragon_crystal_red',category:'Paragon Collectables',sellPrice:21239,traderSells:false,traderBuys:true},
{name:'Paragon Crystal Yellow',className:'paragon_crystal_yellow',category:'Paragon Collectables',sellPrice:22912,traderSells:false,traderBuys:true},
{name:'Paragon Cube Blue',className:'paragon_cube_blue',category:'Paragon Collectables',sellPrice:18778,traderSells:false,traderBuys:true},
{name:'Paragon Cube Green',className:'paragon_cube_green',category:'Paragon Collectables',sellPrice:22350,traderSells:false,traderBuys:true},
{name:'Paragon Cube White',className:'paragon_cube_white',category:'Paragon Collectables',sellPrice:20888,traderSells:false,traderBuys:true},
{name:'Paragon Diamond Blue',className:'paragon_diamond_blue',category:'Paragon Collectables',sellPrice:21408,traderSells:false,traderBuys:true},
{name:'Paragon Diamond Green',className:'paragon_diamond_green',category:'Paragon Collectables',sellPrice:21975,traderSells:false,traderBuys:true},
{name:'Paragon Diamond Pink',className:'paragon_diamond_pink',category:'Paragon Collectables',sellPrice:18852,traderSells:false,traderBuys:true},
{name:'Paragon Diamond Purple',className:'paragon_diamond_purple',category:'Paragon Collectables',sellPrice:22462,traderSells:false,traderBuys:true},
{name:'Paragon Diamond Red',className:'paragon_diamond_red',category:'Paragon Collectables',sellPrice:20785,traderSells:false,traderBuys:true},
{name:'Paragon Diamond White',className:'paragon_diamond_white',category:'Paragon Collectables',sellPrice:19922,traderSells:false,traderBuys:true},
{name:'Paragon Documents',className:'paragon_documents',category:'Paragon Collectables',sellPrice:21300,traderSells:false,traderBuys:true},
{name:'Paragon Ds',className:'paragon_ds',category:'Paragon Collectables',sellPrice:18895,traderSells:false,traderBuys:true},
{name:'Paragon Gameboy Blue',className:'paragon_gameboy_blue',category:'Paragon Collectables',sellPrice:22768,traderSells:false,traderBuys:true},
{name:'Paragon Gameboy Green',className:'paragon_gameboy_green',category:'Paragon Collectables',sellPrice:21375,traderSells:false,traderBuys:true},
{name:'Paragon Gameboy Red',className:'paragon_gameboy_red',category:'Paragon Collectables',sellPrice:20170,traderSells:false,traderBuys:true},
{name:'Paragon Gameboy Yellow',className:'paragon_gameboy_yellow',category:'Paragon Collectables',sellPrice:18919,traderSells:false,traderBuys:true},
{name:'Paragon Glowrock Blue',className:'paragon_glowrock_blue',category:'Paragon Collectables',sellPrice:19640,traderSells:false,traderBuys:true},
{name:'Paragon Glowrock Green',className:'paragon_glowrock_green',category:'Paragon Collectables',sellPrice:21075,traderSells:false,traderBuys:true},
{name:'Paragon Glowrock Orange',className:'paragon_glowrock_orange',category:'Paragon Collectables',sellPrice:20264,traderSells:false,traderBuys:true},
{name:'Paragon Glowrock Pink',className:'paragon_glowrock_pink',category:'Paragon Collectables',sellPrice:20518,traderSells:false,traderBuys:true},
{name:'Paragon Glowrock Red',className:'paragon_glowrock_red',category:'Paragon Collectables',sellPrice:21718,traderSells:false,traderBuys:true},
{name:'Paragon Goldbar',className:'paragon_goldbar',category:'Paragon Collectables',sellPrice:19519,traderSells:false,traderBuys:true},
{name:'Paragon Goldbar Stack',className:'paragon_goldbar_stack',category:'Paragon Collectables',sellPrice:22856,traderSells:false,traderBuys:true},
{name:'Paragon Intel',className:'paragon_intel',category:'Paragon Collectables',sellPrice:21140,traderSells:false,traderBuys:true},
{name:'Paragon Kaws Black',className:'paragon_kaws_black',category:'Paragon Collectables',sellPrice:21844,traderSells:false,traderBuys:true},
{name:'Paragon Kaws Blue',className:'paragon_kaws_blue',category:'Paragon Collectables',sellPrice:20001,traderSells:false,traderBuys:true},
{name:'Paragon Kaws Red',className:'paragon_kaws_red',category:'Paragon Collectables',sellPrice:21665,traderSells:false,traderBuys:true},
{name:'Paragon Kaws White',className:'paragon_kaws_white',category:'Paragon Collectables',sellPrice:19472,traderSells:false,traderBuys:true},
{name:'Paragon Lion',className:'paragon_lion',category:'Paragon Collectables',sellPrice:22340,traderSells:false,traderBuys:true},
{name:'Paragon Money',className:'paragon_money',category:'Paragon Collectables',sellPrice:23428,traderSells:false,traderBuys:true},
{name:'Paragon Silver Stack',className:'paragon_silver_stack',category:'Paragon Collectables',sellPrice:19392,traderSells:false,traderBuys:true},
{name:'Paragon Silverbar',className:'paragon_silverbar',category:'Paragon Collectables',sellPrice:22214,traderSells:false,traderBuys:true},
{name:'Paragon Skull Gold',className:'paragon_skull_gold',category:'Paragon Collectables',sellPrice:19088,traderSells:false,traderBuys:true},
{name:'Paragon Skull Silver',className:'paragon_skull_silver',category:'Paragon Collectables',sellPrice:19186,traderSells:false,traderBuys:true},
{name:'Paragon Sword Gold',className:'paragon_sword_gold',category:'Paragon Collectables',sellPrice:19012,traderSells:false,traderBuys:true},
{name:'Paragon Sword Silver',className:'paragon_sword_silver',category:'Paragon Collectables',sellPrice:22940,traderSells:false,traderBuys:true},
{name:'Paragon Triangle Orange',className:'paragon_triangle_orange',category:'Paragon Collectables',sellPrice:22660,traderSells:false,traderBuys:true},
{name:'Paragon Triangle Red',className:'paragon_triangle_red',category:'Paragon Collectables',sellPrice:22026,traderSells:false,traderBuys:true},
{name:'Paragon Triangle White',className:'paragon_triangle_white',category:'Paragon Collectables',sellPrice:19261,traderSells:false,traderBuys:true},
{name:'Paragon Trophy Bronze',className:'paragon_trophy_bronze',category:'Paragon Collectables',sellPrice:20976,traderSells:false,traderBuys:true},
{name:'Paragon Trophy Gold',className:'paragon_trophy_gold',category:'Paragon Collectables',sellPrice:22950,traderSells:false,traderBuys:true},
{name:'Paragon Trophy Silver',className:'paragon_trophy_silver',category:'Paragon Collectables',sellPrice:22490,traderSells:false,traderBuys:true},
{name:'Paragon Wii',className:'paragon_wii',category:'Paragon Collectables',sellPrice:22538,traderSells:false,traderBuys:true},
{name:'Sealed Pokémon Collection Box 1',className:'pokemoncard_sealedbox1',category:'Pokémon Collection Boxes',sellPrice:2500000,traderSells:false,traderBuys:true},
{name:'Sealed Pokémon Collection Box 2',className:'pokemoncard_sealedbox2',category:'Pokémon Collection Boxes',sellPrice:2500000,traderSells:false,traderBuys:true},
{name:'Sealed Pokémon Collection Box 3',className:'pokemoncard_sealedbox3',category:'Pokémon Collection Boxes',sellPrice:2500000,traderSells:false,traderBuys:true},
{name:'Sealed Pokémon Collection Box 4',className:'pokemoncard_sealedbox4',category:'Pokémon Collection Boxes',sellPrice:2500000,traderSells:false,traderBuys:true},
{name:'Sealed Pokémon Collection Box 5',className:'pokemoncard_sealedbox5',category:'Pokémon Collection Boxes',sellPrice:2500000,traderSells:false,traderBuys:true},
{name:'Vyse Intel Folder',className:'vyse_intel_folder',category:'Vyse Collectables',sellPrice:18495,traderSells:false,traderBuys:true},
{name:'Vyse Labubu Black',className:'vyse_labubu_black',category:'Vyse Collectables',sellPrice:17728,traderSells:false,traderBuys:true},
{name:'Vyse Labubu Blue',className:'vyse_labubu_blue',category:'Vyse Collectables',sellPrice:18331,traderSells:false,traderBuys:true},
{name:'Vyse Labubu Gold',className:'vyse_labubu_gold',category:'Vyse Collectables',sellPrice:18790,traderSells:false,traderBuys:true},
{name:'Vyse Labubu Green',className:'vyse_labubu_green',category:'Vyse Collectables',sellPrice:17936,traderSells:false,traderBuys:true},
{name:'Vyse Labubu Horror',className:'vyse_labubu_horror',category:'Vyse Collectables',sellPrice:19202,traderSells:false,traderBuys:true},
{name:'Vyse Labubu Pink',className:'vyse_labubu_pink',category:'Vyse Collectables',sellPrice:18458,traderSells:false,traderBuys:true},
{name:'Vyse Labubu Redbull',className:'vyse_labubu_redbull',category:'Vyse Collectables',sellPrice:18720,traderSells:false,traderBuys:true},
{name:'Vyse Lego Batman',className:'vyse_lego_batman',category:'Vyse Collectables',sellPrice:18156,traderSells:false,traderBuys:true},
{name:'Vyse Lego Darth Vader',className:'vyse_lego_darth_vader',category:'Vyse Collectables',sellPrice:17599,traderSells:false,traderBuys:true},
{name:'Vyse Lego Spider Man',className:'vyse_lego_spider_man',category:'Vyse Collectables',sellPrice:18832,traderSells:false,traderBuys:true},
{name:'Vyse Lootlord',className:'vyse_lootlord',category:'Vyse Collectables',sellPrice:18850,traderSells:false,traderBuys:true},
{name:'Vyse Monster Labubu',className:'vyse_monster_labubu',category:'Vyse Collectables',sellPrice:18475,traderSells:false,traderBuys:true},
{name:'Vyse Mouse',className:'vyse_mouse',category:'Vyse Collectables',sellPrice:18312,traderSells:false,traderBuys:true},
{name:'Vyse Nintendo Switch',className:'vyse_nintendo_switch',category:'Vyse Collectables',sellPrice:17968,traderSells:false,traderBuys:true},
{name:'Vyse Pokemon Greatball',className:'vyse_pokemon_greatball',category:'Vyse Collectables',sellPrice:19334,traderSells:false,traderBuys:true},
{name:'Vyse Pokemon Masterball',className:'vyse_pokemon_masterball',category:'Vyse Collectables',sellPrice:19736,traderSells:false,traderBuys:true},
{name:'Vyse Pokemon Pokeball',className:'vyse_pokemon_pokeball',category:'Vyse Collectables',sellPrice:18944,traderSells:false,traderBuys:true},
{name:'Vyse Ps3 Controller',className:'vyse_ps3_controller',category:'Vyse Collectables',sellPrice:19129,traderSells:false,traderBuys:true},
{name:'Vyse Ps4 Godofwar',className:'vyse_ps4_godofwar',category:'Vyse Collectables',sellPrice:17591,traderSells:false,traderBuys:true},
{name:'Vyse Ps4 Grandtheftautov',className:'vyse_ps4_grandtheftautov',category:'Vyse Collectables',sellPrice:19906,traderSells:false,traderBuys:true},
{name:'Vyse Ps4 Horizonzerodawn',className:'vyse_ps4_horizonzerodawn',category:'Vyse Collectables',sellPrice:17636,traderSells:false,traderBuys:true},
{name:'Vyse Ps4 Madmax',className:'vyse_ps4_madmax',category:'Vyse Collectables',sellPrice:18754,traderSells:false,traderBuys:true},
{name:'Vyse Ps4 Rdr2',className:'vyse_ps4_rdr2',category:'Vyse Collectables',sellPrice:18161,traderSells:false,traderBuys:true},
{name:'Vyse Ps4 Shadowofthecolossus',className:'vyse_ps4_shadowofthecolossus',category:'Vyse Collectables',sellPrice:19526,traderSells:false,traderBuys:true},
{name:'Vyse Ps4 Spiderman',className:'vyse_ps4_spiderman',category:'Vyse Collectables',sellPrice:18206,traderSells:false,traderBuys:true},
{name:'Vyse Ps4 Thelastofus',className:'vyse_ps4_thelastofus',category:'Vyse Collectables',sellPrice:18386,traderSells:false,traderBuys:true},
{name:'Vyse Ps4 Uncharted4',className:'vyse_ps4_uncharted4',category:'Vyse Collectables',sellPrice:19891,traderSells:false,traderBuys:true},
{name:'Vyse Ps4 Untildawn',className:'vyse_ps4_untildawn',category:'Vyse Collectables',sellPrice:19329,traderSells:false,traderBuys:true},
{name:'Vyse Rolex',className:'vyse_rolex',category:'Vyse Collectables',sellPrice:17942,traderSells:false,traderBuys:true},
{name:'Vyse Scifi Energy Capsule',className:'vyse_scifi_energy_capsule',category:'Vyse Collectables',sellPrice:19455,traderSells:false,traderBuys:true},
{name:'Vyse Tamagotchi',className:'vyse_tamagotchi',category:'Vyse Collectables',sellPrice:19630,traderSells:false,traderBuys:true},
{name:'Vyse Wisdom Book',className:'vyse_wisdom_book',category:'Vyse Collectables',sellPrice:17500,traderSells:false,traderBuys:true},
{name:'Vyse Xbox',className:'vyse_xbox',category:'Vyse Collectables',sellPrice:19919,traderSells:false,traderBuys:true},
{name:'Vyse Xboxcontroller',className:'vyse_xboxcontroller',category:'Vyse Collectables',sellPrice:18278,traderSells:false,traderBuys:true},
{name:'Vyse Yugioh Case',className:'vyse_yugioh_case',category:'Vyse Collectables',sellPrice:19936,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 1',className:'vyse_yugioh_card_01',category:'Vyse Collectables',sellPrice:19204,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 10',className:'vyse_yugioh_card_10',category:'Vyse Collectables',sellPrice:19088,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 11',className:'vyse_yugioh_card_11',category:'Vyse Collectables',sellPrice:19852,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 12',className:'vyse_yugioh_card_12',category:'Vyse Collectables',sellPrice:19099,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 13',className:'vyse_yugioh_card_13',category:'Vyse Collectables',sellPrice:19659,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 14',className:'vyse_yugioh_card_14',category:'Vyse Collectables',sellPrice:18549,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 15',className:'vyse_yugioh_card_15',category:'Vyse Collectables',sellPrice:17698,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 16',className:'vyse_yugioh_card_16',category:'Vyse Collectables',sellPrice:19921,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 17',className:'vyse_yugioh_card_17',category:'Vyse Collectables',sellPrice:18966,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 18',className:'vyse_yugioh_card_18',category:'Vyse Collectables',sellPrice:19638,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 19',className:'vyse_yugioh_card_19',category:'Vyse Collectables',sellPrice:19361,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 2',className:'vyse_yugioh_card_02',category:'Vyse Collectables',sellPrice:18344,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 20',className:'vyse_yugioh_card_20',category:'Vyse Collectables',sellPrice:19255,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 21',className:'vyse_yugioh_card_21',category:'Vyse Collectables',sellPrice:19081,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 22',className:'vyse_yugioh_card_22',category:'Vyse Collectables',sellPrice:17569,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 23',className:'vyse_yugioh_card_23',category:'Vyse Collectables',sellPrice:17664,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 24',className:'vyse_yugioh_card_24',category:'Vyse Collectables',sellPrice:18724,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 25',className:'vyse_yugioh_card_25',category:'Vyse Collectables',sellPrice:18088,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 26',className:'vyse_yugioh_card_26',category:'Vyse Collectables',sellPrice:19468,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 27',className:'vyse_yugioh_card_27',category:'Vyse Collectables',sellPrice:19645,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 28',className:'vyse_yugioh_card_28',category:'Vyse Collectables',sellPrice:17758,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 29',className:'vyse_yugioh_card_29',category:'Vyse Collectables',sellPrice:18741,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 3',className:'vyse_yugioh_card_03',category:'Vyse Collectables',sellPrice:19666,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 30',className:'vyse_yugioh_card_30',category:'Vyse Collectables',sellPrice:19435,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 31',className:'vyse_yugioh_card_31',category:'Vyse Collectables',sellPrice:18189,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 32',className:'vyse_yugioh_card_32',category:'Vyse Collectables',sellPrice:18559,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 33',className:'vyse_yugioh_card_33',category:'Vyse Collectables',sellPrice:19982,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 34',className:'vyse_yugioh_card_34',category:'Vyse Collectables',sellPrice:20000,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 35',className:'vyse_yugioh_card_35',category:'Vyse Collectables',sellPrice:18872,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 36',className:'vyse_yugioh_card_36',category:'Vyse Collectables',sellPrice:18998,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 37',className:'vyse_yugioh_card_37',category:'Vyse Collectables',sellPrice:19872,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 38',className:'vyse_yugioh_card_38',category:'Vyse Collectables',sellPrice:19795,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 39',className:'vyse_yugioh_card_39',category:'Vyse Collectables',sellPrice:18329,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 4',className:'vyse_yugioh_card_04',category:'Vyse Collectables',sellPrice:17586,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 40',className:'vyse_yugioh_card_40',category:'Vyse Collectables',sellPrice:18574,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 41',className:'vyse_yugioh_card_41',category:'Vyse Collectables',sellPrice:17769,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 42',className:'vyse_yugioh_card_42',category:'Vyse Collectables',sellPrice:19844,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 43',className:'vyse_yugioh_card_43',category:'Vyse Collectables',sellPrice:18878,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 44',className:'vyse_yugioh_card_44',category:'Vyse Collectables',sellPrice:19756,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 45',className:'vyse_yugioh_card_45',category:'Vyse Collectables',sellPrice:17974,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 46',className:'vyse_yugioh_card_46',category:'Vyse Collectables',sellPrice:18594,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 47',className:'vyse_yugioh_card_47',category:'Vyse Collectables',sellPrice:19331,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 48',className:'vyse_yugioh_card_48',category:'Vyse Collectables',sellPrice:19684,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 49',className:'vyse_yugioh_card_49',category:'Vyse Collectables',sellPrice:19149,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 5',className:'vyse_yugioh_card_05',category:'Vyse Collectables',sellPrice:19865,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 50',className:'vyse_yugioh_card_50',category:'Vyse Collectables',sellPrice:18870,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 51',className:'vyse_yugioh_card_51',category:'Vyse Collectables',sellPrice:19871,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 6',className:'vyse_yugioh_card_06',category:'Vyse Collectables',sellPrice:17522,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 7',className:'vyse_yugioh_card_07',category:'Vyse Collectables',sellPrice:18468,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 8',className:'vyse_yugioh_card_08',category:'Vyse Collectables',sellPrice:19838,traderSells:false,traderBuys:true},
{name:'Yu-Gi-Oh! Card 9',className:'vyse_yugioh_card_09',category:'Vyse Collectables',sellPrice:18784,traderSells:false,traderBuys:true}
]};
